### ISSUE TITLE
Command line is inconsistent:  --rpcport vs. --p2p-port

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#1012]
I'm thinking of writing a patch to accept the following hyphenated command line options in addition to their non-hyphenated counterparts:

- `--rpc-user`
- `--rpc-password`
- `--rpc-port`
- `--httpd-endpoint`
- `--http-port`

I think we should prefer the hyphenated versions (e.g. not showing non-hyphenated versions in help).  I'm also thinking of printing a deprecation warning if non-hyphenated versions are used, but I think we need to continue to support non-hyphenated usage for backward compatibility with existing scripts at least until the next major upgrade.

**Comment by vikramrajkumar** [comment]
Too low priority.
