### ISSUE TITLE
UIA / BitAsset market pairs don't work

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#1031]
Trying one way:

    wallet_market_submit_ask alice 1000 DOGS 0.0025 USD
    {"id":32,"error":{"message":"invalid market (37001)\\n\\n\\n\\n","detail":"37001 invalid_market: invalid market\\n\\n    {\\"quote_id\\":1,\\"base_id\\":2}\\n    th_a  chain_database.cpp:2448 get_market_bids\\n\\n    {\\"quote_symbol\\":\\"USD\\",\\"base_symbol\\":\\"DOGS\\",\\"limit\\":1}\\n    th_a  chain_database.cpp:2502 get_market_bids\\n\\n    {}\\n    th_a  common_api_client.cpp:1891 wallet_market_submit_ask","code":37001}}

Trying the other way:

    wallet_market_submit_ask alice 2 USD 400 DOGS
    {"id":32,"error":{"message":"unspecified (0)\\nUnable to pay fee; no remaining balances can cover it and no account can pay it.\\nAll balances: [[[\\"XTSH8fShbqeTGCsb8Ko97JMDiZppYeaK4S8t\\",1],-20000]]\\n\\n\\n\\n","detail":"0 exception: unspecified\\nUnable to pay fee; no remaining balances can cover it and no account can pay it.\\n    {}\\n    th_a  transaction_builder.cpp:781 pay_fee\\nAll balances: [[[\\"XTSH8fShbqeTGCsb8Ko97JMDiZppYeaK4S8t\\",1],-20000]]\\n    {\\"bals\\":[[[\\"XTSH8fShbqeTGCsb8Ko97JMDiZppYeaK4S8t\\",1],-20000]]}\\n    th_a  transaction_builder.cpp:782 pay_fee\\n\\n    {\\"trx\\":{\\"expiration\\":\\"1970-01-01T00:00:00\\",\\"delegate_slate_id\\":null,\\"operations\\":[{\\"type\\":\\"ask_op_type\\",\\"data\\":{\\"amount\\":20000,\\"ask_index\\":{\\"order_price\\":{\\"ratio\\":\\"400.\\",\\"quote_asset_id\\":2,\\"base_asset_id\\":1},\\"owner\\":\\"XTS7ojHvpj96BqqUHvD2sfo4DHFaZnbeeXEB\\"}}}],\\"signatures\\":[]}}\\n    th_a  transaction_builder.cpp:711 finalize\\n\\n    {\\"from_account_name\\":\\"alice\\",\\"real_quantity\\":\\"2\\",\\"quantity_symbol\\":\\"USD\\",\\"quote_price\\":\\"400\\",\\"quote_symbol\\":\\"DOGS\\",\\"sign\\":true}\\n    th_a  wallet.cpp:3661 submit_ask\\n\\n    {}\\n    th_a  common_api_client.cpp:1891 wallet_market_submit_ask","code":0}}

**Comment by vikramrajkumar** [comment]
I suspect this was just confusion about the arguments.

On BitShares the ROSE/CNY market seems to have been operating.
