### ISSUE TITLE
Wallet don't recognizes the password after: "wallet_change_passphrase <passphrase>" and the passphrase has spaces included!!!

### ISSUE THREAD

**Issue by liondani** [BitShares/bitshares#1054]
I was experimenting with "wallet_change_passphrase <passphrase>" command and a password manager (keepass2) with a new test wallet I created (thanks God!)... 
Many times I couldn't use the last password I had created, and  that resulted a useless wallet...finally I realized why that happened !
Whenever the password-manager created a password with spaces in them, in reality the wallet takes the passwords until it reaches the first space... so for example:
wallet_change_passphrase 12345678910 111213141516
has a result of a new password : 12345678910 
and ignores the space and the other characters after that!!
The problem is that after the command the output is :   "ok"
So the user has no clue what happened in reality and he thinks that the right password is:
123456789 10111213141516
so when he tries to input it after he reopens the wallet the systems informs him that the password is "wrong"... It is a very tricky situation when you don't know that the system does not allow spaces in the password!!!

PS It would be nice also to have an option on the wallet to change the password that is hiding what is typed with asterisks and demands a password confirmation!

**Comment by bitAndy** [comment]
This problem happened to me when I tried to change my passphrase about a month ago. What's strange is that my previous passphrase that I created when it was BitsharesX had a space and had no problems.
