### ISSUE TITLE
Incorrect fee in Bit asset yield transaction

### ISSUE THREAD

**Issue by janx** [BitShares/bitshares#1064]
![selection_364](https://cloud.githubusercontent.com/assets/5958/5198269/b86b0b50-7589-11e4-9ee6-5a1f57b283d4.png)

I transfered 1 CNY from account A to B. The screenshot is what I get by 'wallet_account_transaction_history'.

As you can see, tx fee is incorrectly set to 0, while amount is incorrectly set to total (amount + fee).

Only happens when there's yield.

**Comment by vikramrajkumar** [comment]
Unlikely to be properly fixed until #845.

**Comment by vikramrajkumar** [comment]
Possibly mitigated by https://github.com/BitShares/bitshares/commit/2549c003f6b430d2f7e0ae26aab298c1d28e990d, otherwise unlikely to be fixed until #845.
