### ISSUE TITLE
Create Restricted Asset Test

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1097]
wallet_asset_create TEST TestName issuer "no desc" 1000000.0 100 null false 
wallet_asset_update TEST null null null null null 0 ["restricted"]  ["restricted","retractable","market_halt"] issuer

wallet_asset_issue 100.0 TEST receiver_account "memo"   // should fail, receiver account active key is not authorized

All three of the following commands should do the same thing and need to be tested as valid
wallet_asset_authorize_key issuer TEST active_key_address_of_receiver 0 
wallet_asset_authorize_key issuer TEST public_key_of_receiver 0
wallet_asset_authorize_key issuer TEST account_name_of_receiver2 0

// this should work now
wallet_asset_issue 100.0 TEST receiver_account "memo"   // should fail, receiver account active key is not authorized
wallet_transfer from receiver to receiver2

// revoke authorization (-1) 
wallet_asset_authorize_key issuer TEST account_name_of_receiver2 -1

// this should fail now
wallet_transfer from receiver to receiver2

// this should also fail, receiver2 funds are frozen. 
wallet_transfer from receiver2 to receiver

**Comment by theoreticalbts** [comment]
Substantial work has been done on this, it's just not referenced in the ticket:  87bd07a78f934097967914d684517615e5877578 63029cf79cd372b0b623b51b57f778a26f693e71 d1b6c0fc42c7479765535c1bf300cf9a18c5b24a 247c0e3d760589fb0a0cf6da51fa9b2d14a7015e

**Comment by vikramrajkumar** [comment]
Progress: #1424

**Comment by vikramrajkumar** [comment]
The specifically mentioned cases in the OP are more-or-less covered by: https://github.com/BitShares/bitshares/blob/9a73ebfec644ab81d2820c18f953368996f175df/tests/btstests/advanced_uia/issue_restricted_uia_exception/issue_restricted_uia_exception.btstest
