### ISSUE TITLE
Specifying an optional argument on the CLI requires all earlier arguments to be specified

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#1108]
When implementing #1097, the command being tested has many optional parameters:

    symbol (asset_symbol, required): the ticker symbol for the asset to update
    name (optional_string, optional, defaults to null): the new name to give the asset; or null to keep the current name
    description (optional_string, optional, defaults to null): the new description to give the asset; or null to keep the current description
    public_data (optional_variant, optional, defaults to null): the new public_data to give the asset; or null to keep the current public_data
    maximum_share_supply (optional_double, optional, defaults to null): the new maximum_share_supply to give the asset; or null to keep the current maximum_share_supply
    precision (optional_uint64_t, optional, defaults to null): the new precision to give the asset; or null to keep the current precision
    issuer_transaction_fee (share_type, optional, defaults to 0): an additional fee (denominated in issued asset) charged by the issuer on every transaction that uses this asset type
    flags (asset_permission_array, optional, defaults to []): a set of flags set by the issuer (if they have permission to set them)
    issuer_permissions (asset_permission_array, optional, defaults to ["retractable","market_halt","balance_halt","supply_limit"]): a set of permissions an issuer retains
    issuer_account_name (account_name, optional, defaults to ""): used to transfer the asset to a new user
    required_sigs (uint32_t, optional, defaults to 0): number of signatures from the authority required to control this asset record
    authority (address_list, optional, defaults to []): owner keys that control this asset record

I want to specify only a couple later parameters:  `flags` and `issuer_permissions`.  I should be able to type:

    wallet_asset_update TEST flags=["restricted"] issuer_permissions=["restricted", "retractable", "market_halt"]

but this syntax is currently unsupported.

**Comment by vikramrajkumar** [comment]
This would be nice, but unlikely to happen anytime soon I think. Since the offending command that prompted the OP has been removed (https://github.com/BitShares/bitshares/commit/9a73ebfec644ab81d2820c18f953368996f175df), I will close this for now.
