### ISSUE TITLE
Unable to delete messages using mail_remove_message

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1118]
Using rpc call `mail_remove_message` any messages that have a status of `received`.  This is the typical inbox, so no messages can be removed from the inbox.

This is the test to re-produce the problem:
```
~/bitshares/bitshares/tests/acceptance_tests
cucumber features/mail_removal.feature 
```

This should fail as follows:
```
...
    Then bob should delete my message     # features/step_definitions/mail_steps.rb:69
      Mail id 00074dc445e291d967ebbe188dacf88c02cd0e4d was not deleted (RuntimeError)
```

**Comment by vikramrajkumar** [comment]
Development on the mail system has been halted for the foreseeable future.
