### ISSUE TITLE
light-weight and native client interoperability

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1146]
I believe I have identified a few required things we need to have functional light-weight clients (lw, client that goes do not have a full block-chain) interoperate with the full-client bitshares_client.  

Keep in mind this scenario: same account in both places (bitshares_client and web or mobile) and support transactions sent from either.  

Option (3) is provided should something get “lost in the mail.”

1..3 are for bitshares_client native 
1..2 are for lw clients like BitShares-JS

1. transactions delivered to sender's mailbox ( not just receiver )
2. upon fetching remote mailboxes, insert transactions into the user's wallet making sure to update balance records
3. public re-scan feature ( json authenticated ) where X (could be blocks of 100, 1000, etc) public keys are provided and matching transactions are returned ( the lw client will be required to encrypt and insert into send/receive mailboxes is missing )

- [ ] Option 1 lets the user send something from the native client then go to the same account on there lw-web wallet which will check the mailbox and then get that transaction and process it into their wallet..

- [ ] Option 2 lets the user send something from the lw-web as there lw client will implement 1.  Now they can go back to bitshares_client (or qt wallet) and that will check their mailbox and process the transaction into their wallet.

- [ ] Option 3 may be scheduled by a web front end to happen off hours.  It should be fine to have a long standing RPC connection, this will not happen live over the www anyways.

**Comment by vikramrajkumar** [comment]
@jcalfee Is this still relevant?

**Comment by vikramrajkumar** [comment]
I assume this is can be closed since the light wallet and hosted wallet are now undergoing public testing.
