### ISSUE TITLE
History is empty sending BTS to public account with active key

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#1153]
This may already be fixed on testnet, but I ran into this problem on mainnet:

- Create new public account
- Change active key of new account
- Create new wallet in new data directory
- Import active key into new wallet
- Send BTS to new account

The newly sent BTS shows properly in the balance, but the transaction history is empty.

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php?topic=13687.msg178580#msg178580
