### ISSUE TITLE
On-blockchain upgrade announcement channel

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1164]
Almost 24 hours after the upgrade has been released, many delegates have not upgraded.  (Including some developers and init delegates.)

Perhaps we should consider publishing upgrade information in the profile of a multisig public account signed by all developers?  E.g.

    {
    "available_upgrades" : [{"git-tag" : "v0.4.27",
                             "git-commit-hash" : "59f6c1f1f77aaad5086b89c3a2d0a4b6dfbadfe6",
                             "dmg-hash" : "785fa2134f97710f6187a5c6e495e9e5cdfc67c7",
                             "exe-hash" : "73b52181d6ffb8d4ce98a319faf132c3970de7ca",
                             "release-date" : "20141217T<whatever>",
                             "security-advisory" : {"delegate" : true, "user" : false}
                            }]
    }

**Comment by vikramrajkumar** [comment]
Can be done client-side with existing features like `public_data`. Won't bother with protocol level; refer to #1135 instead for the greater issue.
