### ISSUE TITLE
Support public accounts by using transaction builder in wallet::withdraw_delegate_pay

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1168]
Delegate pay withdrawal does a TITAN transaction even when targeted to a public account.  The `wallet::withdraw_delegate_pay` function currently creates a transaction directly.  We should instead create the transaction with a transaction builder, which contains logic to check whether the recipient is public or TITAN.

**Comment by vikramrajkumar** [comment]
Was fixed in #1319 and related.
