### ISSUE TITLE
0.6.x invalid passphrase on some JSON backup imports

### ISSUE THREAD

**Issue by andyjbas** [BitShares/bitshares#1177]
With an export made in v0.4.27.1, importing as well in v0.4.27.1 gives error http://cl.ly/image/2t322I091D2T.

**Comment by xeroc** [comment]
wrong pwd error when importing backups:
https://bitsharestalk.org/index.php?topic=14330.msg186684#msg186684
https://bitsharestalk.org/index.php?topic=14337.msg186685#msg186685

**Comment by vikramrajkumar** [comment]
Also see: #1406

**Comment by vikramrajkumar** [comment]
Refer to #1406 instead.
