### ISSUE TITLE
bts: URI scheme opens wallet but doesn't go to proper page.

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1183]
This is making it difficult to integrate BitShares into my blog.  Now that I am eating our dog food so to speak we need to get this working.

**Comment by vikramrajkumar** [comment]
@nathanhourt Has this been resolved?

**Comment by nathanhourt** [comment]
Nope, I've never been able to reproduce it, which makes me think it's probably an OSX bug. I guess I'd have to install Sparkle to reproduce it...

**Comment by vikramrajkumar** [comment]
@nathanhourt I think the sparkle thing is different and irrelevant (not a bug). I am referring to BM's original post and the title of this issue.

**Comment by nathanhourt** [comment]
Looks like either OSX or Qt on OSX changed the way the URL is passed to the program... Fixing now.

**Comment by nathanhourt** [comment]
https://github.com/BitShares/qt_wallet/commit/ec5906b766ce4a9646f4327c95e8cbd3c2d5e917

**Comment by nathanhourt** [comment]
I tried to make the fix backwards compatible, but it would be nice if someone tested it on OSX Mavericks.

**Comment by eightyhz** [comment]
Built the GUI with your fix.. it works. Huzzah!

**Comment by vikramrajkumar** [comment]
Also: https://github.com/BitShares/qt_wallet/commit/7abc25fa43301f7fb1a7bcda376faaa252a5e3ed
