### ISSUE TITLE
wallet scanning issue: deposit not showing up in poloniex's wallet

### ISSUE THREAD

**Issue by nmushegian** [BitShares/bitshares#1194]
https://bitsharestalk.org/index.php?topic=12684.new#new

**Comment by optictopic** [comment]
When this bug is fixed what will happen to transaction 893a6a32?  This is the id of the 33k BTSX I sent from the latest client wallet to Poloniex.  If someone needs to speak to a dev at Poloniex they should contact Tristan D'Agosta at contact@poloniex.com

**Comment by optictopic** [comment]
This is the latest from Poloniex:
"At this point, I am confident the funds are in our possession, despite the bug causing them not to show up in the right place. I think you've waited long enough, so I've gone ahead and inserted the deposit manually for you. Hopefully we can get the issue sorted with the developers."

They went ahead and deposited the BTXS into my Poloniex wallet manually.

Thanks You,
Rich

**Comment by vikramrajkumar** [comment]
For reference from helpdesk:
![screen shot 2014-12-25 at 8 42 21 am](https://cloud.githubusercontent.com/assets/793567/5621365/dc2c4bba-9502-11e4-8d09-42029a64d11b.png)
![screen shot 2014-12-25 at 12 38 32 am](https://cloud.githubusercontent.com/assets/793567/5621366/dc40d53a-9502-11e4-8e50-7a796a963d88.png)

**Comment by vikramrajkumar** [comment]
Also see: https://bitsharestalk.org/index.php?topic=12679.msg166821#msg166821

**Comment by optictopic** [comment]
Thank you Vikram,
Poloniex went ahead and manually credited the transfer to my Poloniex
wallet.  Are you a Bitshares delegate? If so what is your delegate name?

Rich

**Comment by vikramrajkumar** [comment]
@optictopic I did not have time to look at this issue of yours the past couple weeks but I am glad it is resolved. I will come back and look through this when I have time to make sure there is no serious underlying problem.

I have not setup my delegate yet but will soon under the name `developer.vikram`.

**Comment by vikramrajkumar** [comment]
I don't see anything out of the ordinary that could have caused a problem here. This looks like a standard TITAN transfer. I will keep an eye out for problems like this in the future.

Note that there is also the `wallet_verify_titan_deposit` command that the recipient can use in situations like this to try to verify the deposit.
