### ISSUE TITLE
wallet_remove_contact_account - not persistent across client restarts

### ISSUE THREAD

**Issue by nethyb** [BitShares/bitshares#1196]
Detailed at 

https://bitsharestalk.org/index.php?topic=12740.msg167693;topicseen#msg167693 

There are two issues it appears:  

1. When I've created a local contact account using a public key,  if the public key belongs to a registered account, it appears the client 'resolves' the key to the registered account name and I can no longer reference the local contact using the name I originally used as the contact name. (this may be true only for account registered before the BTSX to BTS transition)

2. I cannot remove the contact - it appears as though wallet_remove_contact_account does not save the removal to the users wallet - the removed contact re-appears on restart

**Comment by vikramrajkumar** [comment]
Superseded by: #1401
