### ISSUE TITLE
Various types of wall

### ISSUE THREAD

**Issue by RoyBts** [BitShares/bitshares#1200]
1.current wall ,everyone can write word on wall at least spend 1 BTS
2.everyone can write word on wall at least spend 1 BTS , but the information that burn more bts is showed more up
3.only owner can write word on the wall.  it is used for group or people publish declaration or promise.

PS: wall support link?

**Comment by vikramrajkumar** [comment]
There doesn't seem to be an issue here.

1. Currently anyone can burn funds for or against an account for at least 1 BTS
2. It is up to frontend developers to choose how they want to display the burn information
3. Accounts can publish any information they want in their account's "public data"
4. There is no documentation on burning yet
