### ISSUE TITLE
Change relative orders to percentage of price feed

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1207]
The current relative orders implementation specifies the desired price as a delta from the current price feed.

@bytemaster and I discussed this, and came to the conclusion that it should be a percentage of the current price feed instead.  From an economic theory standpoint, "money is geometric" and using percentages is the more "correct" way.  From a practical coding standpoint, it will allow us to support relative orders either above or below the feed.

**Comment by theoreticalbts** [comment]
Okay, starting to write an implementation of this has revealed some interesting (but ultimately solvable) problems.  We must use all-integer arithmetic, i.e. we must do the computation `price * relative_percentage`.  @bytemaster suggested keeping the existing `market_index_key` field type where the price is essentially a `uint128` with 64-bit fixed point semantics.  Then you essentially have `price * bid_op.bid_index.order_price >> 64`.  Of course the multiplication requires a full 256-bit product of two `uint128`'s, which I have already implemented in an fc patch (I plan to merge it shortly).

The problem with this approach is that I'm not sure it's desirable to allow such a high degree of quantization.  To me there is some sense of allowing only a precision of `10000`, i.e. if someone bids `99.25%` of the market price, the next highest possible bid "should" be `99.26%`, not `99.25000000000000000542101086242752217003726400434970855712890625%` which would be the next available "step" if we use the above approach.

Therefore, I propose simply quantizing by a factor of `10000` (hard-coded where we `#define` the chain parameteres) so relative orders have a "tick" of `0.01%`.  We then multiply by the numerator and divide by `10000`.  If the feed value is large and the multiplication would produce a result out of range, we can simply shift right 15 places (this provides ample room to multiply even the maximum `uint128` value by a number up to `32768`, which is sufficient because the numerator will be limited to `20000` or below), multiply, divide by `10000`, and shift left 15 places.  The left shift can still overflow, but we can prevent this by forbidding publishing a feed price of `2**63` or larger (thus a relative order will always represent a price that will "fit").

Note, `0.01%` of the price will always be a "reasonable" quantization step, regardless of the range of the feed or the value of BTS.

This also provides a small bonus:  If (for relative orders) we replace the `market_index_key` data type with, say, a `relative_market_index_key`, we can save 14 bytes of blockchain storage per relative order because a `uint16_t` suffices to store a quantized percentage from `5000` (50.00%) to `20000` (200.00%).  You'll never be mixing quantized percentages and regular prices anyway, so there is really no reason to use the same type for the index of both of them.

**Comment by theoreticalbts** [comment]
Full `128 * 128 -> 256` multiplication implementation:  https://github.com/BitShares/fc/commit/6ecb55ac2e8e212ff8849945b4c5dadcfede5a1a

Full `128 * 128 -> 256` multiplication test:  https://github.com/BitShares/bitshares/commit/a4a51e3d1260dc0a0aa2645dac2d15c00745ffea

**Comment by theoreticalbts** [comment]
@bytemaster : I suggest you work on getting the relative ask to do satoshi conversion (i.e. prices shown to / entered by the user are unit-to-unit exchange rates, internal blockchain uses satoshi-to-satoshi exchange rates, and we need to convert between the two since XTS and USD have different precision).  It is certainly needed for display, it may also be needed for actual semantics.  This is called "precision dance" in some existing code.

**Comment by theoreticalbts** [comment]
`submit_relative_ask` call was fixed by b8817c6587276fa888f7c88c14ac39304dfb5733

**Comment by bytemaster** [comment]
This change has been implemented and tests pass.
