### ISSUE TITLE
Usable Brainwallet Generation

### ISSUE THREAD

**Issue by indolering** [BitShares/bitshares#1208]
A few enhancements would make the brainwallet backup more usable:

* Spell check
* Order independent word entry
* Word list optimized for correction of verb forms, alternate spellings, etc.

Thankfully, @ryancdotorg has already worked out such a system and kindly posted [a demo](http://ryanc.org/mnemonic/demo.html) that is entirely client-side JS, it has everything including the wordlist.  

The UI should visually group words into triplets, the encoding is designed so that each group of three words is a "thing" (verb, adjective, noun) and 3 happens to be a cognitive sweet spot.

Paraphrasing @ryancdotorg,
>12 words -> 80 bits, 15 words -> 96 bits, 18 words -> 112 bits, 21 words -> 128 bits.  Aggressive key stretching can provide up to an additional 24 bits of effective security.  12 words (with key stretching) [should be](http://www.keylength.com/en/3/) the minimum.

Ryan also has a python implementation if that is of help to anyone.

Migrated from https://github.com/BitShares/qt_wallet/issues/86

**Comment by vikramrajkumar** [comment]
@nathanhourt @jcalfee Please review and close if you don't plan to support this in the foreseeable future.

**Comment by nathanhourt** [comment]
I have no plans to use this particular scheme.

**Comment by vikramrajkumar** [comment]
Looks like this is out of scope for now.
