### ISSUE TITLE
Market cancels fail when you don't control the account owner private key

### ISSUE THREAD

**Issue by nmushegian** [BitShares/bitshares#1213]
https://bitsharestalk.org/index.php?topic=12987.msg170790#msg170790

**Comment by vikramrajkumar** [comment]
Looks like the transaction builder (publicly) ties all market orders to account *owner* addresses.

**Comment by theoreticalbts** [comment]
This reminds me of 2aafc098204ccfcbe73a0761a07d7175c3e785a3 -- maybe we need to go through all the places owner keys / addresses are used, and for each place, think about whether we want it to be an owner or active key / address.

**Comment by vikramrajkumar** [comment]
^ Yes, this has been a long ongoing process. It took many months before I felt comfortable generating new accounts with different owner and active keys, now still need to hammer out the remaining problems like this as they crop up.

**Comment by vikramrajkumar** [comment]
Actually, this was a much smaller problem than I thought--just an extraneous assert.
