### ISSUE TITLE
[Request] blockchain_get_account to also show balances in public address

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1214]
Hey there,

as every account name has a public key (and thus a public BTS address) and
"active keys" that are know to the blockchain I recommend to extend the client
to also show all funds stored in those addresses (active keys).

Use-case would be i.e. my *charity* delegates.

Example:

    >>> blockchain_get_account xeroc
    Name: xeroc
    Registered: Genesis (Keyhotee Founder)
    Last Updated: 67 days ago
    Owner Key: BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa
    Active Key History:
    - BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa, last used 25 weeks ago

    ID    NAME (* next in line)           APPROVAL       PRODUCED MISSED   RELIABILITY   PAY RATE PAY BALANCE         LAST BLOCK  VERSION     
    ==========================================================================================================================================
    284   xeroc                           0.02316093 %   0        0        N/A           3 %      0.00000 BTS         NONE                    

    ID    Asset                           Balance               all active keys
    ==========================================================================================================================================
    0     BTS                             10.0                  BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa
    22    USD                             100.0                 BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa

    Block Signing Key: BTS5WaszCsqVN9hDkXZPMyiUib3dyrEA4yd5kSMgu28Wz47B3wUqa
    Public Data:
    {
      "slate_id": 6136676347887220980,
      "mail_server_endpoint": "127.0.0.1:19999",
      "mail_servers": [
	"xeroc"
      ]
    }

Also it would be cool to have the ability to send transactions with
***unencrypted*** memo messages.

edit: discussion: https://bitsharestalk.org/index.php?topic=13044.msg171178#msg171178

**Comment by vikramrajkumar** [comment]
`blockchain_get_account_public_balance` can be used for this purpose (and will be fixed in next version, see #1420). It is an expensive call so must be kept separate.

Unencrypted memos could be nice but unlikely to happen anytime soon.
