### ISSUE TITLE
Add support for displaying published slates

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1216]
We need a way to see the published slate of a given published account. Without this, voting for a published account with "vote_recommended" is a bit of a blind voting system.

**Comment by vikramrajkumar** [comment]
@dnotestein is the above added call sufficient?

**Comment by dnotestein** [comment]
I think this API is needed, but I think we need one that "connects the dots" as well. I think we should have an option to do:
blockchain_get_slate account_name

This would look up the current slate id for that account name, then print the results of blockchain_get_slate for that slate id.

I'm hoping the two types are significantly different (account_name vs slate_id), so that we could share the API call, but an additional api like blockchain_get_slate_of_account would also work.

**Comment by vikramrajkumar** [comment]
Sounds good, will overload the same call.
