### ISSUE TITLE
blockchain_market_order_book incorrectly shows short quantity as 0 XTS

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1218]
The `wallet_market_interleave_test` regression test reproduces this behavior.

**Comment by bytemaster** [comment]
I believe this has been fixed.  Please verify.

**Comment by theoreticalbts** [comment]
It hasn't been fixed; the test reproduces it (after some updates to the test to fix misc. breakage due to unrelated changes)
