### ISSUE TITLE
genesis_dvs.json has lot of empty balances

### ISSUE THREAD

**Issue by testzcrypto** [BitShares/bitshares#1221]
genesis_dvs.json has lot of empty balances, like:
      "raw_address": "BTSMLZMWGkoGfEUwrsJp3yTDo7uzGukdqLch",
      "balance": 0
    },{
      "raw_address": "BTS4ZD2itCYuJak8RnEu2ibwFP1qhmkERoEG",
      "balance": 0
    },{

**Comment by testzcrypto** [comment]
Same for genesis_bts.json but not as many as in genesis_dvs.json

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/1abfdfe76f0bf0a1970bef14ea5540582374942d
