### ISSUE TITLE
 implementation for blockchain_list_address_transactions

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1222]
Look like _chain_db->fetch_address_transactions is the source of this information but it is returning empty results.  It is setup to use chain/index/address_to_trx_db/, those files are small and don't increase in size when a transaction is sent.  There is a track_stats boolean but that is on.  

Basically what I see is that pending_chain_state::index_transaction is setup to lock and call chain_database::index_transaction.  But who is calling pending_chain_state::index_transaction?  Maybe pending_chain_state::store_transaction is a good place.  Now, back in the chain_database::index_transaction, I would mind if this were conditional based on a config.json setting, there is a comment in the code that explains this:  "This index is to facilitate light weight clients and is intended mostly for block explorers and other APIs serving data."

Note: dump_state is dumping at least one other *_index file but does not dump _address_to_trx_db (doubt we need that though); not sure what get_stats is about but the same thing there.

**Comment by emfrias** [comment]
For the get_stats() function: it's purely there for us to use when analyzing blockchain code performance -- we have some test code that will call that periodically as it replays the blockchain and generates a graph of the size of each index over time.  That lets us see if any indexes are "exploding", or see at a glance whether the block or transaction processing speed correlates with the size of any indexes.  Ideally, it should be in there because maintaining that database may slow block processing down, but I wouldn't worry about it.  There are probably other new indexes that aren't printed in get_stats(), we'll just have to update it before the next time we profile the code.

**Comment by emfrias** [comment]
So what's the purpose of this address_to_trx_db thing anyway?

**Comment by jcalfee** [comment]
It should be just like `wallet_account_transaction_history` .. but since some implementations will be using non-titan (using the owner's active key), then `blockchain_list_address_transactions` can be used to accomplish the same goal.

**Comment by jcalfee** [comment]
This is some glue code I was debugging (you probably know this already):
```
map<transaction_id_type, transaction_record> detail::client_impl::blockchain_list_address_transactions( const string& raw_addr, const time_point& after )const
{
    address addr;
    try {
        addr = address( raw_addr );
    } catch (...) {
        addr = address( pts_address( raw_addr ) );
    }
    vector<transaction_record> transaction_records = _chain_db->fetch_address_transactions( addr );
    std::cout<<"...transaction_records\t"+fc::json::to_pretty_string(transaction_records)<<"\n";
    map<transaction_id_type, transaction_record> transactions_map;
    for( const auto& transaction_record : transaction_records )
    {
        std::cout<<"...transaction_record\t"+fc::json::to_pretty_string(transaction_record)<<"\n";
        /*if( fc::time_point(transaction_record.created_time) < after )
            transactions_map[ transaction_record.trx.id() ] = transaction_record;*/
    }

    return transactions_map;
}
```

**Comment by emfrias** [comment]
ok... fetch_address_transactions seems to expect that address_to_trx_index will contain transactions that get_transaction() can't return, so there's no strict need to remove information from that index when we roll back the blockchain.  It looks like chain_database::store_transaction() is never called so pending_chain_state::store_transaction() looks like as good a place as any to call index_transaction()

**Comment by jcalfee** [comment]
Would you please update pending_chain_state.cpp then I'll complete the api call...

**Comment by vikramrajkumar** [comment]
This index should probably be updated in the store/remove methods of the transaction record chain db interface.

What counts as a transaction's address? Do you care about only deposits, only withdraws, anything that has a withdraw condition with a single owner, multiple owners, etc. ?

**Comment by jcalfee** [comment]
I think Nathan took care of this here: 
https://github.com/BitShares/bitshares/issues/1226

**Comment by nathanhourt** [comment]
Oh, hi there. Yes, I did. :) Note that currently, only the owners for deposits and withdrawals are catalogued though. If you need other ops, they can be added in chain_database::store_transaction().

**Comment by jcalfee** [comment]
This API appears to be fully implemented now, however, I was not able to fetch any transactions:
```
wallet_account_create test
wallet_account_list_public_keys test
# transfer to the native_address
wallet_transfer_to_address 1 XTS delegate0 XTSB91fYK2ToN6WYhMnEBMtFBbwRF1k9EpQT
# verify the balance
blockchain_list_address_balances XTSB91fYK2ToN6WYhMnEBMtFBbwRF1k9EpQT
# .. great, has 1 balance record that matches 
blockchain_list_address_transactions XTSB91fYK2ToN6WYhMnEBMtFBbwRF1k9EpQT
[]
```
The transaction is not returned from `blockchain_list_address_transactions`.  There are a couple of log messages from the API that confirm this: 
```
2015-01-21T14:25:08    th_a:client::start blockchain_list_addr ] Found 0 transactions for XTSB91fYK2ToN6WYhMnEBMtFBbwRF1k9EpQT			blockchain_api.cpp:354
2015-01-21T14:25:08    th_a:client::start blockchain_list_addr ] Found 0 transactions after block 0			blockchain_api.cpp:361
```
I noticed the index _address_to_trx_index is still being used but its size on disk did not change.

**Comment by jcalfee** [comment]
It is working, just tricky to get it going: Nahan's explanation: "Yes, but the list_address_* functions only work if statistics were enabled before the chain database was created."
