### ISSUE TITLE
Add support for multiple accounts

### ISSUE THREAD

**Issue by nathanhourt** [BitShares/bitshares#1223]
The Light Wallet currently assumes only one account is used. It should be altered to support multiple accounts.

**Comment by vikramrajkumar** [comment]
@nathanhourt Just a suggestion but the overwhelming cause of complexity and problems in the full wallet is the fact that it tries to support multiple accounts. I recommend considering sticking with the 1 wallet = 1 account model.

If multiple accounts are absolutely necessary, maybe consider allowing only 1 account to be in context/scope at a time, and the user must fully switch contexts everytime they want to work with a different account.

**Comment by nathanhourt** [comment]
@vikramrajkumar It'll definitely be a modal switching mechanism where only one account can be active at a time. And I'm back-burnering this until I have a working beta. I think multi-account support in the light wallet is a waste of effort, and I'd rather not have it at all, but Dan wants it.

**Comment by vikramrajkumar** [comment]
Sounds like this is out of scope for now.
