### ISSUE TITLE
network_get_peer_info fails with "local_endpoint: Bad file descriptor: error getting socket's local endpoint"

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1224]
>>> info
    {
      "blockchain_head_block_num": 209312,
      "blockchain_head_block_age": "21 weeks old",
      "blockchain_head_block_timestamp": "2014-08-13T03:19:20",
      "blockchain_average_delegate_participation": "0.01 %",
      "blockchain_confirmation_requirement": 1,
      "blockchain_share_supply": "2,498,963,067.47391 BTS",
      "blockchain_blocks_left_in_round": 61,
      "blockchain_next_round_time": "at least 10 minutes in the future",
      "blockchain_next_round_timestamp": "2015-01-09T20:31:40",
      "blockchain_random_seed": "c5ef966b154ac8eb2e006b2ae876ad0c39f29db6",
      "client_data_dir": "/home/cc/bts/.BitShares",
      "client_version": "v0.4.27.2",
      "network_num_connections": 15,
      "network_num_connections_max": 200,
      "network_chain_downloader_running": false,
      "network_chain_downloader_blocks_remaining": null,
      "ntp_time": "2015-01-09T20:21:37",
      "ntp_time_error": 5.8e-05,
      "wallet_open": false,
      "wallet_unlocked": null,
      "wallet_unlocked_until": null,
      "wallet_unlocked_until_timestamp": null,
      "wallet_last_scanned_block_timestamp": null,
      "wallet_scan_progress": null,
      "wallet_block_production_enabled": null,
      "wallet_next_block_production_time": null,
      "wallet_next_block_production_timestamp": null
    }
    >>> network_get_peer_info
    13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: local_endpoint: Bad file descriptor
    local_endpoint: Bad file descriptor: error getting socket's local endpoint
        {"what":"local_endpoint: Bad file descriptor"}
        p2p  tcp_socket.cpp:132 local_endpoint

        {}
        th_a  common_api_client.cpp:565 network_get_peer_info

        {"command":"network_get_peer_info"}
        th_a  cli.cpp:579 execute_command

This appears to be system-specific.  I'm trying to run on a VPS (I believe OpenVZ?) where I have no control over the kernel version.  The listed version is:

    $ cat /proc/version
    Linux version 2.6.32-042stab094.7 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Oct 22 12:43:21 MSK 2014

Note, my user space is Ubuntu 14.04, I'm just using an older kernel.

**Comment by vikramrajkumar** [comment]
Too old; closing.
