### ISSUE TITLE
Linux: DevShares build 0.5.0 crashes

### ISSUE THREAD

**Issue by davidpbrown** [BitShares/bitshares#1228]
DevShares seems not to have /issues/new option on github so posting here.

Having build DevShares previously when it was in BitShares branch
Now, 0.5.0 build crashes at 100% on Linux Mint 17 and Ubuntu 14.10 i386

Error reads:
<pre lang="javascript"><code>Scanning dependencies of target multest
[100%] Building CXX object tests/drltc_tests/fc_math/CMakeFiles/multest.dir/multest.cpp.o
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp: In function ‘int main(int, char**, char**)’:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:136:27: error: conversion from ‘__time_t {aka long int}’ to ‘fc::uint128’ is ambiguous
                 ns_before = t_before.tv_sec;
                           ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:136:27: note: candidates are:
In file included from /home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:18:9: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator=(fc::uint128&&)’
   class uint128 
         ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:138:27: error: conversion from ‘__syscall_slong_t {aka long int}’ to ‘const fc::uint128’ is ambiguous
                 ns_before += t_before.tv_nsec;
                           ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:138:27: note: candidates are:
In file included from /home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:54:16: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator+=(const fc::uint128&)’
       uint128& operator += ( const uint128& u ) { const uint64_t old = lo; lo += u.lo;  hi += u.hi + (lo < old); return *this; }
                ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:140:26: error: conversion from ‘__time_t {aka long int}’ to ‘fc::uint128’ is ambiguous
                 ns_after = t_after.tv_sec;
                          ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:140:26: note: candidates are:
In file included from /home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:18:9: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator=(fc::uint128&&)’
   class uint128 
         ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:142:26: error: conversion from ‘__syscall_slong_t {aka long int}’ to ‘const fc::uint128’ is ambiguous
                 ns_after += t_after.tv_nsec;
                          ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:142:26: note: candidates are:
In file included from /home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:54:16: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator+=(const fc::uint128&)’
       uint128& operator += ( const uint128& u ) { const uint64_t old = lo; lo += u.lo;  hi += u.hi + (lo < old); return *this; }
                ^
make[2]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/multest.cpp.o] Error 1
make[1]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/all] Error 2
make: *** [all] Error 2
</code></pre>

**Comment by davidpbrown** [comment]
hmm.. I'm not used to github markup and can't attach a text file!

Error ends:
/home/davidpbrown/x/bitcoins/DevShares/0.5.0/DevShares/libraries/fc/include/fc/uint128.hpp:54:16: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator+=(const fc::uint128&)’
       uint128& operator += ( const uint128& u ) { const uint64_t old = lo; lo += u.lo;  hi += u.hi + (lo < old); return *this; }
                ^
make[2]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/multest.cpp.o] Error 1
make[1]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/all] Error 2
make: *** [all] Error 2

**Comment by theoreticalbts** [comment]
First of all `multest.cpp` is a benchmark / test.  It is not required for normal usage, and should not be built unless you specifically ask for it.  What `make` target are you using?

To copy stuff verbatim to Github markdown, indent it four spaces.

As for the actual compiler error, it should be fixed by 2602504998dcd63788e106260895769697f62b07 (n.b. this commit is on our bleeding-edge branch and needs ported to devshares).
