### ISSUE TITLE
[request] let the client parse 'raw transactions' and return json

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1232]
Can we have something like bitcoin's 

   decoderawtransaction

and let the client json decode a raw transaction .. that would make developing costum transaction building software alot easier to debug ..

**Comment by nmushegian** [comment]
For now you can use `wallet_builder_file_add_signature` to have the client read a raw json and try to process the transaction, but it will need to be in transaction builder format

**Comment by vikramrajkumar** [comment]
@xeroc What do you mean by raw transaction? The serialized transaction as sent on the p2p network? Or a JSON string of the transaction?

**Comment by theoreticalbts** [comment]
I'm thinking this is asking for standalone serialization / deserialization functions with JSON input / output, and possibly whatever validation can be done with the contents of the transaction alone.

@bytemaster said that it should be possible to autogenerate serialization / deserialization code in languages other than C++ using FC's reflection functionality.  But seeing as that functionality is a totally undocumented mess of magic macros, I think that @bytemaster is likely the *only* person capable of doing that right now.

**Comment by jcalfee** [comment]
Custom transaction building software is probably going to need to sign a hash eventually .. If I understand you, you're going to need the binary parsing anyways so you can see what your signing.  I do this in bitshares-js for simple transfers and account registration but it is all just a matter of templating in more transaction types (well after I get variants supported).

**Comment by xeroc** [comment]
I'd like to implement a simple withdraw type transaction in python so that I can use blockchain_broadcast_transaction to send it to the network .. 

From what I understand, blockchain_broadcast_tx takes a serialized transaction so the python script would require to serialize a (json) transaction.

I'd like to have the private key separated from the client and basic be able to construct a valid transaction just by having the balance_id the private_key and the amount+asset_id

**Comment by jcalfee** [comment]
O joy... You can use toJson and toBinary... you use toBinary to get data that you hash and sign.  Then take the signature HEX and add it to the JSON transaction.  Send the JSON to blockchain_broadcast_transaction.  I do not see a blockchain_broadcast_tx command in my build, maybe that is new.  That might save you a step of having to go to JSON, however, you will have to serialize more of the transaction if you do that.  You do not hash the outer transaction that contains the signature and several other fields (that would be impossible).

You'll probably want to start with a library that will give you variable length integer encoding and large numbers (64 bits).  

You end goal is something like this but you can simplify a lot of it by creating a non titan transfer and not having to derive any keys: https://github.com/BitShares/BitShares-JS/blob/639a1c7eb151948d43277316396cf27d31f4a259/scratchpad/trx_titan.coffee#L148-L204  (use js2coffee.org if you need to see it in javascript).

So far, this supports everything I need except public_data (like embedded json).  It uses bytebuffer.js to do the math on the variable length numbers: https://github.com/BitShares/BitShares-JS/blob/639a1c7eb151948d43277316396cf27d31f4a259/src/common/fast_parser.coffee

This is there fast_parser fb is appending the transaction to the buffer: https://github.com/BitShares/BitShares-JS/blob/639a1c7eb151948d43277316396cf27d31f4a259/src/blockchain/withdraw_signature_type.coffee#L37-L42

Then you can write out the entire transaction to the buffer: https://github.com/BitShares/BitShares-JS/blob/639a1c7eb151948d43277316396cf27d31f4a259/scratchpad/trx_titan.coffee#L192

You have to hash the tx hash with the chain ID (so transactions can't cross chains!):  https://github.com/BitShares/BitShares-JS/blob/639a1c7eb151948d43277316396cf27d31f4a259/scratchpad/trx_titan.coffee#L193

This is one way to get (or check) chain ID (and you will want to do this to make sure "missing signature" does not mean you hashed wrong): https://github.com/BitShares/BitShares-JS/blob/master/src/config.coffee#L5-L13

The best way to do all of this is very small steps.  Serialize one thing in your code then print the data in hex then compare to the working code (bitshares or bitshares-js) and check it.  In bitshares, you can use fc::json::to_pretty_string on almost any object.  OR, in bitshares-js you can use console.log or in the bytebuffer library b.printDebug() to get a nice looking hex dump.  Both libs have advantages one being completeness (the first) and the latter being faster to change and re-execute.

I'll be happy to review your code...

**Comment by jcalfee** [comment]
related: https://github.com/BitShares/bitshares/issues/1231

**Comment by jcalfee** [comment]
I'm available by phone, I'll see you on skype....

**Comment by xeroc** [comment]
Thanks for the comprehensive summary .. I am already working through your code and figured out most (but not all) parts of it .. 

I may start working with your JS library first and make a simple page that does the serialization and deserialization so that I can verify my python implementations once finished (probably not so soon).

Anyway, maybe someone can come up with a brainwallet.org kind of site using your JS library :)

Thanks for the assistance so far anyway .. If things are getting to complicated for me I will certainly skype or pm you .. thanks for the offer

**Comment by jcalfee** [comment]
"@bytemaster said that it should be possible to autogenerate serialization / deserialization code in languages other than C++ using FC's reflection functionality."

If there turns out to be a need for this, maybe just write a routine that exports the FC_REFLECT structure recursively as JSON?  Then other languages could just use that data.

**Comment by xeroc** [comment]
> If there turns out to be a need for this, maybe just write a routine that exports the FC_REFLECT structure recursively as JSON? Then other languages could just use that data.

unfortunatelly I am NOT a developer .. so I have no clue how to do that ..
Think I am going to write a simplified costum code (that's what I need anyway) .. but yeha .. as I am not really a coder it might take some time .. need to focus on my disseration atm too ..

gonna keep you posted and thx for the chat
