### ISSUE TITLE
Different logic when qualifying a withdraw condition as spenable

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1239]
Here, it looks like anything that is not a "withdraw_signature_type" is not included in a spendable balance: https://github.com/BitShares/bitshares/blob/79e2a90e9fc064178a52dc41f7f1881eb7c70d4f/libraries/wallet/wallet.cpp#L4061

But in this code there are additional conditions that qualify as spendable: https://github.com/BitShares/bitshares/blob/853853e035b88cd199fe24b63bda39b55b162f50/libraries/blockchain/balance_record.cpp#L53

**Comment by jcalfee** [comment]
It looks like the balance_record is more recent and will be used in all cases eventually.  Please confirm.

**Comment by vikramrajkumar** [comment]
That function in the wallet is just a helper function for the common case of people spending "normal" (withdraw_signature) balances. Other types of balances will be claimed/displayed using other commands. In fact once the scanning is rewritten, I even want genesis balances to be explicitly claimed using a separate command.

You can see here how I now initially cache all relevant balances: https://github.com/BitShares/bitshares/blob/55f6b4086334d6c1f6ef371715598b212324a756/libraries/wallet/transaction_ledger_experimental.cpp#L9-L33

**Comment by jcalfee** [comment]
In the other cases, once claimed / signed / etc then we will end up with a new simple-case withdraw_signature?  So, I'll be sure to only show a withdraw_signature balance for wallet spending purposes.

**Comment by vikramrajkumar** [comment]
Yes, when I say "claimed", I mean the necessary conditions are met to transfer a balance to a "normal" withdraw_signature balance.
