### ISSUE TITLE
wallet_account_list_public_keys key formats

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1242]
I'm wondering if these keys might be in the wrong format.  Maybe they are correct, I just don't know where the are used like this.  I have a use case below...
```
default (unlocked) >>> wallet_account_list_public_keys acct
[{
...
    "pts_normal_address": "PXzB8g9LPd3oZT317GteWLDakSUJj1HoYV",
    "pts_compressed_address": "PZxV21L9d9Un2xadeVqbaK2kpconvC1JLT",
    "btc_normal_address": "114PzbTCdX6jmBE9jnEoMJyXWC3Uv7nf4e",
    "btc_compressed_address": "132hsve1s3XiEgmnH1BkRHnhaNNy7t5s5E"
  },{
```
Here is one place where these 4 keys are being created from a public key and then getting cached in the wallet for lookup.  The values that are cached are all prefixed by the currency symbol (ex: XTS):

https://github.com/BitShares/bitshares/blob/2602504998dcd63788e106260895769697f62b07/libraries/wallet/wallet_db.cpp#L103-L108

This is what the keys look like below as they are being added to the address cache map in the code above.  The last key format Compressed_PTS is the format I am using to pass to blockchain_list_address_balances to get the genesis balance record for an account.
```
Uncompressed_BTC:	"XTSLAFmEtM8as1mbmjVcj5dphLdPguXquimn"
Compressed_BTC:	"XTSANNTSEaUviJgWLzJBersPmyFZBY4jJETY"
Uncompressed_PTS:	"XTSEgj7RM6FBwSoccGaESJLC3Mi18785bM3T"
Compressed_PTS:	"XTSD5rYtofD6D4UHJH6mo953P5wpBfMhdMEi"
```

**Comment by vikramrajkumar** [comment]
In the referenced lines you can see that the public key is first converted to `pts_address` before being converted to `address`. The first list seems to be the string versions of the former type, while the second list seems to be the string versions of the latter type.

**Comment by jcalfee** [comment]
That is what is looks like .. I'm just wondering if we had a use case for the raw pts_address format.  It does not seem to work for me in the `wallet_account_list_public_keys` rpc call, I had to use the later.

**Comment by vikramrajkumar** [comment]
The only current use case is to claim genesis balances originating from the PTS/BTC blockchains.

**Comment by jcalfee** [comment]
ok, thank you .. let see if anyone else needs the latter format.  I'm not ready to clutter up the results with more keys unless we really need it.
