### ISSUE TITLE
acceptance feature fails: Transfer funds from one account to another

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1243]
http transaction callback doesn't match:

features/step_definitions/basic_wallet_steps.rb:123
      
      expected: {"from_account"=>"XTS6voTTcv5y9PyLdQLYt76iCigoS8zSbsMTAUtdRtCDLrvbv7L2C", "to_account"=>"XTS5pT2ZvwSTfxybbamzuTsWRHLWs6NQtoFti6zEEJbTLGd2nFFPK", "amount"=>{"amount"=>5000000, "asset_id"=>0}, "memo"=>"", "memo_from_account"=>"XTS6voTTcv5y9PyLdQLYt76iCigoS8zSbsMTAUtdRtCDLrvbv7L2C"}
           got: {"from_account"=>"XTS6voTTcv5y9PyLdQLYt76iCigoS8zSbsMTAUtdRtCDLrvbv7L2C", "to_account"=>"XTS6bLmTQSvjgPjefdCUYm7LmPpNxH1GAgA5u44vvKVDYFUGnpgZZ", "amount"=>{"amount"=>5000000, "asset_id"=>0}, "memo"=>"", "memo_from_account"=>nil}

Probably ledger_entries structure format has been changed, so the callback doesn't match it now.

**Comment by vikramrajkumar** [comment]
When was the most recent time this was passing?

Ledger entry format should not have change. @nathanhourt any ideas on this? Could it possibly be related to #1241?

**Comment by nathanhourt** [comment]
Yeah, it could be. I'm not exactly sure what is going on here, though... Is a transfer going to the wrong account or something? What is the test doing exactly?

**Comment by valzav** [comment]
I didn’t run those for a long time, probably a month or so.

On January 13, 2015 at 4:05:39 PM, Vikram Rajkumar (notifications@github.com) wrote:

When was the most recent time this was passing?

Ledger entry format should not have change. @nathanhourt any ideas on this? Could it possibly be related to #1241?

**Comment by valzav** [comment]
The test transfers 100 XTS and runs web server - http transaction callback should match last ledger entry.

**Comment by nathanhourt** [comment]
Any idea what C++ triggers this callback? If I can find that, I can trace it back and see if what I did affects it.

Alternatively, you could try reverting fd61a0885338606c6ab8a7774739e7f28fc77745 and see if the test passes.

**Comment by valzav** [comment]
look at where wallet_callback_url config entry is used

**Comment by vikramrajkumar** [comment]
Too old and I don't know why you would have a memo_from_account with an empty memo. The transfer_from feature has been disabled with recent API changes anyway.
