### ISSUE TITLE
the last scenario from market.feature fails (Scenario: Alice shorts BitUSD, Bob shorts BitBTC, then they can trade USD vs BTC)

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1244]
And I submit ask for 3 BTC at 4.0 USD/BTC
  And I wait for one block
  And Bob submits bid for 5 BTC at 4.0 USD/BTC
  And I wait for 2 blocks
  Then I should have around 47 BTC and 12 USD                                    # features/step_definitions/basic_wallet_steps.rb:96      
      expected: 12
           got: 0.0

What happens above - Alice places order to sell 3 BTC for 12 USD, after Bob places bid, trade happens and after 2 blocks Alice's balance should be 12 USD, but for some reason wallet_account_balance returns 0 USD balance. I tried to increase wait time to 5 blocks - the same result.

**Comment by vikramrajkumar** [comment]
@valzav Can you try with the latest and confirm whether the problem is still there?

**Comment by valzav** [comment]
fixed now!
