### ISSUE TITLE
wallet_collect_genesis_balances issues a transaction even when you have no genesis balances

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1246]
I tried out `wallet_collect_genesis_balances` on DVS, but it did nothing and cost me a fee.  The account has genesis keys, but I'd already transferred all genesis funds from the account.  Immediately beforehand, I did issue a `wallet_collect_vested_balances` which gave me some DVS, however.

The no-op transaction generated by `wallet_collect_genesis_balances` is in block 63216, txid 61824a7b

**Comment by vikramrajkumar** [comment]
Already fixed in `develop` via: https://github.com/BitShares/bitshares/commit/8c87046384cdba3acde818b75a0eca885e41e852
