### ISSUE TITLE
Blocking blockchain rescan command

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1250]
I want to create a test that involves transferring between multiple wallets.  In particular, I'm working on a test that will need to:

- Create a wallet that contains an account
- Close the wallet
- Open a different wallet
- Transfer from the second wallet to the first wallet
- Close the second wallet
- Re-open the first wallet
- Rescan transactions issued since the first wallet was closed
- Examine the first wallet's transaction history / create transactions that use funds transferred from the second wallet

If the rescan command returns immediately, then the last step becomes non-deterministic.  It will depend on who wins a race between the rescan command's completion and the execution of the transaction history command.

The solution is to allow the rescan command to block the client, not allowing subsequent commands to execute until the rescan is complete.  I'm thinking of just adding a parameter in the `rescan` command.

**Comment by dnotestein** [comment]
sounds like a good solution to me. I can imagine plenty of scenarios where a remote controller of the client will want to know that rescan is completed, at the very least. An option to make it blocking lowers the burden on such controllers.

**Comment by theoreticalbts** [comment]
Yeah, although remote scripts become more recoverable from network failures if you poll `info` because that's properly RESTful and doesn't matter if your RPC connection dropped between starting and finishing the rescan.

The problem is when using a very dumb client language like the regression test framework, with no way to do conditional branching, polling isn't a viable approach.

**Comment by dnotestein** [comment]
It was always my intent to throw in a python interpreter as an optional replacement to the base cli entry method and use that for testing, but I doubt that's happening soon at this point.

**Comment by vikramrajkumar** [comment]
@theoreticalbts @grzegorzs You may find this useful.
