### ISSUE TITLE
Should this be called get_extended_balance?

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1252]
https://github.com/BitShares/bitshares/blob/14442468698c7c10cecc4761ecff2b0ef7fea579/libraries/blockchain/balance_record.cpp#L66-L109

**Comment by jcalfee** [comment]
I believe most of these types are not spendable until they are converted into a simple withdraw_signature_type.  Extended is a word used in the API and seems to work, these other types are a balance that one may have access to.

**Comment by vikramrajkumar** [comment]
No, this function returns the amount that could be withdrawn at the specified time if the withdrawal conditions are met; they are all spendable.

The other function in the wallet that is probably confusing you should probably instead be called somelike like get_signature_balances.
