### ISSUE TITLE
"Reindex-without-downtime" script

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1253]
This will primarily be to help delegates, market makers, etc. who want to be able to reindex with minimal downtime.  The script will:

- Copy blockchain into new datadir
- Delete database lock file from blockchain in new datadir
- Run client in new datadir until reindex is complete
- Copy index from new datadir to old datadir

Then on startup, the client will check if `index-v0.5.0` exists and seems to be a valid index for the current version.  If so, then it will delete the old index and rename the new index in its place.

**Comment by vikramrajkumar** [comment]
This seems like something community members can take care of. There are many different delegate topologies, and this will not be useful for some of them.

**Comment by theoreticalbts** [comment]
Well, I'm running a delegate, I obviously need to upgrade to 0.5.0 before the hardfork, and I want to do it without missing a block.  So this is scratching my own itch, really.

**Comment by vikramrajkumar** [comment]
Yeah, of course no problem--just that this isn't priority or 0.6 in the context of BTS.

**Comment by nmushegian** [comment]
What's wrong with just using two clients with a swap data directory?

**Comment by svk31** [comment]
I do this manually every time I upgrade, although the second step isn't needed:

> cp -r ./BitShares .BitShares2
> ./bitshares_client --data-dir $HOME/.BitShares2

Wait until it finishes, then close it (to reduce memory usage), then close the old client, then restart new client using the new data-dir. When a new version comes around, I move everything back to .BitShares

**Comment by vikramrajkumar** [comment]
@svk31 I'm not sure if it is what you are describing, but it is probably a bad idea to copy the data directory while a client is using it, as you may catch the databases in an inconsistent state.

**Comment by dnotestein** [comment]
I think it's a good idea for us to provide a script to the delegate community. Originally we were going to write one, but we got tied up with other stuff. If theoretical has one to commit, please do it. 

I think it's a good contribution to the community, because while not complex, mistakes like the one above are  easy to make. Solving the problem for 90% of our delegates is a win, even if not everyone can use it with some complex topology (presumably anyone with a complex topology can write their own). It will certainly make hard fork updates go smoother...

**Comment by janx** [comment]
+1. It would also help service providers like exchanges, any wallet downtime means a deposit/withdraw pause, which in turn affects normal users.

**Comment by vikramrajkumar** [comment]
Not bothering to track helper scripts like this (another: #1378) which are not directly related to development.
