### ISSUE TITLE
0.5.0 can't show transaction details on Win7-64

### ISSUE THREAD

**Issue by btswildpig** [BitShares/bitshares#1254]
click on a time of transaction in the "recent transactions" , I can see transaction number , but no other data .

Many people have this issue .

![image](https://cloud.githubusercontent.com/assets/9744912/5761467/9b455652-9d16-11e4-94f1-2557e4dcee86.png)

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/522
