### ISSUE TITLE
There is no option to use my own fund to reg an account at 0.5.0

### ISSUE THREAD

**Issue by btswildpig** [BitShares/bitshares#1255]
![image](https://cloud.githubusercontent.com/assets/9744912/5761586/54ddd9f4-9d17-11e4-99c2-05b16fdafa49.png)

**Comment by theoreticalbts** [comment]
Possibly related:  https://github.com/BitShares/web_wallet/issues/513

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/523
