### ISSUE TITLE
Add ability to have an extra 32 bytes in memo for a total of 51 bytes. 

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1258]
This will make it easier to implement gateways and will not significantly compromise privacy or add to network bloat.

**Comment by theoreticalbts** [comment]
Related discussion:  https://bitsharestalk.org/index.php?topic=13328

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/3eac06ebc5208b3fc77dd3004f0bddf44e0a3ae3
