### ISSUE TITLE
blockchain_get_transaction cannot find transaction

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1259]
wallet_account_transaction_history returns a list of transactions with trx_id each, some of them couldn't be found by blockchain_get_transaction. This happens with acceptance tests on develop branch, in order to replicate you can run market.feature, pause it after the first scenario (via @pause tag), go to console and try to get the last transaction by its id.

**Comment by vikramrajkumar** [comment]
@valzav I cannot reproduce. Am I looking at the correct scenario?

![screen shot 2015-01-15 at 4 57 28 pm](https://cloud.githubusercontent.com/assets/793567/5767598/cb0e1e44-9cd7-11e4-8f12-95cee88765f1.png)
![screen shot 2015-01-15 at 4 58 06 pm](https://cloud.githubusercontent.com/assets/793567/5767602/cd21c744-9cd7-11e4-8fa6-fd7f586d94aa.png)

**Comment by vikramrajkumar** [comment]
Just some confusion over "virtual" market transactions.
