### ISSUE TITLE
prevent orders or transfers for "BIT..." user-issued assets.

### ISSUE THREAD

**Issue by nmushegian** [BitShares/bitshares#1260]
These are obviously a scam attempt. Fuzzy might have gotten ripped off by this

**Comment by vikramrajkumar** [comment]
Is this a hardfork or client-side?

**Comment by nmushegian** [comment]
I would say hardfork

**Comment by vikramrajkumar** [comment]
If we are going to effectively destroy them, why not just rename them?

**Comment by nmushegian** [comment]
That works too

**Comment by nmushegian** [comment]
"FRAUDUSD" lol

**Comment by nmushegian** [comment]
Let's review them carefully, for example "BITVPN" seems like a legit project, so we should change it to "VPN" or ask them what they want

**Comment by vikramrajkumar** [comment]
How many of these are there? Shouldn't we just leave BITVPN as-is and only rename ones that look like legit market-pegged assets? How does the community decide what is legit? Seems like a can of worms

**Comment by nmushegian** [comment]
Anything that is named after an existing MPA should be deleted. Anything that isn't should have the option to rename.

**Comment by nmushegian** [comment]
No bit* assets should remain

**Comment by dnotestein** [comment]
We're not allowing BIT for any future user-issued assets, so I agree with Nikolai.

**Comment by btswildpig** [comment]
BitVPN owner agreed to change the name to "freevpn"

**Comment by nmushegian** [comment]
So how can we make this change without someone going and registering the asset name to which we are trying to change it?

I think maybe just disabling trades and transfers is fine?

**Comment by nmushegian** [comment]
but we also shouldn't disable the legit ones...
We might need to do it in two parts, the first time disable anyone from registering the version without the bit* prefix, and then once that is in we can safely change the names.

**Comment by nmushegian** [comment]
Actually that won't work either, for the same reason (someone registers the asset before hardfork blocks it).

I think preventing transfers/orders for MPA imitators is the only real solution.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/4b74882b2af2ee381001c6ef592c3dee843971b5
