### ISSUE TITLE
High priority : let users select datadir during install process

### ISSUE THREAD

**Issue by btswildpig** [BitShares/bitshares#1270]
Nowadays , even a chatting software can let you select where to store the data-file , for example , the one I'm using can let you have three options during install . How can a software which can have billions of dollars at stake still using the same design that stores the data at a location which no one would know about unless they're computer experts ? I've seen too many people hit on that front . It's not ok .

![image](https://cloud.githubusercontent.com/assets/9744912/5792288/1694818e-9f4c-11e4-86ce-31f556a138b1.png)

![image](https://cloud.githubusercontent.com/assets/9744912/5792455/ecce9b3e-9f53-11e4-971a-ec5d51daaf66.png)

If this function were to developed , there are 3  tasks .
1、For first time installer , select during the process . Just like the first picture . 
2、For upgraders , provide three ways to do so , in addition automatically copy the files in the original dita-dir and move it to the new location the users chooses . 
3、For users , provide these options in settings , so they can change it whenever the want .Just like the second picture described .

I don't know about how Linux users feels about this , but to Windows user , putting their wallet data in C drive is killing them . It affects both the chain data and the wallet .

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/qt_wallet/issues/90
