### ISSUE TITLE
tried to transfer 990,099 XTS and only 990 transfered

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1271]
```
default (unlocked) >>> wallet_transfer 990,098 XTS delegate0 delegate1
TIMESTAMP           BLOCK     FROM                TO                  AMOUNT                  MEMO                                        FEE                 ID      
======================================================================================================================================================================
2015-01-18T16:50:27 PENDING   delegate0           delegate1           990.00000 XTS                                                       0.50000 XTS         3f6327f6
```

The comma should probably trigger an error instead of trying to transfer...

**Comment by clayop** [comment]
Similar error occurs in Devshares as well. I think the wallet does not recognize (even in GUI) comma.

**Comment by vikramrajkumar** [comment]
Unlikely to be fixed; should be handled in the GUI if not already.

**Comment by dnotestein** [comment]
I really think should be fixed in the console client too. This is not the kind of bug we want to leave around to catch the unwary.

**Comment by vikramrajkumar** [comment]
It has to be an error; there is no way to tell if the user means 990099 or 990.099.

I don't think we can fix the reverse i.e. a user types `990.099` when they mean 990099.
