### ISSUE TITLE
testnet, full balance transfer missing

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1272]
A small transfer works but then a full transfer leads to missing funds...

```
jcalfee@jcalfee-desktop(develop): ~/bitshares/develop/tests/acceptance_tests
./testnet.rb 

entering node 'alice' interactive mode, enter 'exit' or 'quit' to exit
→ wallet_account_create tim
→ wallet_transfer 10 XTS angel tim
→ wallet_transfer 1,1 XTS angel tim
→ wallet_account_balance
ACCOUNT                         BALANCE                     
============================================================
angel                           47,474,988.00000 XTS        
tim                             11.00000 XTS    
→ wallet_transfer 47474987 XTS angel tim
→ blockchain_list_pending_transactions 
[]
No pending transactions.
→ wallet_account_balance
ACCOUNT                         BALANCE                     
============================================================
angel                           0.50000 XTS                 
tim                             11.00000 XTS                

```

**Comment by vikramrajkumar** [comment]
@jcalfee Does the correct balance eventually show up after any period of time? It may take a few seconds for the scanner to update the cache.

**Comment by jcalfee** [comment]
I have yet to see the balance show up; several restarts and some time has passed.  I was 1 day behind and discovered develop has a compiler error.  Not a big deal for me, I can work around it for now; i'll let you know what I discover.

**Comment by jcalfee** [comment]
By the way, the user acceptance tests pass.  So, this may be a special case: (like: having an account that is on the genesis block, or transferring to the unregistered account by name in the same wallet).

**Comment by jcalfee** [comment]
I went backwards to commit https://github.com/BitShares/bitshares/commit/14127f7a5926ca2fb0e94e58a83f0585e6b2af64 .. the transfer balance did eventually show up then transfers started working fine each block.

**Comment by jcalfee** [comment]
The build is fixed, but I'm still unable to test anything.  Transfers are still an issue for me on ubuntu using the latest develop code...

**Comment by jcalfee** [comment]
Same thing happened on DVS 0.6.0.  After wallet_delegate_withdraw_pay I see my balance was reduced but was not shown in the recipient's balance.  The balance did show up after I ran `wallet_rescan_blockchain`.

**Comment by vikramrajkumar** [comment]
Did you withdraw to the same wallet or a different wallet? Did the transaction show up for the recipient before rescanning?

**Comment by jcalfee** [comment]
Different wallet different machine ..  No, it did not show up before rescanning.  I waited several minutes before running the rescan.  The recipient was running before the transfer took place.

**Comment by bytemaster** [comment]
Can this be reproduced at will in a test?   Is transaction scanning enabled?

**Comment by vikramrajkumar** [comment]
@jcalfee What is the output of `wallet_get_info` when this occurs?

**Comment by jcalfee** [comment]
Sorry, I just saw your request.  Yes, something is cause my client's setting `transaction_scanning_enabled` to go to false on every re-start even though I have no active delegates.  I'll investigate that as a separate issue.

**Comment by jcalfee** [comment]
I re-did this test in a new environment and everything worked fine.  Out-of-the-box, transaction scanning was enabled.  After a full run in the acceptance_tests transaction scanning was still enabled.  I'm not sure how it would have been disabled but I think that was the cause.
