### ISSUE TITLE
address::is_valid is inconsistent about treatment of un-padded addresses

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1274]
@xeroc key generation Python script https://github.com/xeroc/pytshares breaks, but our tooling outputs an address which begins with a '1', see https://bitsharestalk.org/index.php?topic=12073

The `is_valid` implementation in [address.cpp](https://github.com/BitShares/bitshares/blob/128c0f70b8d0eabddb18975870e997136896c5c2/libraries/blockchain/address.cpp#L31-43) cannot seem to make up its mind whether an address smaller than the minimum length is allowed.  The `FC_ASSERT` which checks the length allows less than or equal, but OTOH the `memcmp` uses an absolute address to locate the checksum.

We should see if there is a standard (BIP?) specifying whether padding is required in an address, and have our tools follow the standard (tighten the length check to strict equality if padding is required, index the checksum properly if it is not).

**Comment by xeroc** [comment]
so it's about padding .. thanks for figureing it out .. would have taken me hours to find that out from the code

**Comment by theoreticalbts** [comment]
Looks like Bitcoin requires an address to decode to exactly 24 bytes (20 bytes ripemd160 plus 4 bytes checksum).  Adding that check to our validation, currently keys that decode to shorter lengths pass the length check but fail the checksum with high probability.

Bitcoin also assigns different semantics to initial 1's.  In particular, a Bitcoin address is essentially the following pseudo-regular-expression:

    ([1]*)([^1][base58-chars]*)

Essentially you decode the second group as base58, then prepend a number of 0 bytes specified by the length of the first group.  In other words, base58 is only capable of storing numbers that don't begin with a 0 byte, and Bitcoin uses prepended ones to unary-code the number of 0 bytes to prepend (because using base58 to store arbitrary byte strings must be able to handle any number of initial 0 bytes).

[1] https://en.bitcoin.it/wiki/Protocol_specification#Addresses

[2] https://en.bitcoin.it/wiki/Base58Check_encoding#Creating_a_Base58Check_string

**Comment by theoreticalbts** [comment]
It looks like `fc/src/crypto/base58.cpp` does treat leading 1's interoperably with Bitcoin.  So fc's base58 implementation is compatible.  The problem is the code in `blockchain/address.cpp` which uses fc's generic base58 functionality for addresses.

Specifically, the code attempts to accept un-padded addresses, but the unintended side effect of checksum indexing causes the code to actually reject them with high probability.

I will write a patch which simply rejects addresses which decode to the wrong length.  Usually the programmer's rule of thumb is "be liberal in what you accept."  But I think it would be wrong to follow the rule of thumb in this case -- for the good and simple reason that it's poor user experience if addresses have non-canonical forms which *sometimes* work in *some* tools in *certain* situations.

Further, accepting multiple equivalent forms for addresses might open up malleability style attack vectors on third-party systems that have "every address has exactly one canonical form" deeply and implicitly baked into their design.

I am fairly certain that this patch won't break anybody, because all of our tooling already outputs correctly padded addresses and (unintentionally, but with high probability) rejects incorrectly padded addresses.

@xeroc you will need to fix how your script's base58 address encode/decode implementation handles leading zero bytes, see references in the above posts for hints on how to do this.

**Comment by vikramrajkumar** [comment]
> Usually the programmer's rule of thumb is "be liberal in what you accept." But I think it would be wrong to follow the rule of thumb in this case

I agree. We should strive to keep the blockchain as strict as possible.

**Comment by vikramrajkumar** [comment]
Confirmed to not change syncing behavior for DVS and BTS.

**Comment by xeroc** [comment]
@theoreticalbts fixed the python code: 
https://github.com/xeroc/pytshares/blob/master/genbtskey.py#L21
added another check for the particular case of the forum
https://github.com/xeroc/pytshares/blob/master/genbtskey.py#L122
