### ISSUE TITLE
Incorrect response header in HTTP RPC

### ISSUE THREAD

**Issue by pmconrad** [BitShares/bitshares#1275]
In libraries/fc/network/http/http_server.cpp in fc::http::server::response::impl::send_header:

```
ss << "HTTP/1.1 " << rep.status << " ";
switch( rep.status ) {
            case fc::http::reply::OK: ss << "OK\r\n"; break;
            case fc::http::reply::RecordCreated: ss << "Record Created\r\n"; break;
            case fc::http::reply::NotFound: ss << "Not Found\r\n"; break;
            case fc::http::reply::Found: ss << "Found\r\n"; break;
            case fc::http::reply::InternalServerError: ss << "Internal Server Error\r\n"; break;
}
for( uint32_t i = 0; i < rep.headers.size(); ++i ) {
            ss << rep.headers[i].key <<": "<<rep.headers[i].val <<"\r\n";
}
```

The switch is lacking a default case, which means that for any unhandled response code the first header field is appended to the status line and therefore ignored by the client. This is particularly bad, because the first header is Connection: close, so HTTP/1.1 clients keep the connection open and fail on the next request.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/fc/commit/e1678b1801649e7e6cab84e92ffcb61d82cdd000
