### ISSUE TITLE
PTS prefix in account key

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1276]
See https://bitsharestalk.org/index.php?topic=12687 -- I'm assuming this is someone who imported a PTS key with a genesis block balance.  The user reports that the web wallet is showing them a key with PTS prefix, but I assume the web wallet is getting the key from a CLI command.

The end effect is that the user cannot register at @valzav faucet because the faucet cannot handle PTS addresses, but I think the correct fix for this is to find and fix the CLI command which is reporting the user account key with a PTS prefix.

**Comment by vikramrajkumar** [comment]
@valzav Can you confirm which RPC call is used to get the key for registering through the faucet?

**Comment by valzav** [comment]
wallet_get_account, then it picks the last key from active_key_history array

**Comment by vikramrajkumar** [comment]
I am watching the thread and will assume the user is using PTS2 instead of BTS unless I see otherwise.
