### ISSUE TITLE
Undefined signed overflow

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/bitshares#1278]
https://github.com/BitShares/bitshares/blob/32dc72dd6234f3c4580222cfa211d8b082de4576/libraries/blockchain/balance_operations.cpp#L323

**Comment by theoreticalbts** [comment]
Can we simply check that `amount_to_sender` and `amount_to_receiver` are each less than `BTS_BLOCKCHAIN_MAX_SHARES` ?

**Comment by vikramrajkumar** [comment]
@theoreticalbts Yeah that's prob good enough. The majority of our code does not check for overflow/underflow at all, so this isn't worth spending any time on.
