### ISSUE TITLE
Insufficient relay fee (36005) to cancel open BitSilver sell order

### ISSUE THREAD

**Issue by Ashaman-** [BitShares/bitshares#1280]
I apologize if this belongs in web_wallet.
I get an insufficient relay fee when I try to cancel an open BitSilver sell order.

getStackTrace@app.js:27:17454
 ○ request@app.js:32:26086
 ○ market_cancel_order@app.js:33:40307
 ○ cancel_order@app.js:32:19645
 ○ cancel_order@app.js:29:5698
 ○ app.js:7:20403
 ○ app.js:7:27250
 ○ $eval@app.js:6:48397
 ○ $apply@app.js:6:48680
 ○ app.js:7:27237
 ○ dispatch@app.js:3:14328
 ○ handle@app.js:3:11078
36005 insufficient_relay_fee: insufficient relay fee

    {"fees":0,"required_fees":10000}
    bitshares  chain_database.cpp:1544 evaluate_transaction

**Comment by bytemaster** [comment]
Is this repeatable?

**Comment by bytemaster** [comment]
What is the balance in your account when you attempt to cancel?

**Comment by vikramrajkumar** [comment]
Superseded by: #1327
