### ISSUE TITLE
github api gives old bitshares/tags 

### ISSUE THREAD

**Issue by davidpbrown** [BitShares/bitshares#1281]
The github api that gives the latest version, appears stalled for BTS, suggesting "v0.4.28-dev1" instead of "bts/0.5.0"
https://api.github.com/repos/BitShares/bitshares/tags

Where it does seem to work for DVS
https://api.github.com/repos/BitShares/DevShares/tags

**Comment by emfrias** [comment]
I'm not sure why the URL you give doesn't work, but try:

https://api.github.com/repos/BitShares/bitshares/git/refs/tags

Also, beware of relying on tags on the DevShares repository.  DevShares is just a place for us to upload releases for DevShares without confusing people by putting them in the BitShares repository.  The "real" tags for DevShares are the dvs/* tags in the bitshares repo:

https://api.github.com/repos/BitShares/bitshares/git/refs/tags/dvs
