### ISSUE TITLE
BitUSD:BitGOLD still insufficient feeds after fork.

### ISSUE THREAD

**Issue by graffenwalder** [BitShares/bitshares#1285]
Win 0.5.1

After importing the vesting balances I went to look at the new markets.
BitUSD:BitEUR gave an initial error: markets haven't been initialized.
But after putting up an order, the market openend.

But BitUSD:BitGOLD still says insufficient feeds.
I don't know if this is because there where already orders placed before the fork

**Comment by vikramrajkumar** [comment]
> But BitUSD:BitGOLD still says insufficient feeds.
> I don't know if this is because there where already orders placed before the fork

Have there been any new orders since the hardfork? It may need a new order to refresh the market.

**Comment by graffenwalder** [comment]
Just tried to do this. But got this error at 1400 usd/gold, 1000 and 600, while gold is trading above 1200:

(20034) You are attempting to bid at more than 5% above the buy price. This bid is based on economically unsound principles, and is ill-advised. If you're sure you want to do this, place your bid again and set allow_stupid_bid to true. [show details]

Also the price feed in the gui shows 0.00000

**Comment by nmushegian** [comment]
I was able to get some orders in with `allow_stupid_bid`, now it seems to work fine
