### ISSUE TITLE
blockchain_get_delegate_slot_records strange behavior

### ISSUE THREAD

**Issue by wackou** [BitShares/bitshares#1289]
In DevShares 0.6.0, when I call ``blockchain_get_delegate_slot_records delegate 10`` all is fine, but if I give a high value for ``count``, such as ``10000`` (more than the current blocks produced by a single delegate), then instead of just returning the blocks produced by that delegate, it does so but appends also blocks from the next(?) delegate, and the next one, etc. and returns nearly all the blocks from the blockchain.

**Comment by grzegorzs** [comment]
Parameter `count` does not affect the returned result. Always returns only one record.

**Comment by vikramrajkumar** [comment]
@grzegorzs I am unable to reproduce. Is this in the regression tests or separate? If you are working outside the regression tests, keep in mind that slot records are only indexed when `--statistics-enabled` flag is used (and a reindex if an existing chain). You can check by typing `config` and looking for `"statistics_enabled": true`.

**Comment by grzegorzs** [comment]
Regression test `blockchain_get_delegate_slot_records`
slot records are indexed 
`"statistics_enabled": true,`

still returns only one record
```
default (unlocked) >>> blockchain_get_delegate_slot_records delegate45 4
[{
    "index": {
      "delegate_id": 46,
      "timestamp": "2014-06-20T14:41:00"
    },
    "block_id": "087eea976d1e77640ae72e4ed6f2261e58870228"
  }
]

```

**Comment by vikramrajkumar** [comment]
```
default (unlocked) >>> blockchain_list_blocks
HEIGHT  TIMESTAMP           SIGNING DELEGATE                # TXS   SIZE    LATENCY PROCESSING TIME  RAND           
====================================================================================================================
4       <d-ign>2014-06-20T14:41:00</d-ign><d-ign>                         delegate45</d-ign>0       166     <d-ign> 0</d-ign><d-ign>          0.000686</d-ign><d-ign>        5145bd6009c78fff2fc46ffced4c5aeeb5e6286c</d-ign>
3       <d-ign>2014-06-20T14:40:50</d-ign><d-ign>                         delegate44</d-ign>0       166     <d-ign> 0</d-ign><d-ign>          0.000899</d-ign><d-ign>        f00e7ffa074d41538766c540b0ba58b2532fdcbb</d-ign>
2       <d-ign>2014-06-20T14:40:40</d-ign><d-ign>                         delegate43</d-ign>0       166     <d-ign> 0</d-ign><d-ign>          0.000804</d-ign><d-ign>        651f4a46471d05b65eb769e890392640878b3f97</d-ign>
1       <d-ign>2014-06-20T14:40:30</d-ign><d-ign>                         delegate42</d-ign>0       166     <d-ign> 0</d-ign><d-ign>          0.000836</d-ign><d-ign>        2322c73ae804adc5c3e9ec4d188eee59871e4604</d-ign>
```
@grzegorzs This is expected output, since delegate45 has only had 1 slot so far. I've tweaked the API to make this a little more clear.
