### ISSUE TITLE
Implement wallet_market_sell

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1290]
The `wallet_market_sell` command will sell something you have and choose order type accordingly based on asset ID's (e.g. if selling BTS will place an ask, if selling USD then will place a bid).

@bytemaster : I am working on this, my patch is much further along than 285f0fa89ccb9a4be50c56a052e9c07d360df57b .  So please wait for me to merge my patch later today to avoid duplication of effort.

**Comment by theoreticalbts** [comment]
You can see my patch at https://github.com/theoreticalbts/bitshares/tree/relorder

*PLEASE DO NOT MERGE THIS* it likely does not compile, will be rebased / squashed on a regular basis, and is generally not fit for public consumption.  I'm only providing it to keep you up-to-date and hopefully avoid any further duplication of effort.

**Comment by theoreticalbts** [comment]
https://github.com/theoreticalbts/bitshares/tree/relorder now compiles and `wallet_market_sell` is ready for initial testing.  NB the patch still needs squashed before it's ready to apply.

**Comment by theoreticalbts** [comment]
Commits needed for this:

- ca734928766de2a49f135bea96067e1711fe8690 - wip relative order percentage implementation
- ca75c21f1c477e1f1e986f40cba48e0cc17a021e - wip relorder tests
- 32dc72dd6234f3c4580222cfa211d8b082de4576 - wip funding parameter (obsolete)
- acd71b7ffcdee3de6559aac287c9acece2e42ef8 - (Re)implement wallet_market_sell using mature infrastructure 
- 1b7eaf4274eab6b3b8976bd1dcbb147a89c6e490 - wallet_sell: Test sell order
- 35a5428badd6c6deafaae8068422cf69165dfa12 - wallet_sell: Get needs_satoshi_conversion from caller in apply_order_to_builder (obsolete)
- 321005d4f8c86422db73dcbcfd511e7eff4392b5 - wallet_sell: Compute desired quantity for absolute bids (obsolete)
- 5995e0fad340b970b997186e6148e0ba1ea79cb3 - Fix #1296 (obsolete)
- 5e858c7043f8c601ae8876a88aaee335e2de43d8 - Allow real_quantity to be either asset in `submit_bid()` (required by afefcb642af2df004901dc84d7310cc6622e6b9c )
- afefcb642af2df004901dc84d7310cc6622e6b9c - wallet_sell: Don't route sell orders through apply_order_to_builder

The commits market "obsolete" are changes that ended up being superseded by later changes.  Normally I do things in private branches so I don't pollute the repo everyone uses with half-baked changes using questionable architecture decisions that end up being replaced or heavily refactored when I realize how brittle they are.

But @bytemaster thinks this development style doesn't fit well with the team's workflow, so I'm trying to be more aggressive about pushing, with the result that some less-than-airtight patches have made it onto the develop branch.  In a private branch I would simply rebase them out, but that's not an option after I've already pushed them to develop.  @vikramrajkumar it's up to you if you want to rebase them out before merging with master, or if you want to include them in bitshares / master branch as-is.

**Comment by vikramrajkumar** [comment]
@theoreticalbts I will keep them as-is since they are already in develop, but do know that I support your preferred workflow. There seems to have been some conflict this time due to @bytemaster's desire to work on the same code as you, but in the future I encourage you to continue trusting your own judgment.

**Comment by theoreticalbts** [comment]
`wallet_market_sell` has a broken API and nothing uses it.  I think the best resolution at this point is to get rid of it entirely.
