### ISSUE TITLE
There is a need for rpc call that lists all wallet's open orders

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1291]
Could we make wallet_market_order_list to return all open orders when called without parameters?

**Comment by vikramrajkumar** [comment]
@valzav Does `wallet_account_order_list` work?

**Comment by valzav** [comment]
It requires a market to be specified - this doesn't work when I need to show all user's orders

**Comment by vikramrajkumar** [comment]
@valzav Are you sure you are looking at `wallet_account_order_list` and not `wallet_market_order_list`? The former has no required arguments.

**Comment by valzav** [comment]
my bad - I was looking at wallet_market_order_list
