### ISSUE TITLE
Question: C library for EC

### ISSUE THREAD

**Issue by svk31** [BitShares/bitshares#1292]
I'm not sure which EC curve Bitshares uses, but assuming it's the same as Bitcoin, would it be possible to adopt the optimized EC operations library developed by Pieter Wuille once it's ready? 

https://github.com/bitcoin/secp256k1

In one of Gavin's latest blog posts on his 20 Mbyte block size tests he says the following: 

> "Of course, we won't be running current code on tomorrow's hardware; we'll be running better code. CPU usage should go down by a factor of about eight in the next release when we switch to Pieter's libsecp256k1 library for validating transactions"

http://gavintech.blogspot.de/2015/01/twenty-megabytes-testing-results.html

**Comment by emfrias** [comment]
TestZ Crypto brought this up on one of the skype groups about this last week, and it sounded like he had some success replacing OpenSSL either in BitShares or in Sparkle, maybe he can chime in.

**Comment by testzcrypto** [comment]
According information in the Internet secp256k1 10-100 times faster than OpenSSL - my tests just confirms it.

**Comment by vikramrajkumar** [comment]
I am interested in this also; but that lib is young and not production-ready. Bitcoin core only currently only uses it for signature verification IIRC.

**Comment by svk31** [comment]
Sounds good, so basically once this is deemed ready for Bitcoin we can easily integrate this in Bitshares?

**Comment by vikramrajkumar** [comment]
I don't know about "easily", but yeah as Bitcoin proves its maturity we can begin to integrate it. Keep in mind that this is a fundamental crypto library, so that could take a very long time--and this is low priority at the moment anyway.
