### ISSUE TITLE
Update blockchain_list_address_transactions to return a variant_object

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1299]
https://github.com/BitShares/bitshares/blob/7e50eaa7f1dee0805383f3d9af22147c6b3d82f9/libraries/client/blockchain_api.cpp#L368

Instead of using the array (make_pair), the block.timestamp value  should probably go under the variant object with a label like "block_timestamp"...

**Comment by jcalfee** [comment]
I tried a patch, didn't work thouhg.. I'll re-visit later.  Input welcome...
 http://pastebin.com/fT21xuXb
```
/home/jcalfee/bitshares/develop/libraries/client/blockchain_api.cpp:364:38: error: ‘json_type_variant’ was not declared in this scope
    fc::variant_object json_results = json_type_variant.get_object();
```

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/7b294e5c5afc230431aadeaf018aaae2e5461661
