### ISSUE TITLE
vote_delegates_recommended regression test contains control characters, and is broken (likely by 

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1307]
tests/regression_tests/vote_delegates_recommended was displaying in my editor as gibberish, due to the editor choosing a strange encoding because it contains control characters.  I had to run the file through

    cat tests/regression_tests/vote_delegates_recommended/client0.log | tr '\000' '~' | tr '\001' '!' > tests/regression_tests/vote_delegates_recommended/client0-fix.log

in order to convince my editor to show me the actual content of the file.  It looks like this:

    DELEGATE                        VOTES                   APPROVAL
    ================================================================
    mydelegate                      100.00000 XTS           ~       
    default (unlocked) >>> debug_wait_for_block_by_number 11
    OK
    default (unlocked) >>> wallet_account_balance account0
    ACCOUNT                         BALANCE                     
    ============================================================
    account0                        200.00000 XTS               
    default (unlocked) >>> wallet_account_vote_summary
    DELEGATE                        VOTES                   APPROVAL
    ================================================================
    delegate1                       100.00000 XTS           !       
    delegate10                      100.00000 XTS           !       
    delegate2                       100.00000 XTS           !       
    delegate20                      100.00000 XTS           !       
    delegate3                       100.00000 XTS           !       
    delegate40                      100.00000 XTS           !       
    delegate5                       100.00000 XTS           !       
    mydelegate                      200.00000 XTS           ~       

So it appears the console formatting for the output of the command in the version of the client used to produce the text, outputs the number as a binary character instead of formatting it in decimal!  This is obviously incorrect.

Furthermore, on my system the test fails here:

    default (unlocked) >>> wallet_transfer 100 XTS account1 account0 "vote all" "vote_all"
    Command failed with exception: unknown delegate slate (32011)

Based on browsing recent commit messages for likely suspects, I think the exception may be due to 76b94d03f92425c1d1a4711332659b7c3897ce59 .  @vikramrajkumar please try to reproduce this exception and find the root cause.

@grzegorzs while we always appreciate people helping us run tests and keep them up to date, please pay a little more attention to whether the output of the test makes sense (binary characters?) and be sure your test log updates reflect the latest develop branch (I am guessing you ran this test with an older version as the reason your test results and mine are different).

**Comment by vikramrajkumar** [comment]
@theoreticalbts Exception and bad pretty-printing should be fixed now.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/1454796f05487b1e3586ac36566e484f9338e36f
