### ISSUE TITLE
API should never return doubles

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1308]
One common programmer's rule of thumb is "never use floating point for anything to do with money and accounting, ever, under any circumstances."

Unfortunately, early versions of the code did not strictly stick to this rule of thumb, and for many months now the developers have been waging an ongoing campaign to weed out doubles whenever and wherever they are found.

To this end, I want to eliminate doubles from the API entirely.  The main purpose is to help third-party client libraries follow the "never use floating point for money" rule, even if the JSON parser turns numbers into doubles and does not provide straightforward hooks to allow the user to override this behavior.  If everything in our API which is a potentially fractional value -- in particular prices -- is a string, then third-party clients will have no problem applying their own parsing function.

Secondary bonuses include ease of readability and portability.  This ticket was inspired by this regression test failure when testing `blockchain_get_feeds_from_delegate` :

    failed on line 283
    expect: 283:     "price": 2.0000000000000002e-005,
    actual: 283:     "price": 2.0000000000000002e-05,

- The price was entered as `0.00002`, but appears as `2.0000000000000002e-05`.
- Both the loss of "exactness" (that final 2) and the scientific notation are undesirable user experience and may even lead to non-idempotency (if a delegate sets their feed to the value returned by `blockchain_get_feeds_from_delegate` for their own account, it should in theory be a no-op, but it may not be due to the combination of output formatting and input parsing)
- Apparently this difference is due to running on two different combinations of OS, compiler, runtime and libraries resulting in `e-05` vs. `e-005`

I will leave this ticket open until I have had a chance to review all API methods, clean up as many doubles as possible, and note the ones that can't be converted for whatever reason.

**Comment by bytemaster** [comment]
This has more to do with JSON parsing / printing than anything else.   JSON does not allow scientific notation and thus this means the formatting flags on the ostream used to dump the JSON are wrong.

**Comment by theoreticalbts** [comment]
> JSON does not allow scientific notation

http://json.org/ begs to differ.  And it's kind of common sense -- in order to be useful, any data interchange format which supports floating point values must have a concise way to represent e.g. `1e300` (which is a legal double value).

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/e84405ddaacc43474a4a3b89044bcf5bf24ae338
