### ISSUE TITLE
GUI bug:vote id→id display as id→self confuse the transfer id→self

### ISSUE THREAD

**Issue by todasun** [BitShares/bitshares#1311]
![image](https://cloud.githubusercontent.com/assets/10720816/5914477/f7c55ac6-a630-11e4-899f-a656e57ff3e1.png)
system action，the color is gray
but  vote action  id→ self   ,color is blue
although the user id  self has robothash  but still may confuse
it would be better to display   id→id  instead of  id→self

wallet_account_transaction_history  display the right data   from  “id”  to  “id”

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/545
