### ISSUE TITLE
wallet_delegate_update_signing_key fails with "get_head_block_num() >= BTS_V0_4_28_FORK_BLOCK_NUM"

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1313]
delegate (unlocked) >>> wallet_delegate_update_signing_key payouts.xeroc xeroc-delegate-1 BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV
    10 assert_exception: Assert Exception
    eval_state._current_state->get_head_block_num() >= BTS_V0_4_28_FORK_BLOCK_NUM:
        {}
        th_a  account_operations.cpp:174 evaluate

        {"*this":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}}
        th_a  account_operations.cpp:197 evaluate

        {"op":{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}}}
        th_a  operation_factory.hpp:52 evaluate

        {"op":{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}}}
        th_a  transaction_evaluation_state.cpp:242 evaluate_operation

        {"trx_arg":{"expiration":"2015-01-27T09:41:19","slate_id":null,"operations":[{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}},{"type":"define_delegate_slate_op_type","data":{"slate":{"supported_delegates":[129,136,266,317,335,371,774,875,1193,2151,4458,4914,6006,6939,8286,9810,9811,9870,9871,9872,9878,9879,9954,10082,10093,10171,10173,10174,10206,10207,10213,10214,10243,10287,10288,10306,10323,10425,10493,10810,10819,10825,11083,11099,13721,14020,14025,14764,14872,15017,18771,19793,21130,21539,21706,23045,23569,23728,23839,24255,28812,29174,29208,30573,30668,30739,30758,30892,30919,30969,30971,30974,30975,31119,31147,31240,31248,31349,31427,31435,31491,31492,31602,31739,31837,31972,32025,32075,32076,32077,32078,32227,32324,32328,32330,32334,32337,32340,32360,32526,32539,32562,32592,32692,32822]}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4UsscZDVo42HcJtGwMQJijk61djg3N1uM","amount":10000,"claim_input_data":""}}],"signatures":["2052b2132541825f8eb7cd9dba8d29709fe4421280041e9cd08f3056d474f10b4871be148bc20a1450f312e0ba0c75d6c7f9d3687f52441d8bee1a76f46b5a364b","1f53b95ffe5c8fa576dbc3b8a147ac4fcdd05cd31661f65a471be773a215a0dac640e497a3bb485571b3dc3771a76824aa32aa03e367dc7aef382bc2bfb0594c4a"]},"skip_signature_check":false,"enforce_canonical":false}
        th_a  transaction_evaluation_state.cpp:237 evaluate

        {"trx":{"expiration":"2015-01-27T09:41:19","slate_id":null,"operations":[{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}},{"type":"define_delegate_slate_op_type","data":{"slate":{"supported_delegates":[129,136,266,317,335,371,774,875,1193,2151,4458,4914,6006,6939,8286,9810,9811,9870,9871,9872,9878,9879,9954,10082,10093,10171,10173,10174,10206,10207,10213,10214,10243,10287,10288,10306,10323,10425,10493,10810,10819,10825,11083,11099,13721,14020,14025,14764,14872,15017,18771,19793,21130,21539,21706,23045,23569,23728,23839,24255,28812,29174,29208,30573,30668,30739,30758,30892,30919,30969,30971,30974,30975,31119,31147,31240,31248,31349,31427,31435,31491,31492,31602,31739,31837,31972,32025,32075,32076,32077,32078,32227,32324,32328,32330,32334,32337,32340,32360,32526,32539,32562,32592,32692,32822]}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4UsscZDVo42HcJtGwMQJijk61djg3N1uM","amount":10000,"claim_input_data":""}}],"signatures":["2052b2132541825f8eb7cd9dba8d29709fe4421280041e9cd08f3056d474f10b4871be148bc20a1450f312e0ba0c75d6c7f9d3687f52441d8bee1a76f46b5a364b","1f53b95ffe5c8fa576dbc3b8a147ac4fcdd05cd31661f65a471be773a215a0dac640e497a3bb485571b3dc3771a76824aa32aa03e367dc7aef382bc2bfb0594c4a"]}}
        th_a  chain_database.cpp:1550 evaluate_transaction

        {"trx":{"expiration":"2015-01-27T09:41:19","slate_id":null,"operations":[{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}},{"type":"define_delegate_slate_op_type","data":{"slate":{"supported_delegates":[129,136,266,317,335,371,774,875,1193,2151,4458,4914,6006,6939,8286,9810,9811,9870,9871,9872,9878,9879,9954,10082,10093,10171,10173,10174,10206,10207,10213,10214,10243,10287,10288,10306,10323,10425,10493,10810,10819,10825,11083,11099,13721,14020,14025,14764,14872,15017,18771,19793,21130,21539,21706,23045,23569,23728,23839,24255,28812,29174,29208,30573,30668,30739,30758,30892,30919,30969,30971,30974,30975,31119,31147,31240,31248,31349,31427,31435,31491,31492,31602,31739,31837,31972,32025,32075,32076,32077,32078,32227,32324,32328,32330,32334,32337,32340,32360,32526,32539,32562,32592,32692,32822]}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4UsscZDVo42HcJtGwMQJijk61djg3N1uM","amount":10000,"claim_input_data":""}}],"signatures":["2052b2132541825f8eb7cd9dba8d29709fe4421280041e9cd08f3056d474f10b4871be148bc20a1450f312e0ba0c75d6c7f9d3687f52441d8bee1a76f46b5a364b","1f53b95ffe5c8fa576dbc3b8a147ac4fcdd05cd31661f65a471be773a215a0dac640e497a3bb485571b3dc3771a76824aa32aa03e367dc7aef382bc2bfb0594c4a"]},"override_limits":true}
        th_a  chain_database.cpp:2053 store_pending_transaction

        {"transaction_record":{"index":0,"record_id":"810aebd342ce142f4e87f9417e624de3eff9895e","block_num":0,"is_virtual":false,"is_confirmed":false,"is_market":false,"trx":{"expiration":"2015-01-27T09:41:19","slate_id":null,"operations":[{"type":"update_signing_key_op_type","data":{"account_id":509,"signing_key":"BTS6HK8UGX5GWonz1P3GXbhnB4u4PS72K2mhj6GyecVYZ5fAAspPV"}},{"type":"define_delegate_slate_op_type","data":{"slate":{"supported_delegates":[129,136,266,317,335,371,774,875,1193,2151,4458,4914,6006,6939,8286,9810,9811,9870,9871,9872,9878,9879,9954,10082,10093,10171,10173,10174,10206,10207,10213,10214,10243,10287,10288,10306,10323,10425,10493,10810,10819,10825,11083,11099,13721,14020,14025,14764,14872,15017,18771,19793,21130,21539,21706,23045,23569,23728,23839,24255,28812,29174,29208,30573,30668,30739,30758,30892,30919,30969,30971,30974,30975,31119,31147,31240,31248,31349,31427,31435,31491,31492,31602,31739,31837,31972,32025,32075,32076,32077,32078,32227,32324,32328,32330,32334,32337,32340,32360,32526,32539,32562,32592,32692,32822]}}},{"type":"withdraw_op_type","data":{"balance_id":"BTS4UsscZDVo42HcJtGwMQJijk61djg3N1uM","amount":10000,"claim_input_data":""}}],"signatures":["2052b2132541825f8eb7cd9dba8d29709fe4421280041e9cd08f3056d474f10b4871be148bc20a1450f312e0ba0c75d6c7f9d3687f52441d8bee1a76f46b5a364b","1f53b95ffe5c8fa576dbc3b8a147ac4fcdd05cd31661f65a471be773a215a0dac640e497a3bb485571b3dc3771a76824aa32aa03e367dc7aef382bc2bfb0594c4a"]},"ledger_entries":[{"from_account":"BTS6uvZsnN2KWFpKRecLkSmZByoYEdAQk5ZDx8memPMw2qQhaPTM1","to_account":"BTS7dJoXqDatFan2oe3tSUD6ZJEhDnUGcMf3dkWXRuTGumejFZt4P","amount":{"amount":0,"asset_id":0},"memo":"update block signing key","memo_from_account":null}],"fee":{"amount":10000,"asset_id":0},"created_time":"2015-01-27T08:33:59","received_time":"2015-01-27T08:33:59","extra_addresses":[]}}
        th_a  transaction_ledger.cpp:1393 cache_transaction

        {}
        th_a  common_api_client.cpp:6151 wallet_delegate_update_signing_key

        {"command":"wallet_delegate_update_signing_key"}
        th_a  cli.cpp:629 execute_command

**Comment by vikramrajkumar** [comment]
This is not enabled in BitShares yet; only DevShares so far.
