### ISSUE TITLE
Test UIA issuer market fee 

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1316]
The market fee allows the issuer to charge up to 10% of the proceeds of a bid/ask getting matched and paying out in that amount.  

At the moment the market transaction history will still report the FULL payout amount in bid_received or ask_received, but the blockchain will actually pay the issuer the fee and deduct it from the amount they actually receive.   This will appear deceptive in the transaction ledger unless we can update the market order history to separately track "quote_issuer_received" and "base_issuer_received" outputs and then update the sanity check validation to account for that.

**Comment by dnotestein** [comment]
This is to test changes made in https://github.com/BitShares/bitshares/commit/c438aedc78a47adbaf86571f29d30f09a1a48d36

**Comment by grzegorzs** [comment]
test added 0760b62ba34eed6450114a851d7a88fbe2223a33
