### ISSUE TITLE
New accounts should default to using non-titan transfers

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1318]

**Comment by abitmore** [comment]
Do it at GUI level please. I don't think it's a good idea to change the default behavior of current API.

**Comment by jcalfee** [comment]
I agree, the GUI level should do the trick.  The GUI or faucets can create new accounts as a public_account by default.  This should be enough because a public account can transfer to or receive from a titan account and the GUI will only need to see its own public account transactions.

**Comment by vikramrajkumar** [comment]
I'll leave this change at the GUI level for now, as @abitmore suggested. When we implement the light wallet's brain seed system in the full wallet, this can be revisited.
