### ISSUE TITLE
Only send TITAN transfers to registered TITAN accounts

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1319]

**Comment by vikramrajkumar** [comment]
Sort of a consequence of #1318--a TITAN deposit should be made iff the recipient is a registered account who publishes TITAN as their preferred receiving method.

**Comment by vikramrajkumar** [comment]
This was mostly already addressed by: #1241

**Comment by vikramrajkumar** [comment]
Still using TITAN for unregistered contacts.
