### ISSUE TITLE
Set market as dirty on block where cover order expires

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1320]
If a non-expired cover order becomes expired, currently it doesn't execute immediately because the market isn't marked as dirty.

However, anything which flags the market as dirty -- e.g. any delegate who publishes a feed or any user who places an order -- will result in the cover order executing.  So I'm not sure if this is really an issue:

- Anyone can force the market to run by placing an order in the market
- Anyone trying to take advantage of the situation in a way that involves placing an order in the market would make the market run, defeating the purpose of the maneuver
- Important markets get orders and feed updates fairly often

Feel free to flag this as wontfix, but I wanted to at least document the behavior if we aren't going to do anything about it.

**Comment by vikramrajkumar** [comment]
wontfix
