### ISSUE TITLE
offer the negative vote on UI

### ISSUE THREAD

**Issue by cgafeng** [BitShares/bitshares#1321]
Many people want to have the power to vote against somebody.
We have a way to do this on ui.
Against someone is the equality of support the others, so we vote everyone we don't against then got what we want.
But people is lazy to select so many people, then just select the guys who they like and against, the vote algorithm add the top others until the max they can vote for(like 101).

**Comment by vikramrajkumar** [comment]
Negative voting has been discussed heavily on the forums (e.g. https://bitsharestalk.org/index.php?topic=5569.msg74770#msg74770) and we do not currently support it or have plans to.
