### ISSUE TITLE
Bad Cast error for any HTTP Json RPC command

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1322]
In the develop branch, there is "Invalid cast from array_type to string" for any rpc command that gets sent.  This means the web clients will not operate.
```
cat<<-eee|curl --data-binary -d @ http://test:test@localhost:${HTTP_PORT}/rpc
{"method":"open","params":["default"]}
eee
curl: (6) Could not resolve host: 
Invalid RPC Request
7 bad_cast_exception: Bad Cast
Invalid cast from string_type to Object
    {"type":"string_type"}
    th_a  variant.cpp:539 get_object
```
Maybe it is this? 
https://github.com/BitShares/fc/commit/40943808d0f1c134c0559a5904e3cac03cbda478

this extra call to fc::json::to_string should be fine: https://github.com/BitShares/bitshares/commit/e25740b290cbf1367f95d33d632aaf07317389b0#diff-6036c4ee3be744b58d610de2231b6846L317

**Comment by vikramrajkumar** [comment]
@jcalfee Are you using latest develop? This was fixed yesterday by: https://github.com/BitShares/bitshares/commit/5cc25172f31c150505f32e5a88a874a18c43cdc5

**Comment by jcalfee** [comment]
Latest as of yesterday..  Thanks I'm updating now.
