### ISSUE TITLE
insufficient fee when canceling

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/bitshares#1327]
https://bitsharestalk.org/index.php?topic=13812.msg179684#msg179684

**Comment by cassiopaia** [comment]
is this included into 0.6.0 already!? Sam problem with order canceling! My problem is i really have to  cancel those orders!

**Comment by cassiopaia** [comment]
Change it to 0.5 temporarily and cancel the order!

Ths solves my issue!

**Comment by vikramrajkumar** [comment]
@cassiopaia This fix will not come into effect until the hardfork.
