### ISSUE TITLE
Transaction with multiple withdraw_op_type from same balance_id

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1330]
I was browsing bitsharesblocks and happened to see the following transaction:

    [
      "b4a2a5b84ebb74e142551ed84b578d59041bdf93",{
        "trx": {
          "expiration": "2015-01-30T16:31:55",
          "slate_id": null,
          "operations": [{
              "type": "withdraw_op_type",
              "data": {
                "balance_id": "BTSJDifrf89swyNoB6b9cNdvtQKHew3cawGW",
                "amount": 51,
                "claim_input_data": ""
              }
            },{
              "type": "withdraw_op_type",
              "data": {
                "balance_id": "BTSJDifrf89swyNoB6b9cNdvtQKHew3cawGW",
                "amount": 50000,
                "claim_input_data": ""
              }
            },{

Looks like there's two `withdraw_op` coming from the same `balance_id`.

Our code shouldn't generate transactions like this -- although I'm not sure if it's worth fixing in the old transaction builder which is going to be deprecated anyway.

I'm almost thinking it would be better to have an "optimization pass" after transaction has been built, which takes a transaction and optimizes it by combining multiple `withdraw_op_type` (and any other semantics-preserving but size-reducing transformations we can come up with).

Once we fix this in our own wallet, we should consider tightening validation to make this transaction fail, forcing all compatible wallets to combine withdraw / deposit operations with the same `balance_id`.

**Comment by vikramrajkumar** [comment]
Too low priority; not worth addressing until we decide on and switch to a canonical way to construct transactions in the full wallet instead of the 3+ different ways it can be done now.
