### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Benjammin793** [BitShares/bitshares#1334]
--When flipping through tabs (ex. Delegate information), the back button switches only between tabs. It does not take me to the delegate selection screen. Can get annoying if I've moved around a bit.

-- At a certain point in the window size, objects on the task bar begin to overlap disruptively. Maybe add a minimum window size ?

-- Can only filter Delegates by name, cannot filter delegates by approval rating, or Pay rate.

-- It would be nice to be able to sort Categories on the Delegate Screen 
![delegate sorting](https://cloud.githubusercontent.com/assets/9312766/5983545/44a19374-a89c-11e4-8965-e49fd69bb390.png)

--Blocks Produced added as delegate category

-- There is no place to view people who you have added as contacts (if there is it is not easy to find)

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/555
