### ISSUE TITLE
Issue With Short Mode Option

### ISSUE THREAD

**Issue by dclark25** [BitShares/bitshares#1336]
Under Exchange, when I click on the Short DVS tab and check the Short Mode check box, the option to deactivate Short Mode under the Short DVS tab goes away so I have to click the Short Mode option at the top of the page. It's a bid weird and inconvenient when it does this.
![short mode 1](https://cloud.githubusercontent.com/assets/5420442/5984109/fef30646-a8a0-11e4-9a68-532a5f66a56c.JPG)
![short mode 2](https://cloud.githubusercontent.com/assets/5420442/5984114/01e6790a-a8a1-11e4-8369-13f6e731e541.JPG)

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/556
