### ISSUE TITLE
Wallet created before first password given locks user from creating account.

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1337]
https://bitsharestalk.org/index.php?topic=13506.0;topicseen

**Comment by theoreticalbts** [comment]
Doesn't this belong in web_wallet repo?

**Comment by vikramrajkumar** [comment]
The first issue (https://bitsharestalk.org/index.php?topic=13506.msg176386#msg176386) seems to be a `qt_wallet` issue in that there is no way to delete your wallet--which we probably don't want to support for now.

The second issue (https://bitsharestalk.org/index.php?topic=13506.msg180305#msg180305) might be a `web_wallet` issue, @valzav can you confirm?

**Comment by vikramrajkumar** [comment]
Possible partial mitigation: https://github.com/BitShares/qt_wallet/commit/40391bef624fed4e3a59182e4e147ee7c1f8983f

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/commit/13730df471f10b052c3ed22701846110f2666cf5
