### ISSUE TITLE
Unable to cancel Orders ! 

### ISSUE THREAD

**Issue by cassiopaia** [BitShares/bitshares#1339]
After clicking cancel button ... i'm seeing cancelling ... but nothing happens over minutes (BitSILVER market)

**Comment by graffenwalder** [comment]
I have the Same problem onceuponatime reported it earlier. This is the relay fee.
The strange thing is it only happens with Bitsilver.

**Comment by vikramrajkumar** [comment]
Probably duplicate: #1327
