### ISSUE TITLE
Can we enable wallet_asset_update in next official release?

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1341]
It's enabled in develop, but disabled in bitshares branch (command is there, but throws an exception that disables it).

**Comment by vikramrajkumar** [comment]
It's disabled since the asset system is still being developed per #1084, and if we enable it in its current incarnation we may end up wanting to throw it out in favor of something else like the current `update_asset_ext_operation`.

**Comment by vikramrajkumar** [comment]
Refer to master issue #1084.
