### ISSUE TITLE
Thoroughly specify and test behavior when feeds are out-of-date

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1343]
Feed updates expire after a day.  If a quorum of non-expired feeds are not available, it seems like shorts, relative orders, and margin calls should all be suspended.

A test to figure out what the code actually does in this case seems like it would be helpful.

**Comment by vikramrajkumar** [comment]
The relevant lines for shorts and covers:
- https://github.com/BitShares/bitshares/blob/b34d1e6ffb05e0cd1efd345c0379647c5c0c174d/libraries/blockchain/market_engine.cpp#L102
- https://github.com/BitShares/bitshares/blob/b34d1e6ffb05e0cd1efd345c0379647c5c0c174d/libraries/blockchain/market_engine.cpp#L145

There currently seems to be no such check for relative orders.
