### ISSUE TITLE
Add owner key to wallet_add_contact_account 

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1346]
This RPC interface is used by the faucet.  It is registering accounts by there name and active key.  The bitshares_client has been assigning a different owner key (different from the active key) so this means that the web service and the faucet is broken.  An account registered in this way will not work.

https://github.com/BitShares/web_wallet/issues/529

https://github.com/BitShares/web_services/blob/master/faucet/app/services/account_registrator.rb#L32-L42

**Comment by jcalfee** [comment]
To clarify, the error shows up when the owner tries to transfer from the account.  The wallet will check on the blockchain and see that the wallet's owner does not match the blockchain owner and throw an error.

**Comment by vikramrajkumar** [comment]
Related: #1283

**Comment by vikramrajkumar** [comment]
Superseded by: #1401
