### ISSUE TITLE
wallet_transfer - failed

### ISSUE THREAD

**Issue by grzegorzs** [BitShares/bitshares#1352]
Regression test `wallet_account_vote_summary`
after `wallet_account_set_approval`, function `wallet_transfer` failed (before is OK)
```
default (unlocked) >>> wallet_account_set_approval delegate50 1
1
default (unlocked) >>> wallet_transfer 100 XTS delegate0 test my_message "vote_all"
Command failed with exception: Assert Exception (10)
condition.slate_id == 0 || db.lookup<slate_record>( condition.slate_id ).valid(): 

```
A similar problem occurs in the test `vote_delegates_recommended`

**Comment by theoreticalbts** [comment]
Culprit is 34e31cda

I'm not sure what the purpose of the sanity checks is, but it seems like the problems is that the changes might not adequately consider the case of a transaction that defines a slate and immediately votes for the newly defined slate.

**Comment by theoreticalbts** [comment]
Assigning this to @vikramrajkumar as the author of the commit in question.

**Comment by vikramrajkumar** [comment]
The purpose of the sanity checks is to help mitigate bugs in the state transitions, of which we have had dozens.
