### ISSUE TITLE
Shorts below the price feed are mind-bending and possibly wrong

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1354]
At price feed value of 0.02, try shorting at 0.01:

    >>> wallet_market_submit_ask alice 12500 XTS 0.01 USD
    >>> wallet_market_submit_short alice 25000 XTS 0 USD 0.01

Get this order book:

         BIDS (* Short, + Relative, - Relative Limit)                            |                                   ASKS                                  
    TOTAL                     QUANTITY                                     PRICE | PRICE                                        QUANTITY                     TOTAL   COLLATERAL
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    125.0000 USD              12,500.00000 XTS                0.010000000000 USD*| 0.010000000000 USD                   12,500.00000 XTS              125.0000 USD
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                 SHORT WALL                                      |                                   MARGIN                                  
    TOTAL                     QUANTITY                       INTEREST RATE (APR) | CALL PRICE                                   QUANTITY                     TOTAL   COLLATERAL    EXPIRES
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                 | 
    Maximum Short Price: 0.02 USD / XTS     

Then only half the order matches despite the fact that the short requested 2x collateralization:

         BIDS (* Short, + Relative, - Relative Limit)                            |                                   ASKS                                  
    TOTAL                     QUANTITY                                     PRICE | PRICE                                        QUANTITY                     TOTAL   COLLATERAL
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    62.5000 USD               6,250.00000 XTS                 0.010000000000 USD*|
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                 SHORT WALL                                      |                                   MARGIN                                  
    TOTAL                     QUANTITY                       INTEREST RATE (APR) | CALL PRICE                                   QUANTITY                     TOTAL   COLLATERAL    EXPIRES
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                 | 0.010000000000 USD                   12,500.00000 XTS              125.0000 USD       2014-06-20T16:40:50   25,000.00000 XTS
    Maximum Short Price: 0.02 USD / XTS     

This took me a long time to wrap my head around, since it's rather confusing and counter intuitive.  For every short position, there is a bookkeeping fiction which I call *equity*, which is what the short and long will receive if the position is settled at some price.  The *feed equity* is the equity settled at the feed, the *match equity* is the equity settled at the price buyer and seller agree on.

- At any price p, the long gets long_equity(p) BTS and the short gets short_equity(p) BTS.
- The network requires that short_equity(p_feed) = 2 * long_equity(p_feed) for new positions.
- The network requires that K * debt = collateral * p_feed for new positions, for some K >= 3.
- Short and long matching at price p_match represents the parties agreeing that each side gets their money back at price p_match.
- Thus, if long contributes x BTS and short contributes y BTS, then long_equity(p_match) = x and short_equity(p_match) = y.

Given these equations:

    long_equity(p) = debt / p
    short_equity(p) = collateral - debt / p
    K * debt = collateral * p_feed
    long_equity(p_match) = x
    short_equity(p_match) = y

We can do some algebra:

    y = short_equity(p_match)
      = collateral - debt / p_match
      = (K * debt / p_feed) - debt / p_match
      = debt * (K / p_feed - 1 / p_match)

    x = long_equity(p_match)
      = debt / p_match

    short_to_long_ratio = y / x
                        = (K / p_feed - 1 / p_match) / (1 / p_match)
                        = K * p_match / p_feed - 1

where `short_to_long_ratio` is the amount of capital contributed by the shorts, and `K` is the collateral-to-debt ratio of the new position.

**Comment by theoreticalbts** [comment]
I think the moral of the above equation from a policy standpoint:

- The long can contribute more and more to capitalize the initial position until a singularity where the entire position is capitalized by the long (hold `K` constant),
- Requiring the new position to have sufficiently low leverage (high `K` value) will eventually "win" against the above effect and allow us to get back to a 2:1 short-to-long contribution ratio (or any other ratio value)

**Comment by theoreticalbts** [comment]
Related:  #1273

**Comment by theoreticalbts** [comment]
I think the right thing to do is require the capital from the short position to be twice the capital from the long position.  This means the short position will be highly deleveraged *at the feed price*, but when the match price isn't equal to the feed price, the feed price doesn't represent the market!

In other words, a short becomes deleveraged when it "wins" against the long.  The price moving from the match price to the feed price will cause the short to "win" and become deleveraged, so setting 2:1 ratio of initial capital means the short has initially the same leverage ratio *against the actual effective market price* no matter whether that effective price is the feed price or an unequal match price.

(For this paragraph, low/high are "flipped" from the internal market.)  If the short side and long side collude (e.g. shorting to yourself), you can use a "revealed short" strategy to bypass the leverage controls:  Short to yourself at the feed, then "reveal" the short by selling the long above the feed.  However the revealed short strategy is of limited usefulness in a market trading at a small bid-ask spread, because you'd have to keep your short above the top-of-book on the other side of the market, otherwise you wouldn't be shorting to yourself.  In other words, the revealed short strategy is actually equivalent to market making (you'd essentially be doing, in sequence, short low, buy low, sell high, then cover at something lower than your last sell order).

If we believe the correct price is the match price determined by buyer and seller, the new USD are 300% collateralized.  If we believe the correct price is the feed price, the new USD are more than 300% collateralized.  Requiring the short to put up any less, you would have to believe either:

- The feed price is the correct price, despite the presence of a willing buyer and seller transacting at a different price
- The collateral backing the newly created BitUSD is less than 300% of its value

Since the first belief goes against free-market philosophy, and the second one is contrary to policy, it's clear that 2:1 ratio at the match price is the correct thing to do.

**Comment by theoreticalbts** [comment]
What it must be doing is the market engine must only taking matching collateral, not 2:1 collateral.

**Comment by bytemaster** [comment]
I think your test is obscuring the issue because the limit price you used is also exactly 50% of the feed price.   Modify the test to use something that is 75% of the feed price and it would have revealed things more clearly. 

Specifically the collateral rate it uses is ALWAYS the feed price.

**Comment by vikramrajkumar** [comment]
@theoreticalbts Please also see the issue described by @pmconrad in this comment: https://github.com/BitShares/bitshares/issues/923#issuecomment-73495730

**Comment by theoreticalbts** [comment]
This is still a problem on main network.  994216f2fe9aa64258c3abf5945c8b769032f3b7 needs to be ported to the bitshares branch and tested.

**Comment by theoreticalbts** [comment]
Fix for this seems to have been merged to BitShares branch at some point, closing.
