### ISSUE TITLE
wallet_market_sell breaking API change

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1355]
The point of `wallet_market_sell` command is not having to care whether your order is placed on the bid or ask side of the market.  For absolute prices, you always use the higher-is-better price (0.02 if your order is converting XTS -> USD, 50 if your order is converting USD -> XTS).

However, currently relative prices do *not* use higher-is-better!  So the API call doesn't meet its purpose and is inconsistent with itself.

This should be fixed, but it is obviously a breaking API change.  Since the command is only live in DVS, breaking API changes should not be too disruptive.  But we want to hold off including `wallet_market_sell` on mainnet until this is fixed.

**Comment by vikramrajkumar** [comment]
@theoreticalbts Do I need to disable this command for BTS 0.6.0? Or is it not necessary since nothing involving relative orders will be made live until 0.7.0 ?

**Comment by theoreticalbts** [comment]
You should either disable it, or incorporate the patch I'm going to have in a few minutes (currently compiling).

**Comment by theoreticalbts** [comment]
On second thought, forget I said that.  The change only affects interpretation of relative order price, so as long as relative orders are disabled, the change won't matter.

**Comment by theoreticalbts** [comment]
On third thought, disable it in 0.6.0 because I still want to tweak the API for regular bid / ask.

**Comment by vikramrajkumar** [comment]
Disabled.

**Comment by vikramrajkumar** [comment]
Relative orders have been abandoned and the command has never been enabled on mainnet (and it is re-enabled in DevShares now); assuming this can be closed.
