### ISSUE TITLE
DVS v0.6.3 can't publish feed from standby delegates any more (?)

### ISSUE THREAD

**Issue by liondani** [BitShares/bitshares#1359]
I tried to publish price feeds with a standby delegate and it's not possible any more with DVS v0.6.3... 

This is the error message I get:

default (unlocked) >>> wallet_publish_feeds delegate.liondani delegate.liondani 0.010128 USD
4 parse_error_exception: Parse Error
Unexpected char '100' in "delegate.liondani"
    {"c":100,"s":"delegate.liondani"}
    th_a  json.cpp:433 variant_from_stream
Error parsing argument 2 of command "wallet_publish_feeds": [{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]
    {"argument_number":2,"command":"wallet_publish_feeds","detail":[{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]}
    th_a  cli.cpp:580 parse_argument_of_known_type

    {"parameter_index":1}
    th_a  cli.cpp:583 parse_argument_of_known_type
Error parsing argument 2 of command "wallet_publish_feeds": [{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}},{"context":{"level":"error","file":"cli.cpp","line":580,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Error parsing argument ${argument_number} of command \"${command}\": ${detail}","data":{"argument_number":2,"command":"wallet_publish_feeds","detail":[{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]}},{"context":{"level":"warn","file":"cli.cpp","line":583,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"","data":{"parameter_index":1}}]
    {"argument_number":2,"command":"wallet_publish_feeds","detail":[{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}},{"context":{"level":"error","file":"cli.cpp","line":580,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Error parsing argument ${argument_number} of command \"${command}\": ${detail}","data":{"argument_number":2,"command":"wallet_publish_feeds","detail":[{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]}},{"context":{"level":"warn","file":"cli.cpp","line":583,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"","data":{"parameter_index":1}}]}
    th_a  cli.cpp:397 parse_recognized_interactive_command

    {}
    th_a  cli.cpp:447 parse_recognized_interactive_command
Error parsing command "wallet_publish_feeds": Parse Error (4)
Unexpected char '100' in "delegate.liondani"
Error parsing argument 2 of command "wallet_publish_feeds": [{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]

Error parsing argument 2 of command "wallet_publish_feeds": [{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}},{"context":{"level":"error","file":"cli.cpp","line":580,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Error parsing argument ${argument_number} of command \"${command}\": ${detail}","data":{"argument_number":2,"command":"wallet_publish_feeds","detail":[{"context":{"level":"error","file":"json.cpp","line":433,"method":"variant_from_stream","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"Unexpected char '${c}' in \"${s}\"","data":{"c":100,"s":"delegate.liondani"}}]}},{"context":{"level":"warn","file":"cli.cpp","line":583,"method":"parse_argument_of_known_type","hostname":"","thread_name":"th_a","timestamp":"2015-02-06T11:32:42"},"format":"","data":{"parameter_index":1}}]

Usage:
wallet_publish_feeds <delegate_account> <symbol_to_price_map>                                         publishes a set of feeds for BitAssets, only active delegates may do this
publishes a set of feeds for BitAssets, only active delegates may do this

Parameters:
  delegate_account (account_name, required): the delegate to publish the price under
  symbol_to_price_map (price_map, required): maps the BitAsset symbol to its price per share

Returns:
  transaction_record

**Comment by vikramrajkumar** [comment]
Look at the spec; you are looking for `wallet_publish_price_feed`.
