### ISSUE TITLE
Optimize memory usage by implementing true database caching

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1361]
I think this will be a post-1.0 thing, there is no milestone for it yet.  Upon reviewing the `cached_level_map` I have figured out that is actually an in-memory mirror of the whole table, not a cache.  I base this conclusion on two factors:

- There is no mechanism to evict existing entries from memory.
- There is no mechanism to read entries that are not already in memory.

The second factor means that if it *isn't* a mirror -- if there is some data on disk that is not in the `_cache` variable -- it would be a major bug that would have caused enough problems to be found and fixed by now.

I propose a two-phase implementation:

- Phase 1, rename to `mirrored_level_map` including all usage sites (mostly in chain database).  This is a blind search/replace change which can be done at any time.

- Phase 2, create a new `cached_level_map` class that *actually* caches a fixed amount of data in memory instead of mirroring the whole table.  The new class should be tested by putting a bogus checkpoint in the config file, syncing up to that checkpoint, then quitting, advancing the bogus checkpoint ~60 days, and restarting.

We should allow user to specify cache size for each table in the config file, so users can tweak to run at max speed on high-RAM machines, or min-footprint on lower-RAM ones.

**Comment by vikramrajkumar** [comment]
Note that LevelDB already implements its own read and write caches, but we have not experimented with tuning them for the various tables.

**Comment by vikramrajkumar** [comment]
Also note that at present, HDD disk seeks seem to be the bottleneck for the vast majority of users, hence the mirroring to RAM whenever possible.

**Comment by vikramrajkumar** [comment]
Abandoning in favor of possibly using the new improved db architecture.
