### ISSUE TITLE
Clicking on [show details] under Bell/Alert UI does nothing in 0.6.0 OSX

### ISSUE THREAD

**Issue by jazy510** [BitShares/bitshares#1364]
The alert / bell icon has a flag next to it, and when clicked I get a drop down menu with the following text:
"(264) [show details]() (February 8, 2015 ...)"

But when I click on the show details link, nothing happens..?

**Comment by vikramrajkumar** [comment]
Possible duplicate of #554 which I thought had been fixed.

**Comment by vikramrajkumar** [comment]
Refer to https://github.com/BitShares/web_wallet/issues/554 instead.
