### ISSUE TITLE
Error trying to relay a transaction and pay a light-weight network fee using a bit asset

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1366]
blockchain_api.cpp blockchain_broadcast_transaction is getting a null feed_price for BitUSD:
```
auto feed_price = _chain_db->get_active_feed_price(fee.asset_id);
fee.asset_id 22
feed_price null
```
I may not have trades or any market activity in the node, but the min number of feed prices were published and the market is live.  I noticed that this is inconsistent with the same node's current_feed_price in market status which is how I was able to calculate the fee to send to the collector:
```
default (unlocked) >>> blockchain_market_status USD XTS
{
  "quote_id": 22,
  "base_id": 0,
  "current_feed_price": 0.01,
  "last_valid_feed_price": 0.01,
  "last_error": null
}
```
error: "Do I look like some kind of charity? You want your transactions sent, you pay like everyone else!"

**Comment by theoreticalbts** [comment]
Did you wait a block after your feed was published?  Can you create a regression_test to reproduce this?

**Comment by jcalfee** [comment]
Is there a good way to change config.json settings on a test?  This happens only if you have a collector and a light_weight fee configured.

**Comment by jcalfee** [comment]
After some re-starts I do see the active feed price now..  I still see a bug related to fee collectors though.  I have to pay a fee that is 10 times higher that what is required to get a transaction to go through.

**Comment by nathanhourt** [comment]
What exactly is the issue here? chain_database is giving back bad data? I'd prefer to let someone who's still familiar with that code fix that one.

If blockchain_broadcast_transaction is miscalculating the fee based on good data, we have an issue, but this has worked in my testing.

**Comment by jcalfee** [comment]
The issue is that I did not set the fee correctly in the config.json.
