### ISSUE TITLE
Completely Refactor Shorting

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1375]
1) Create new operation "issue_bitasset" that specifies an amount in USD and an amount of collateral 
    - this operation will give the creator the requested USD and a corresponding cover order provided that (collateral/3)/usd is greater than the price feed.

2) Remove all relative orders and all short orders and corresponding indexes. 

The end result will be a system with 3 order types:  bid, ask, and cover with cover being triggered by either price, expiration or both.  

When a cover order expires it buys back the USD at the feed price.  
When a cover order is called it buys back USD below the feed at up to a 10% 

This system is SIGNIFICANTLY simpler to implement.  A side effect is that shorts will no longer pay interest and in theory can sell below the feed.   What keeps them honest is the need to buy back AT THE FEED within 30 days.    In the evolution of the current system we originally had shorts that never had to cover which meant selling below the feed could end in a death spiral toward 0.   The 30 day buy back rule was added after the other rules but ultimately makes the other rules unnecessary.  No short will sell too far below the feed unless they think they can exit their position below that price within 30 days.  "Interest" is now "paid" to those who buy below the feed and wait to sell at the feed.

Removing relative orders and the "short wall" makes the system far more resistant to errors in the price feed.   The price feed only needs to update a couple of times per day rather than continuously like it does now.  The price feed only serves the role of judge in extreme situations and keeps everyone honest.

1) It enforces reasonable collateral around 3x.  If the feed is off a little then the initial collateral may be 2.9 or 3.1x but in any event the exact amount of initial collateral is not important.

2) It protects shorts against market manipulation in thin markets that create "fake" margin calls, in practice as BitAsset markets grow the feed will only serve to confirm a price move and not actually trigger the margin call.

3) It keeps shorts honest in the event they refuse to cover within 30 days.  In this case if the feed is wrong then shorts may lose some money by being forced to pay more than necessary to buy back their BitUSD  or  the buy back price may be too low in which case other market participants are the judge on whether or not they want to wait for the next feed update.     Shorts can completely mitigate the risk of being exposed to a feed price that is off by 5 to 10% by covering prior to expiration.

**Comment by bytemaster** [comment]
It has been pointed out that if a short can "short to themselves" to create the USD they need to cover then a short can "stay short" forever provided they keep resetting their collateral levels back to 3x every 30 days.  

The solution to this is to prevent shorting when there are orders below the feed.  This means that shorting will become a "race" to see who can short to themselves and then issue a sell order below the feed first.  

The only way to solve the "race" is to have shorts wait in line prioritized by some metric, such as interest rate.   This is our current system.

The challenge with the current system is that shorts have "limits" and what do we do when a limit has been reached:   Currently we allow matching at the limit price if someone puts a bid there.   This is what complicates our matching algorithm as we are sorting by both limit and interest rate.

It seems to me that we should simply cancel any shorts that are not valid at the feed.  

Conclusion: don't change much about the current system other than canceling shorts that have hit their limit when we come to them in the order matching queue.

**Comment by tonyk2** [comment]
This is wrong. This means you can only short at feed price. If somebody is willing to buy at 105 BTS/bitUSD and the feed is 100 BTS/bitUSD you can not short to them because your short would 'have hit its limit' right away...or you still have to sort by limit first.

**Comment by vikramrajkumar** [comment]
Not happening.
