### ISSUE TITLE
Non-portable data directory

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1376]
- Run 0.5.3 using default `~/.BitShares` data directory
- Shut down 0.5.3
- `cp -Rp ~/.BitShares ~/bts-reindex`
- `bitshares_client-0.6.1 --data-dir ~/bts-reindex`
- Kill it
- `mv ~/bts-reindex ~/.BitShares`
- Run `bitshares_client-0.6.1` with no `--data-dir`
- It insists on reindexing again

There must be an absolute reference to the old data directory name in the config or something.

**Comment by vikramrajkumar** [comment]
Can you confirm if this really still happens with 0.6.2 ? I can't imagine how this could be.

**Comment by vikramrajkumar** [comment]
Cannot reproduce.
