### ISSUE TITLE
blockchain_list_key_balances performance problem

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1379]
On my machine, this runs 1 core at about 100% cpu for 40 seconds.  I noticed the same problem in production.

`blockchain_list_key_balances  DVS8m7DvVkGzhaCc1LmPhBAXndxdsGaz6o6PT6LKJzGFSSbABWZM8`

This server is running with `--statistics-enabled`

**Comment by vikramrajkumar** [comment]
Pushed some optimization; it's unlikely to get much faster than this.

**Comment by jcalfee** [comment]
Awsome!! big difference...  Is it all from going to an unordered map?

**Comment by vikramrajkumar** [comment]
No, also got rid of the redundant conversions to the various address formats for every balance--instead doing the conversions once at the start of the call now.
