### ISSUE TITLE
Bitshares release with listed fixes/features needed for decent gateway experience

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1381]
Fixes for the issues below need to be incorporated into an official bitshares release for a decent test run for gateways (listed in priority order):

Sending to a unregistered key should not use Titan by default
- [x] https://github.com/BitShares/bitshares/issues/1380

Fix fee calculation for UIA transfer
- [x] https://github.com/BitShares/web_wallet/issues/600

Send to public key from GUI without creating a contact (not critical, but very nice to have)
- [x] https://github.com/BitShares/web_wallet/issues/615

Initial display of NAN for UIA transfers on Dashboard page (not critical, but better UX)
- [ ] https://github.com/BitShares/web_wallet/issues/601

**Comment by vikramrajkumar** [comment]
Should be sufficient.
