### ISSUE TITLE
add contact after remove the contact

### ISSUE THREAD

**Issue by janx** [BitShares/bitshares#1382]
Reproduce steps:

1. wallet_add_contact_account foo key12345
2. wallet_remove_contact_account foo key12345
3. wallet_add_contact_account foo key12345, get error:

```
10 assert_exception: Assert Exception
!key_record.valid(): Wallet already contains that key
    {}
    th_a  wallet_db.cpp:393 add_contact_account
```

**Comment by vikramrajkumar** [comment]
Superseded by: #1401
