### ISSUE TITLE
Can we have a "make install"?

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1383]
Sorry my friends but I have absolutely no idea how to pimp cmake files .. but could someone capable of doing so just add a "make install" to the make files to execute this:

    cp programs/qt_wallet/bin/BitShares /usr/local/bin/
    mkdir -p /usr/local/share/icons/
    cp programs/qt_wallet/images/qtapp80.png /usr/local/share/icons/BitShares.png
    cp programs/qt_wallet/BitShares.desktop /usr/local/share/applications/

**Comment by xeroc** [comment]
anyone?

**Comment by VoR0220** [comment]
Let me try learning Cmake and let me see what I can do.

**Comment by vikramrajkumar** [comment]
Too low priority; closing for the same reason as: #1378
