### ISSUE TITLE
Switching over to new use 'signing_keys' failed!!

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1384]
Hey there,

I wanted to test the separated signing_key feature in the hopes that I can store the owner keys somewhere safe. Theses are the steps I performed:

* Create new privkey/pubkey pair
* wallet_delegate_update_signing_key on the delegate's account with the new pubkey
* closing wallet
* create new wallet
* import new privkey (worked like a charm)
* enable block production

the result was that I missed my blocks .. To fix it, I had to go back to my original wallet and import the new privkeys.

What am I doing wrong?

**Comment by vikramrajkumar** [comment]
@xeroc There is a 1 block transition period where you need to have both the previous signing key and the new signing key in the same wallet, so that you can correctly reveal the previous block secret with the old key while simultaneously committing to a new secret hash with the new key.

**Comment by xeroc** [comment]
Ah .. makes sense to me now .. gonna change my script and give it another try soon .. 

Reporting back

**Comment by xeroc** [comment]
working flawlessly .. thanks!
