### ISSUE TITLE
Expose the random user/password in the advanced GUI settings

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1389]
Hey friends,

would it be possible to have the http user/pwd for the GUI exposed somewhere in the GUI?
I know this might require to add yet another api call to not only have it set but also "get" both ..
but I think the advanced user will profit from this:

https://bitsharestalk.org/index.php?topic=8390.msg186908#msg186908

**Comment by nathanhourt** [comment]
Using the Qt wallet as an RPC server would best be categorized as Worst Practice, and it's not something we plan to support.

**Comment by xeroc** [comment]
how about having 3rd party apps running that want to interface with the client?

Think of a 3th party bot that does not want to reveal the trading engine but wants to offer trades on the BTS blockchain. So you can juts give that 3rd party app access to your client (maybe restricted access) and let the 3rd party bot run on bts ..

Wouldn't it be nice to have an open interface to be able to link any kind of software into BTS?

What would be the alternative approach to satisfy those needs?

**Comment by nathanhourt** [comment]
If you're setting up servers and infrastructure, you should be running a CLI node with a dedicated RPC interface. I am not aware of any use case where a GUI is better for this. The fact that the GUI uses the RPC interface is an implementation detail, and may not continue to be used indefinitely, though I am not aware of any plans to fix this in the short term.

**Comment by xeroc** [comment]
*understood* .. makes sense .. and my use case will certainly just disappear with the light wallets becoming able to do market transactions ..

sorry for taking your time
