### ISSUE TITLE
[Both desktop clients] OS X 10.6.8 crashes on launch

### ISSUE THREAD

**Issue by robrigo** [BitShares/bitshares#1397]
Crash report: http://i.imgur.com/R0o8sNn.png

Forum post: https://bitsharestalk.org/index.php?topic=14466.0

This problem has been latent for a while; any idea why older versions of OS X have trouble with the client?

**Comment by vikramrajkumar** [comment]
No idea, and we are unlikely to be able to troubleshoot this for the foreseeable future. Do you know what is the lowest version that is reported to work? We should probably start defining some system requirements.

**Comment by vikramrajkumar** [comment]
Have to close this; it's been a known issue for a while and we don't have the resources to try to figure this out at this time.
