### ISSUE TITLE
UI enhancement request: Indicate completed orders in Account Orders History

### ISSUE THREAD

**Issue by jazy510** [BitShares/bitshares#1404]
Currently, in the Account Orders History UI, there is a listing of the orders made, both completed and unfulfilled.  It would be helpful to visually indicate which orders there have be filled/completed, and which are still Open. (display completed ones with a green or orange font, perhaps?)

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/629
