### ISSUE TITLE
Document the implementation's general structure

### ISSUE THREAD

**Issue by VoR0220** [BitShares/bitshares#1405]
https://bitsharestalk.org/index.php?topic=14493.msg189204#msg189204

I'd be up to the task of documenting everything if nobody has the time to do so. I need to learn the code any way, so I figure why not make it easier for others?

**Comment by VoR0220** [comment]
@vikramrajkumar What would the documentation standards be? Where should I document this?

**Comment by vikramrajkumar** [comment]
General descriptions on the categories of the files is probably a good start. Some very broad categories: https://github.com/BitShares/bitshares/blob/beb1cb226616f58cde05d873f764a8daf11806d1/libraries/blockchain/CMakeLists.txt#L26-L68 Then we can get more specific about some of the more important parts (`chain_database`, `pending_chain_state`, etc.) Eventually we can get into subsections of the different files.

If you ask questions here I can give you guidance; I just don't want to have to sit down and try to write the whole thing in one go.

Some kind of Markdown file like the existing README is probably sufficient for now.

**Comment by VoR0220** [comment]
Alright. So I'll go ahead and start making a README file for the blockchain libraries with a broad overview of what those specific parts are doing. Might take a couple of days though. I'll refer to you here if I have questions.

**Comment by vikramrajkumar** [comment]
> Am I inferring correctly in thinking that I should be writing in broad categories on the specifics by which they are separated?

Yeah high-level descriptions of the different types of classes, then we can proceed to get more specific.

**Comment by VoR0220** [comment]
So the assets class is handling the assets price and describing the templates for ways in which all assets will be created, and the .cpp file is the execution of the asset object. Is my understanding correct? Would this be a good sentence to fit a high level description?

**Comment by VoR0220** [comment]
In addition to establishing the relationship between asset and BTS by establishing a price that makes up the asset and in doing that, establishing the collateral function.

**Comment by VoR0220** [comment]
Quick question regarding types and the fc class. What is ripemd160? I see that it has something to do with hashing, but what is it exactly as an object?

**Comment by vikramrajkumar** [comment]
BitShares supports multiple assets compared to Bitcoin which only supports one. And the base asset 0 is special because it is used for DPOS among other things. Prices and collateral use assets but assets do not use prices or collateral. The `asset` class is what is used to represent an asset in our implementation.

`ripemd160` is just a class that represents a ripemd160 hash.

**Comment by VoR0220** [comment]
The base asset 0 is used for DPOS? As in it specifies the delegates as an asset?

**Comment by vikramrajkumar** [comment]
Asset 0 is what is used for voting, and delegates are paid in asset 0 for example.

**Comment by VoR0220** [comment]
Ahhhhh....so Asset 0 would be our bitshares, which give us the ability to vote, and asset 0 goes to the delegates? Am I in the ball park?

**Comment by vikramrajkumar** [comment]
Yes

**Comment by VoR0220** [comment]
No I see. Asset 0 is our votes. Correct?

**Comment by VoR0220** [comment]
Wait. I think I understand. So the asset 0 is our vote which is derived in price BTS?

**Comment by vikramrajkumar** [comment]
In the BitShares network, asset 0 is BTS which also happens to be used to vote for delegates as part of DPOS.

Prices are part of the market and represent a ratio between two different assets.

**Comment by VoR0220** [comment]
Alright. Awesome. Think I got that part down. The FC code (particularly in types) looks a bit confusing but am I correct in assuming that these are custom byte lengths of the variable types?

**Comment by VoR0220** [comment]
Question just occurred to me. Does this mean I can use my assets to vote for delegates?

**Comment by vikramrajkumar** [comment]
You can use asset 0.

**Comment by VoR0220** [comment]
Okay so we cannot use assets outside of asset 0. That's clear to me now. Just got curious. 

Okay. I'm seeing something in types that I do remember. There is the security status that is located in types. But why does the security state belong with the public key type? What is the struct binary key doing? What do the fc functions to_variant and from_variant do?

**Comment by vikramrajkumar** [comment]
> But why does the security state belong with the public key type?

They just happen to be in the same file.

> What is the struct binary key doing?

I don't know.

> What do the fc functions to_variant and from_variant do? 

A custom conversion to and from the `fc::variant` type https://en.wikipedia.org/wiki/Tagged_union

**Comment by VoR0220** [comment]
Lol alright. Interesting stuff. They never taught us about Tagged Unions in school. Will have to do more research on that later. Moving onto address. Reading address this seems to be a bit simpler. It handles the creation and checking for validity of public key addresses, correct?

**Comment by vikramrajkumar** [comment]
An address is ultimately a hash of a public key. Same as in bitcoin.

**Comment by VoR0220** [comment]
Alright. I've been reading the extended address code. Does this handle TITAN? This code seems a little more confusing.

**Comment by vikramrajkumar** [comment]
Extended addresses are used for child key derivation as defined in Bitcoin BIP32 https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki. In reality they may or may not match the specification.

These child keys are indeed what is used for TITAN stealth addresses, but that feature is an implementation detail of the wallet.

**Comment by VoR0220** [comment]
Ahhhhh....so essentially what it is doing is using the original private key and original public key in a parent process to hash out a new private and public key in a child.

**Comment by VoR0220** [comment]
In transaction_creation_state, this is essentially handling all of the changes to the block chain, am I correct?

**Comment by vikramrajkumar** [comment]
`transaction_creation_state` is only to help construct new transactions. Only the light wallet is using it at present. The blockchain does not use it.

**Comment by vikramrajkumar** [comment]
> Ahhhhh....so essentially what it is doing is using the original private key and original public key in a parent process to hash out a new private and public key in a child.

Processes are not relevant to any of this.

**Comment by VoR0220** [comment]
Sorry...I should have said "parent key". Interesting bit on transaction_creation_state. What does the normal wallet use to construct new transactions in the block chain?

**Comment by vikramrajkumar** [comment]
MUSIC and PLAY have already figured the current code out.. unlikely to be too worthwhile if we are able to move to the new db architecture BM has been researching.
