### ISSUE TITLE
LW: Cannot pay fees for UIA transfer

### ISSUE THREAD

**Issue by clayop** [BitShares/bitshares#1407]
I have enough fee (about 10 BTS) for UIA transfer, but when I tried to send UIA, the message says I currently do not have enough fee.

http://imgur.com/Srv6Zdy,RLCkAZz#0
http://imgur.com/Srv6Zdy,RLCkAZz#1

Plus, it shows 500, instead of 500,000

**Comment by nathanhourt** [comment]
@clayop Is this in a locale which uses commas as a decimal point?

**Comment by clayop** [comment]
@nathanhourt Probably. Using Windows 7 64bit Korean.

**Comment by nathanhourt** [comment]
@clayop I cannot reproduce your number formatting issue using either decimal point type. Either way it works correctly on my end. Can you send some TOURCOIN to lightclient so I can try it with that particular asset? I can send it back when I'm done.

Thanks.

**Comment by nathanhourt** [comment]
Nevermind, I found it. It's a problem with assets having zero digits of precision. :)

**Comment by vikramrajkumar** [comment]
@nathanhourt You mean an asset precision value of 1 in the backend right? This should have no digits after the decimal point. We don't have any assets with a precision value of 0 do we?

**Comment by nathanhourt** [comment]
@vikramrajkumar Correct. The precision number is 1, so digits of precision is clog(1) = 0. See http://bitsharesblocks.com/asset/info?asset=TOURCOIN
