### ISSUE TITLE
0.6.2 memory leak

### ISSUE THREAD

**Issue by wackou** [BitShares/bitshares#1410]
it seem like that 0.6.2 has a memory leak somewhere, here's the RAM usage of my seed node for the last day (had to restart it before it went swapping):
![screen shot 2015-02-27 at 21 39 58](https://cloud.githubusercontent.com/assets/15667/6420778/9c0a46cc-bec9-11e4-953e-913bc4fdaae1.png)

And here's for my delegate node, less pronounced, although still present.
![screen shot 2015-02-27 at 21 40 09](https://cloud.githubusercontent.com/assets/15667/6420785/ad8bd622-bec9-11e4-8f5d-c4f8fb47ab3f.png)

(note: my delegate seems to have a really low CPU usage, not too sure why, that's new also. Maybe a problem with my tools)

**Comment by VoR0220** [comment]
...could it be from all the unsigned ints that are paraded throughout the code?

**Comment by sidhujag** [comment]
Can use valgrind to detect the leaks

**Comment by bytemaster** [comment]
We use shared_ptr or unique_pointers for almost everything.

**Comment by wackou** [comment]
there might be a cycle, then, with some shared_ptr. This looks like it might be in the network code somewhere, as my seed node leaks much faster than my delegate, and the seed node doesn't even have a wallet open... I'm also very confident that this was introduced between 0.6.1 and 0.6.2, if it helps tracking it down.

I tried to run it in valgrind, too, but my VPS is not hefty enough for that and the binary is not very valgrind-clean, so I couldn't get any useful info out of it...

**Comment by vikramrajkumar** [comment]
> I'm also very confident that this was introduced between 0.6.1 and 0.6.2

Interesting.. @emfrias could there be a problem with the recent network fix? https://github.com/BitShares/bitshares/commit/7ca1cfa233da42ccf2d4eeecda8b6a16a7726721

**Comment by vikramrajkumar** [comment]
Will assume fixed by https://github.com/BitShares/bitshares/commit/ca0b39c31537b17ee547127e27bac23734854822 unless we see otherwise.
