### ISSUE TITLE
importing an old wallet seems to not regenerate the active_key

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1413]
https://bitsharestalk.org/index.php?topic=14607.0;all

Are active keys derived from the owner key?
Is there a call to force the client regenerate the active key?

**Comment by lastagile** [comment]
Hi Vikram. is there a way to manually add the active key back?

**Comment by vikramrajkumar** [comment]
Another: https://bitsharestalk.org/index.php?topic=14603.msg189813#msg189813
