### ISSUE TITLE
0.6.2，non-tian account ，use  blockchain_get_account_public_balance can't get the correct result

### ISSUE THREAD

**Issue by CurrencyMaster** [BitShares/bitshares#1420]
The first deposit ,can get the correct result. The second and the third deposit ,then can't get the correct result,why?

**Comment by abitmore** [comment]
Here is a TODO: https://github.com/BitShares/bitshares/blob/develop/libraries/wallet/transaction_builder.cpp#L299 

but no similar logic in transaction_builder::deposit_asset() :
https://github.com/BitShares/bitshares/blob/develop/libraries/wallet/transaction_builder.cpp#L198
