### ISSUE TITLE
RPC whitelist file (only RPC commands in this file can run)

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1421]

**Comment by vikramrajkumar** [comment]
For reference: @wackou's RPC proxy: https://bitsharestalk.org/index.php?topic=13143.msg172159#msg172159

**Comment by jcalfee** [comment]
Not needed at the moment...

**Comment by vikramrajkumar** [comment]
Still a good feature; will keep open for now.

**Comment by jcalfee** [comment]
I agree.  Even if a proxy is used, this would be a good secondary safety measure.  I have a few thoughts:

Implementation should consider that a whitelist is a security feature so an error reading a specified whitelist file should prevent the rpc/json ports from opening.

Any unrecognized command in the whitelist file should probably trigger a warning.

Nice to have: alias support in first or both: rpc/json commands, whitelist file.
Nice to have: apply whitelist filter to help, meta_help

**Comment by jcalfee** [comment]
Also valuable to see a warning on any attempt to run a command that is not whitelisted.

**Comment by pmconrad** [comment]
My patch adds whitelisting to the http-rpc and json-rpc (encrypted and plain) interfaces. Whitelisting a commands also allows all aliases. An empty whitelist means allow-all (compatible with current default).

Comments anyone? Especially regarding the removal of commands added through register_common_api_methods, which I'm not really happy with.

**Comment by jcalfee** [comment]
Removal looks fine to me since your generically checking the methods (the list can't fall out of sync).  I would save the results of the removal statically so it does not happen on every request (if you don't already).

**Comment by pmconrad** [comment]
The removal happens once per json-rpc connection, just like the commands are added once after the connection is accepted. For http-rpc, the whitelist is added once when the server starts.
