### ISSUE TITLE
Armory Balance

### ISSUE THREAD

**Issue by BitcoinUser444** [BitShares/bitshares#1433]
I have a problem with a transaction placed on expresscoin. i typed in the correct address and my order was completed today, but i checked on my live armory watch only copy and there is still a balance of $0. I have went to other sites like blockchain and they all show that this address has $108 in it. Is there a certain amount of time, or something else i have to do to show my funds, and to be able to use them?

**Comment by vikramrajkumar** [comment]
I don't know what expresscoin is nor is BitShares related to Armory in any way.
