### ISSUE TITLE
Issue on Client 0.6.2

### ISSUE THREAD

**Issue by ylytdeng** [BitShares/bitshares#1434]
When we use rpc to call command wallet_account_transaction_history. it have a probability not call scan. For avoiding this problem, we have to call scan again, but sometime it will run scan two times and it take too much resource.

we will run a script to get the information of last 180 block transaction. this script need call client API. but the client always crash at this point.

**Comment by xeroc** [comment]
when you unlock the wallet, the client will catch up with blocks since the last unlock automatically ..
maybe you check the "wallet_scan_progress" attribute to be 100% before you try to get the history
or maybe unlock the wallet for a short period of time regularily ..

**Comment by vikramrajkumar** [comment]
@ylytdeng Please see my comments here: https://bitsharestalk.org/index.php?topic=14614.msg189957#msg189957 and let me know if that helps.

**Comment by ylytdeng** [comment]
thanks, it works
