### ISSUE TITLE
after sending to some account, this account is added to wallet's accounts (wallet_list_account shows it in the list)

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1435]
I'm working on 0.7 GUI support and stumbled upon this issue. My toolkit's version is "dryrun-18-2187-g448bf8e-testnet-84".
If you want to replicate this, just run any acceptance test, pause it after scenario, e.g.
> cucumber -t @current
When it stops, press 'a' and enter the following command in the console:
→ transfer 111 XTS alice bob
Now if you list account you will see 'bob' in the list:
→ wallet_list_accounts

**Comment by abitmore** [comment]
Possible related:
https://bitsharestalk.org/index.php/topic,15900.msg204349.html#msg204349
https://bitsharestalk.org/index.php/topic,15900.msg204350.html#msg204350
http://i.imgur.com/BjG9mJe.png
After vote, the account added to account list.
