### ISSUE TITLE
Maximum APR on shorts is higher than it should be

### ISSUE THREAD

**Issue by pmconrad** [BitShares/bitshares#1438]
Max APR is supposed to be 1000%, but in reality it is >18000%, see http://bitsharesblocks.com/blocks/block?id=2018800 .

The reason is that the actual APR is checked against this value (wallet_impl::apply_order_to_builder in wallet.cpp):
static fc::uint128 max_apr = fc::uint128( 1000, 0 );
and this (short_operation::evaluate in market_operations.cpp):
fc::uint128( 10, 0 )

The actual APR is represented as a fixed point decimal scaled with FC_REAL128_PRECISION == 10^18 but the check value is scaled with 2^64.

This is actually somewhat dangerous, because at 18000% interest rate the principal plus interest exceeds the collateral value after only a couple of days.

Working on a partial fix.

**Comment by bytemaster** [comment]
Lets set the max interest rate to 50% APR.

**Comment by abitmore** [comment]
Those orders are placed in order to protect expired short positions (by 3rd party). See https://github.com/BitShares/bitshares/issues/1315#issuecomment-79949960 . Please fix that issue first.

**Comment by abitmore** [comment]
@pmconrad @bytemaster see this line: https://github.com/BitShares/bitshares/blob/9a73ebfec644ab81d2820c18f953368996f175df/libraries/blockchain/market_operations.cpp#L135

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/b5afb82ebaeeea3b5d5cd77af47226cecf8b389f
