### ISSUE TITLE
Enhancement to RPC request path (allows for useful logging and benchmarking)

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1441]
It would be helpful for logging and performance monitoring if an optional path prefix could be added to /rpc (like:  /rpc/blockchain_get_account).   Standard requests to "/rpc" would still work as this method name is in the header.  Also, if a request came in for /rpc/blockchain_get_account and the method header was added too (redundant) the request should be rejected..

It will better help the tracking of IP address to type of RPC request being made.  Currently it is not known which method is being called without logging headers.  A load balancer (like amazon) will benchmark and log URLs but has no knowledge of payload.  This feature would enable better logging and enable benchmarks at a low cost to a system admin.

**Comment by xeroc** [comment]
It would also make CDN/proxying easier, wouldn't it?

**Comment by jcalfee** [comment]
RPC is potentially the entire block-chain so it does not lend it self to caching very well.  We are luck to have local storage in JavaScript so that is already aware of the parameters in the RPC call and can cash there.

**Comment by jcalfee** [comment]
I think I can make this even easier.  If the path after /rpc has anything in it (like /rpc/blockchain_get_account), just validate it against the RPC request (check to see if the method or batch method matches the URL).  This would prevent someone trying to disguise there request and hide in the logs.  The code processing the request does not change, it just always uses the standard way.
