### ISSUE TITLE
Accurate cost for covering a short

### ISSUE THREAD

**Issue by abitmore** [BitShares/bitshares#1450]
1. What does the `COST` column mean for a `cover_order` in `wallet_market_order_list` command?

2. I think the cost for covering an order via GUI is some higher than how much it actually need. Traders always want maximum profit and minimum loss. Is there a command/API to show how much exact interest need to pay for covering a specific short order now, or covering at a specified time/block_number?

**Comment by pmconrad** [comment]
Related to #1345 
The wallet will automatically cut down the cover amount if it exceeds principal + interest when the cover transaction is created: https://github.com/BitShares/bitshares/blob/master/libraries/wallet/transaction_builder.cpp#L644

**Comment by abitmore** [comment]
I finally figured out .. the 2nd issue is fixed in this commit:  https://github.com/BitShares/bitshares/commit/fa18f01aeec7f7be36c0bce200bbb962e4064bc6#diff-4bcca2f3abbcb15b2f74e9ed807bf9da . But I am still using v0.6.1 :( Have to upgrade.
