### ISSUE TITLE
short order  should match  at  which is higher between Price Limit  & Call Price（when BTS per BitUSD@default）

### ISSUE THREAD

**Issue by todasun** [BitShares/bitshares#1451]
![qq 20150317201641](https://cloud.githubusercontent.com/assets/10720816/6687130/af796392-cce2-11e4-8077-f1fd0acdd161.png)

short bitUSD  when  higher price of bitUSD  is more safe
so

Price Limit   (BTS per BitUSD)  vs  Call Price
short order  should match  at  which is higher between Price Limit  & Call Price
eg:Call Price 110    Price Limit  120   not match
when  Call Price 130    Price Limit  120   math 130

=======================
![bitusd bts](https://cloud.githubusercontent.com/assets/10720816/6687274/6d492e92-cce4-11e4-8838-fcd5a2111af5.png)

BitUSD per BTS
short order  should match  at  which is low  between Price Limit  & Call Price

**Comment by vikramrajkumar** [comment]
@valzav, I think this is saying that the description needs to be flipped when the market is flipped?

**Comment by valzav** [comment]
@vikramrajkumar yes, I think this is just a GUI issue, I'll check this out

**Comment by todasun** [comment]
i made some Commits  yesterday .

**Comment by todasun** [comment]
@valzav  please check it

**Comment by valzav** [comment]
@todasun, I've merged your pull request - it looked good to me
