### ISSUE TITLE
acceptance tests are broken: invalid asset amount in wallet_transfer (develop branch)

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1453]
E.g. cucumber if you run "cucumber features/basic_transfer.feature", 
wallet_transfer 1000.0 XTS angel alice
will result in the following error:
{"detail": "35005 invalid_asset_amount: invalid asset amount\n\n    {\"share_string\":\"1000.000000000000\",\"max_rhs_size\":5}\n    th_a  asset_record.cpp:75 share_string_to_satoshi\n\n    {\"share_string\":\"1000.000000000000\",\"precision\":100000}\n    th_a  asset_record.cpp:91 share_string_to_satoshi\n\n    {\"amount\":\"1000.000000000000\"}\n    th_a  asset_record.cpp:96 asset_from_string\n\n    {\"amount\":\"1000.000000000000\",\"symbol\":\"XTS\"}\n    th_a  chain_interface.cpp:228 to_ugly_asset\n\n    {\"amount_to_transfer\":\"1000.000000000000\",\"asset_symbol\":\"XTS\",\"from_account_name\":\"angel\",\"recipient\":\"alice\",\"memo_message\":\"\",\"strategy\":\"vote_recommended\"}\n    th_a  wallet_api.cpp:322 wallet_transfer\n\n    {}\n    th_a  common_api_client.cpp:3784 wallet_transfer",

Wallet's balances prior wallet_transfer command:
angel                           47,474,999.50000 XTS

**Comment by vikramrajkumar** [comment]
For some reason it looks like the command starts off as `wallet_transfer 1000.000000000000` and that is invalid as it has too many decimals. Perhaps some conversion to float/double and printing it is involved?

**Comment by abitmore** [comment]
Maybe related: https://github.com/BitShares/bitshares/issues/1440

**Comment by valzav** [comment]
@vikramrajkumar you are right, this is client side issue. It's fixed

**Comment by HackFisher** [comment]
This fix will cause json(variant) objects like 
```
{"from_account_name"=>"bob", "amount"=>10.0, "odds"=>2, "guess"=>1}
```
be casted to string before to_json and before sending to rpc server, and the rpc server will not receive the right variant

**Comment by HackFisher** [comment]
I'm guessing that the root cause is that the type in the api of 
```
std::string& amount_to_transfer
```
already be changed to string, but in the client side still pass the numbers to it. The problem shows up when converting numbers to string in the server side.

**Comment by vikramrajkumar** [comment]
@HackFisher Does the above fix by @valzav look okay to you?

**Comment by HackFisher** [comment]
@vikramrajkumar yes, it looks okay for me, resolved now.
