### ISSUE TITLE
market.feature's short price limit test is failing (second one)

### ISSUE THREAD

**Issue by valzav** [BitShares/bitshares#1455]
in order to replicate this, run this scenario "Scenario: Alice shorts BitUSD with price limit, price feed moves short executes, Bob is able to sell 10 USD paying fee in USD"
and place @current @pause tags above the scenario, then run it with this command:
> cucumber -t @current
after it fails use console to examine the order -  there would be two orders: alice's short and bob's ask at 0.01 USD/XTS that used to match with old market engine.

**Comment by theoreticalbts** [comment]
I can't reproduce this.  I'm wondering if your framework's block waiting logic is exactly correct.  If it is racy that might be a problem.

Also, if you could get an exact list of commands issued, that would help

**Comment by valzav** [comment]
here is an excerpt from the log file:
I, [2015-03-18T11:30:49.824516 #81793]  INFO -- : [delegate] request: wallet_delegate_set_block_production ALL true
I, [2015-03-18T11:30:49.843397 #81793]  INFO -- : [delegate] request: wallet_backup_create tmp/delegate_wallet_backup.json
I, [2015-03-18T11:30:49.883397 #81793]  INFO -- : [alice] request: wallet_import_private_key 5JqPYA6KJvJM9XQDKGJCHTmzBDdNDCzkKBDXWJbexHqxuVJwR2S angel true true
I, [2015-03-18T11:30:49.892496 #81793]  INFO -- : [alice] request: wallet_backup_create tmp/alice_wallet_backup.json
I, [2015-03-18T11:30:49.897081 #81793]  INFO -- : [bob] request: wallet_import_private_key 5JE95D9duVVbcSyZ2N6FM74httNaRNZpDFdi7LDyAbFFntd4zVF angel true true
I, [2015-03-18T11:30:49.905715 #81793]  INFO -- : [bob] request: wallet_backup_create tmp/bob_wallet_backup.json
I, [2015-03-18T11:30:49.909708 #81793]  INFO -- : [alice] request: wallet_account_create alice
I, [2015-03-18T11:30:49.916801 #81793]  INFO -- : [alice] request: wallet_account_register alice angel
I, [2015-03-18T11:30:49.925669 #81793]  INFO -- : [bob] request: wallet_account_create bob
I, [2015-03-18T11:30:49.934272 #81793]  INFO -- : [bob] request: wallet_account_register bob angel
I, [2015-03-18T11:30:49.942349 #81793]  INFO -- : [alice] request: info 
I, [2015-03-18T11:30:50.952449 #81793]  INFO -- : [alice] request: info 
...
I, [2015-03-18T11:30:55.252071 #81793]  INFO -- : [delegate] request: wallet_publish_price_feed delegate100 0.02 USD
I, [2015-03-18T11:31:01.349913 #81793]  INFO -- : [alice] request: wallet_transfer 100000.0 XTS angel alice
I, [2015-03-18T11:31:01.367826 #81793]  INFO -- : [bob] request: wallet_transfer 40001.0 XTS angel bob
I, [2015-03-18T11:31:10.468171 #81793]  INFO -- : [alice] request: wallet_market_submit_short alice 10000.0 XTS 10 USD 0.01
I, [2015-03-18T11:31:10.486051 #81793]  INFO -- : [bob] request: wallet_market_submit_ask bob 20000.0 XTS 0.02 USD
...
I, [2015-03-18T11:31:22.733095 #81793]  INFO -- : [delegate] request: wallet_publish_price_feed delegate100 0.01 USD
I, [2015-03-18T11:31:30.840283 #81793]  INFO -- : [bob] request: wallet_market_submit_ask bob 20000.0 XTS 0.01 USD

**Comment by theoreticalbts** [comment]
Fixed.
