### ISSUE TITLE
0.7.0 bug again, can't send to subaccount

### ISSUE THREAD

**Issue by CurrencyMaster** [BitShares/bitshares#1458]
![4 vmef1cbcw_ z5z w9t](https://cloud.githubusercontent.com/assets/883593/6711071/c6e91c24-cdbf-11e4-8d23-6b96ec12c8d5.png)

**Comment by theoreticalbts** [comment]
Possibly https://github.com/BitShares/web_wallet/issues/639 ?

**Comment by vikramrajkumar** [comment]
@valzav Yes duplicate https://github.com/BitShares/web_wallet/issues/639. 0.7.0 used current web_wallet master branch
