### ISSUE TITLE
Potentially incorrect matching in block 2059269

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1459]
`btswildpig` has brought to our attention a potential market matching issue demonstrated in block 2059269.

**Comment by btswildpig** [comment]
![image](https://cloud.githubusercontent.com/assets/9744912/6712895/1637e076-cdca-11e4-8197-9d8e76698165.png)
This was the original short order with 100K BTS collateral (Now the collateral is decreased 0.83604 because partially filled today , look at the next photo  )  

![image](https://cloud.githubusercontent.com/assets/9744912/6712959/79a0efae-cdca-11e4-8a2e-6defaca64f8c.png)

it filled at odd price (first 3 in the history ) 
the block number is 2059269   .

And the guy finally used 0.0035 USD to cover this partial short order and get 29 BTS in return . (no photo about it at this point  ) .

**Comment by theoreticalbts** [comment]
The issue where the short is matched despite not being at the top of the book should be fixed with the upcoming hardfork.

I think the strange price is legit.  It seems to be due to the ask orders specifying a very low price:

    >>> blockchain_market_order_book USD BTS
         BIDS (* Short, + Relative, - Relative Limit)                            |                                   ASKS                                  
    TOTAL                     QUANTITY                                     PRICE | PRICE                                        QUANTITY                     TOTAL   COLLATERAL
    -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    16.9999 USD               2,091.32769 BTS                 0.008128759551 USD | 0.000125500000 USD                       10.00000 BTS                0.0012 USD
    2.2391 USD                275.96907 BTS                   0.008113590264 USD | 0.000125600000 USD                       11.00000 BTS                0.0013 USD
    100.0000 USD              12,324.99999 BTS                0.008113590264 USD | 0.008130000000 USD                       21.68218 BTS                0.1762 USD
    1,934.9218 USD            238,962.85227 BTS               0.008097165992 USD*| 0.008403361345 USD                    2,022.98810 BTS               16.9999 USD

There is another more subtle matching issue here as well, it is known and a fix for it has been developed and is currently being tested.

I will double check the numbers on this, will close the ticket once I do that and have a reference to the ticket for the other issue.

**Comment by pmconrad** [comment]
See also the last 4 comments in #1277

**Comment by vikramrajkumar** [comment]
I believe this was fixed by https://github.com/BitShares/bitshares/commit/0f34cb33fb428b65c96d72cb54e3f67d68ff633b and/or https://github.com/BitShares/bitshares/commit/371343cd19c4d3a9d9a9b483b46cdda434ab8209, which have since been backported to `develop`.
