### ISSUE TITLE
Issue in bts/0.7.0 about market engine

### ISSUE THREAD

**Issue by abitmore** [BitShares/bitshares#1464]
Core developers please check your forum message.
@bytemaster @vikramrajkumar @theoreticalbts @nmushegian @pmconrad

**Comment by pmconrad** [comment]
The behaviour you describe is essentially the same as in 0.6.2. The difference is that shorts with a low limit are no longer preferred over bids with a higher limit.

Also, if I read the code correctly the alleged liquidity problem only exists for expiring covers. Normal asks should still match shorts with a high limit even if other shorts with lower limit but higher interest exist.

**Comment by abitmore** [comment]
@vikramrajkumar some questions:

* https://github.com/BitShares/bitshares/blob/b97f25a47d10715fb5dfff7130c41978d591639a/libraries/blockchain/market_engine_v7.cpp
 * Why initiate _shorts_at_feed and _short_limit_index from chain_db directly in execute(), but get short orders from _pending_state in get_next_short_v065()? Will this trigger some inconsistent-state issues?
 * In what condition will this return false? https://github.com/BitShares/bitshares/blob/b97f25a47d10715fb5dfff7130c41978d591639a/libraries/blockchain/market_engine_v7.cpp#L718 . In case of it returned false, is it better to get next short at feed_price rather than end the function? Same question for https://github.com/BitShares/bitshares/blob/b97f25a47d10715fb5dfff7130c41978d591639a/libraries/blockchain/market_engine_v7.cpp#L735 .

**Comment by vikramrajkumar** [comment]
Good work @abitmore, based on your comments I've simplified the patch in the above commit.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/compare/480b4ec1df...1a71a01b0f
