### ISSUE TITLE
On Linux mint, bts client, File > Check for Updates broken

### ISSUE THREAD

**Issue by kenCode-de** [BitShares/bitshares#1466]
Please fix this so we can finally update our software and I never have to come back to github just for an update, uninstalling, reinstalling, come on please

**Comment by xeroc** [comment]
... or at least rename it to 
  Upgrade GUI / check for network upgrades

BTW. my CLI client tells peers that they have to upgrade and the block number of the hardfork .. why can't I see this data in the GUI/web_wallet?

**Comment by vikramrajkumar** [comment]
Refer to https://github.com/BitShares/qt_wallet/issues/106 instead.
