### ISSUE TITLE
Please add 2FA ability, in bts client; qr code google authenticator, etc.

### ISSUE THREAD

**Issue by kenCode-de** [BitShares/bitshares#1468]
I'd love to see it in Moonstone and the wallet.bitshares.org site as well, please :) 
https://github.com/google/google-authenticator/

**Comment by xeroc** [comment]
https://bitsharestalk.org/index.php?topic=7575.0

**Comment by kenCode-de** [comment]
Taulant at Moonstone says v1 will not have 2FA. he says v2 will have 2FA 4 months later. 
Now, wallet.bitshares.org.. Can we get 2FA into that one asap? Security is imperative to mass adoption.

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/BitShares-JS/issues/75
