### ISSUE TITLE
No Order history&K chart in BDR.AAPL : BitCNY market

### ISSUE THREAD

**Issue by abitmore** [BitShares/bitshares#1471]
https://bitsharestalk.org/index.php?topic=15132.0

**Comment by vikramrajkumar** [comment]
Possibly related: #1300

**Comment by abitmore** [comment]
I think it's better to record volumes of both assets rather than to record asset 0 only. Any thoughts?

**Comment by vikramrajkumar** [comment]
I agree.

**Comment by abitmore** [comment]
Please check pull request https://github.com/BitShares/bitshares/pull/1476

Note: returned structure of `blockchain_market_price_history` API changed, `volume` renamed to `base_volume`, and a new `quote_volume` added.

**Comment by abitmore** [comment]
I wonder if it's better to not rename `volume` in the API for backward compatibility.

**Comment by vikramrajkumar** [comment]
I think it is probably okay. I will review your PR when I get a chance.

**Comment by abitmore** [comment]
@vikramrajkumar need to back-port to older versions of market_engine, or not?

**Comment by vikramrajkumar** [comment]
Already done as part of: https://github.com/BitShares/bitshares/commit/739a858d6ff7a25674a4bdf0ceb40472097e3540
