### ISSUE TITLE
 Real-time display total destruction and limit amount of bts

### ISSUE THREAD

**Issue by todasun** [BitShares/bitshares#1472]
About total confusion, suggest to publish a BTS total "inflation and deflation" model
1, the theory of inflation is at 100% of the 101 largest payment rates, each block trustee income highest 50 BTS - 25 BTS - "12.5 - > 6.25 - > 3.125 BTS BTS BTS --...
Total is infinite close to 3.7 billion;
This data is never change (I hope...) So clear about the total is, for the moment is marked as: A theory of the maximum total
2, 101 active trustees average pay rate does not reach 100% in real terms, such as the current phase is 30.92%, which is equivalent to the phase destroyed by an average of 69.08% inflation. Can dynamically publish destruction of BTS, each BTS released a block is destroyed. This is BTS as chain system shares with other blocks. The important distinction between the virtual currency, not pay 100% cumulative number of destruction of BTS marked as: dynamic accumulative destruction of B
3, accumulation of trading transfer fee destroyed BTS marked as: dynamic accumulative destruction of C
4, registered agent (including low pay rate trustee, 100% senior trustee) handling charge accumulation destroy BTS marked as: D dynamic accumulative destruction
5, a registered assets (including characters long, short character assets) handling charge accumulation destroy BTS marked as: dynamic accumulative destruction of E
6, other services (such as in BitShares systems in holding all kinds of decentralized VOTE - that also need to destroy BTS) destruction of BTS marked as: dynamic accumulative destruction of F
Subtotal A total change curve: system BTS maximum amount = A - B - C - D - E - F
This value is a dynamic change, and constantly reduce the deflation.

**Comment by imYao** [comment]
================== todasun 公布的以上英文翻译的中文原文============================
关于总量的疑惑，建议公布一个【BTS总量“通胀+通缩”模型】：

1、理论最大通胀就是按101个100%支付率，每区块受托人最高收入50BTS——》25BTS——》12.5BTS——》6.25BTS——》3.125BTS——（补充：不断减半）……
总量是无限接近于37亿；
这个数据是永远不变的（希望吧……），这样关于总量就说清楚了，暂且就标记为【理论最大总量A】

2、101个活跃受托人实际平均支付率不会达到100%，比如当前阶段是30.92%，那就相当于这个阶段平均销毁了69.08%的通胀。可以动态公布销毁的BTS，每产一个块就公布销毁的BTS。这个是BTS作为系统股份与其他区块链的虚拟币的重要区别，非100%支付累积销毁BTS数标记为【动态累积销毁量B】

3、交易转账手续费累积销毁BTS标记为【动态累积销毁量C】
4、注册受托人（含低支付率受托人、100%高级受托人）手续费累积销毁BTS标记为【动态累积销毁量D】
5、注册资产（含长字符资产、短字符资产）手续费累积销毁BTS标记为【动态累积销毁量E】
6、其他服务（如在BitShares系统中举行各种去中心化投票——VOTE也需要销毁BTS）累积销毁的BTS标记为【动态累积销毁量F】

小计一个总量变化曲线：【系统BTS最大总量】=A-B-C-D-E-F
这个数值是动态变化，不断减小的——通缩！
===============================================================================
补充：在客户端GUI动态显示这个BTS总量数据模型。

**Comment by vikramrajkumar** [comment]
Out of scope; external services can perform these calculations.

**Comment by imYao** [comment]
About the ISSUE #1472
I know that http://bitsharesblocks.com can do this .
But , not everyone （the shareholders especially these Newbie ）will go to http://bitsharesblocks.com to see  this .

In general, the user (non IT people), the characteristics of the preset is very important on the client side, the shareholder can intuitively understand the maximum amount of stock supply and the changes taking place (deflationary), is the confidence of the value of the BitShares system.
