### ISSUE TITLE
Unlocking with time far in the future shows timestamp in 1910

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1473]
I did this:

    >>> wallet_unlock 999999999
    >>> info
    {
    ...
      "wallet_open": true,
      "wallet_unlocked": true,
      "wallet_unlocked_until": "31 years  in the future",
      "wallet_unlocked_until_timestamp": "1910-10-25T10:17:58",
    ...
    }

Needs fixed.

**Comment by vikramrajkumar** [comment]
Meh too low priority.

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php/topic,15469.msg199153.html#msg199153
