### ISSUE TITLE
CMake Error attempting to build latest develop

### ISSUE THREAD

**Issue by robrigo** [BitShares/bitshares#1481]
Trying to build the latest bitshares develop branch and seeing this when running cmake

```
CMake Error at libraries/fc/CMakeLists.txt:193 (add_subdirectory):
  The source directory

   ~/Documents/repos/bitshares/libraries/fc/vendor/websocketpp
```

I checked out the master branch in fc and was able to build.

**Comment by xeroc** [comment]
Same thing here ... fc not up-to-date in branch bitshares?

**Comment by pmconrad** [comment]
IMO such inconsistencies in the develop branch are to be expected and shouldn't be reported as an issue.
If you're using the develop branch you're expected to be able to handle such "issues" yourself (as you clearly are). ;-)

**Comment by robrigo** [comment]
@pmconrad Good point. I'll close the issue.

**Comment by vikramrajkumar** [comment]
It's reasonable to expect that the build is never broken on any public branch.

In this case, the build is not broken, but there is still a bug in that a submodule was added to fc--and will cause build failure if missing--without being documented anywhere.

I've updated the build instruction files to reflect that you should do `git submodule update --init --recursive` to properly checkout all submodules now.
