### ISSUE TITLE
NOTES balances not updated on transfer

### ISSUE THREAD

**Issue by davidpbrown** [BitShares/bitshares#1482]
Transfer of NOTES and TESTNOTES internal to wallet, updates the new account balance but doesn't affect the original account displayed balance. The balance is properly unavailable, so looks to be just a GUI issue not updating the detail. This in 0.8.1 with the latest GUI update applied. Unclear if this affects any other assets.

The balances are corrected if the GUI is restarted.

(Off topic but could do with a menu.[About] that details the current version and GUI patch reference.)

**Comment by xeroc** [comment]
"right click -> refresh" changing anything?
Never saw anything comparable in the CLI .. probably web_wallet issue

**Comment by davidpbrown** [comment]
Right click refresh does fix it, although moving between tabs from the dashboard and back doesn't.

It was only an issue where the whole balance was moved and that asset then disappears from the account summary. Balance updates otherwise appear to refresh promptly.

I guess there is some very minor issue with the display of balances refreshing but happy this issue closed if not worth pursuing atm.

**Comment by vikramrajkumar** [comment]
Refer to https://github.com/BitShares/web_wallet/issues/643 instead.
