### ISSUE TITLE
blockchain_list_recently_registered_accounts&blockchain_list_recently_updated_accounts  broke

### ISSUE THREAD

**Issue by todasun** [BitShares/bitshares#1483]
>> blockchain_list_recently_registered_accounts

10 assert_exception: Assert Exception
_chain_db->get_statistics_enabled(): 
    {}
    bitshares  blockchain_api.cpp:404 bts::client::detail::client_impl::blockchain_list_recently_registered_accounts

    {}
    bitshares  common_api_client.cpp:1587 bts::rpc_stubs::common_api_client::blockchain_list_recently_registered_accounts

    {"command":"blockchain_list_recently_registered_accounts"}
    bitshares  cli.cpp:626 bts::cli::detail::cli_impl::execute_command

>> blockchain_list_recently_updated_accounts

10 assert_exception: Assert Exception
_chain_db->get_statistics_enabled(): 
    {}
    bitshares  blockchain_api.cpp:387 bts::client::detail::client_impl::blockchain_list_recently_updated_accounts

    {}
    bitshares  common_api_client.cpp:1559 bts::rpc_stubs::common_api_client::blockchain_list_recently_updated_accounts

    {"command":"blockchain_list_recently_updated_accounts"}
    bitshares  cli.cpp:626 bts::cli::detail::cli_impl::execute_command

**Comment by vikramrajkumar** [comment]
These commands will only work when extra statistics tracking is enabled. You must run with `--statistics-enabled` and reindex or set `statistics_enabled: true` in config file and reindex. `blockchain_get_info` will show whether currently enabled or not.

**Comment by todasun** [comment]
tks
