### ISSUE TITLE
GUI Client hangs on menu command quit

### ISSUE THREAD

**Issue by cryptosig** [BitShares/bitshares#1485]
This has happened to me several times. When I try to properly exit the Bitshares GUI program by using the File>Quit command the client becomes unresponsive. After 10's of minutes the client may eventually finish work and close, but more often I will have had to force quit. There is no indication of work or how much work is left.

**Comment by vikramrajkumar** [comment]
Duplicate: https://github.com/BitShares/qt_wallet/issues/40
