### ISSUE TITLE
blockchain_market_status all zeros for UIAs

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1488]
delegate (locked) >>> blockchain_market_status NOTE BTS
    {
      "quote_id": 358,
      "base_id": 0,
      "current_feed_price": 0,
      "last_valid_feed_price": 0,
      "last_error": null,
      "ask_depth": 0,
      "bid_depth": 0,
      "center_price": {
        "ratio": "0.",
        "quote_asset_id": 0,
        "base_asset_id": 0
      }
    }

**Comment by vikramrajkumar** [comment]
These are deprecated but kept around for syncing old blocks:
```
"ask_depth": 0,
  "bid_depth": 0,
  "center_price": {
    "ratio": "0.",
    "quote_asset_id": 0,
    "base_asset_id": 0
  }
```
And there is not a current market error or feeds since it's a UIA so this makes sense:
```
 "quote_id": 358,
  "base_id": 0,
  "current_feed_price": 0,
  "last_valid_feed_price": 0,
  "last_error": null,
```

**Comment by xeroc** [comment]
Understood .. so in order to get latest price i need to get the order history .. can live with that .. thx
