### ISSUE TITLE
Error in import wallet backup from 0.4.27.1 to 0.8.1

### ISSUE THREAD

**Issue by testzcrypto** [BitShares/bitshares#1491]
User report error when trying to import 0.4.27.1 backup into 0.8.1: "Invalid password (20001)":
https://bitsharestalk.org/index.php?topic=11845.msg199202#msg199202

Problem was solved by installing 0.4.27.1 importing a wallet and upgrading into 0.8.1. If it's imposible to implement, at least the BitShares client should notify the user about compatibility problem.

**Comment by abitmore** [comment]
Related: https://github.com/BitShares/bitshares/issues/1406

**Comment by vikramrajkumar** [comment]
Notification added: https://github.com/BitShares/qt_wallet/commit/f941bc3a1101e8dc9bc23004a2bcb6d0b16e27f0
