### ISSUE TITLE
Intermittent crash on scanning MPA market operations

### ISSUE THREAD

**Issue by Troglodactyl** [BitShares/bitshares#1492]
Client crashes intermittently just as short covers are confirmed, and just as shorts to myself match.

This has been happening for several versions using the QT wallet.  I have not had crashes with any other transaction types.  Reopening the wallet generally reveals that the transaction went through correctly, though occasionally it crashes on login with the second attempt to scan the transaction and has to be restarted again.

**Comment by vikramrajkumar** [comment]
Possibly related: #1477

**Comment by vikramrajkumar** [comment]
@Troglodactyl Is this easily reproducible for you? Is it possible for you to get a stacktrace of the crash?

**Comment by Troglodactyl** [comment]
0	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7840465	
1	QPushButton::autoDefault() const	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff784054d	
2	QPushButton::initStyleOption(QStyleOptionButton*) const	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff78407bf	
3	QPushButton::paintEvent(QPaintEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff78408b5	
4	QWidget::event(QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76ebddc	
5	QApplicationPrivate::notify_helper(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76b02b4	
6	QApplication::notify(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76b3c86	
7	BitSharesApp::notify	BitSharesApp.cpp	549	0x8f0709	
8	QCoreApplication::notifyInternal(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff39dfe24	
9	QWidgetPrivate::sendPaintEvent(QRegion const&)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76d9f34	
10	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76e885d	
11	QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76e98ec	
12	QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76e967f	
13	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76e898e	
14	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76bd301	
15	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76bd449	
16	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7709690	
17	QApplicationPrivate::notify_helper(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76b02b4	
18	QApplication::notify(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff76b3c86	
19	BitSharesApp::notify	BitSharesApp.cpp	549	0x8f0709	
20	QCoreApplication::notifyInternal(QObject*, QEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff39dfe24	
21	QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff4292557	
22	QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff4299aad	
23	QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff427e728	
24	??	/opt/Qt5.4.1/5.4/gcc_64/plugins/platforms/libqxcb.so		0x7fffea66ea10	
25	g_main_context_dispatch	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff1be2e04	
26	??	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff1be3048	
27	g_main_context_iteration	/lib/x86_64-linux-gnu/libglib-2.0.so.0		0x7ffff1be30ec	
28	QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff3a3a5e4	
29	QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff39de04b	
30	QCoreApplication::exec()	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.so.5		0x7ffff39e2f65	
31	BitSharesApp::run	BitSharesApp.cpp	415	0x8f0e25	
32	BitSharesApp::run	BitSharesApp.cpp	316	0x8f1555	
33	main	main.cpp	11	0x8c4462	



0	QImageData::create(QSize const&, QImage::Format, int)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff42de502	
1	QImage::QImage(int, int, QImage::Format)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff42de9eb	
2	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff432b7c5	
3	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff432c673	
4	QImage::QImage(char const* const*)	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.so.5		0x7ffff42db2b1	
5	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7789a42	
6	QProxyStyle::standardPixmap(QStyle::StandardPixmap, QStyleOption const*, QWidget const*) const	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff773aad5	
7	QCommonStyle::standardIcon(QStyle::StandardPixmap, QStyleOption const*, QWidget const*) const	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7728b50	
8	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7789ce9	
9	QProxyStyle::standardIcon(QStyle::StandardPixmap, QStyleOption const*, QWidget const*) const	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff773ae93	
10	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7a30f31	
11	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7a322a2	
12	??	/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.so.5		0x7ffff7a4fe3a	
13	operator()	MainWindow.cpp	377	0x8d7a1a	
14	boost::detail::function::void_function_obj_invoker1<MainWindow::setupTrayIcon()::__lambda7, void, bts::wallet::ledger_entry>::invoke(boost::detail::function::function_buffer &, bts::wallet::ledger_entry)	function_template.hpp	153	0x8d7a1a	
15	operator()	function_template.hpp	767	0xaa6c86	
16	m_invoke<boost::function<void(bts::wallet::ledger_entry)>, 0u, bts::wallet::ledger_entry&>	variadic_slot_invoker.hpp	92	0xaa6c86	
17	operator()<boost::function<void(bts::wallet::ledger_entry)>, bts::wallet::ledger_entry&, 1ul>	variadic_slot_invoker.hpp	81	0xaa6c86	
18	m_invoke<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>	variadic_slot_invoker.hpp	117	0xaa6c86	
19	operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>	variadic_slot_invoker.hpp	110	0xaa6c86	
20	dereference	slot_call_iterator.hpp	82	0xaa6c86	
21	dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, bts::wallet::ledger_entry>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>	iterator_facade.hpp	514	0xaa6c86	
22	operator*	iterator_facade.hpp	639	0xaa6c86	
23	operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, bts::wallet::ledger_entry>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>	optional_last_value.hpp	55	0xaa6c86	
24	operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, bts::wallet::ledger_entry>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void(bts::wallet::ledger_entry), boost::function<void(bts::wallet::ledger_entry)>>, boost::signals2::mutex>>>	result_type_wrapper.hpp	64	0xaa6c86	
25	boost::signals2::detail::signal_impl<void (bts::wallet::ledger_entry), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (bts::wallet::ledger_entry)>, boost::function<void (boost::signals2::connection const&, bts::wallet::ledger_entry)>, boost::signals2::mutex>::operator()(bts::wallet::ledger_entry)	signal_template.hpp	246	0xaa6c86	
26	boost::signals2::signal<void (bts::wallet::ledger_entry), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (bts::wallet::ledger_entry)>, boost::function<void (boost::signals2::connection const&, bts::wallet::ledger_entry)>, boost::signals2::mutex>::operator()(bts::wallet::ledger_entry)	signal_template.hpp	695	0xaa761c	
27	bts::wallet::detail::wallet_impl::scan_market_transaction	transaction_ledger.cpp	162	0xa780aa	
28	bts::wallet::detail::wallet_impl::scan_block	transaction_ledger.cpp	283	0xa7e236	
29	bts::wallet::detail::wallet_impl::start_scan_task	wallet.cpp	234	0x90009f	
30	operator()	wallet.cpp	1725	0x901f16	
31	fc::detail::void_functor_run<bts::wallet::wallet::start_scan(uint32_t, uint32_t)::__lambda10>::run(void *, void *)	task.hpp	83	0x901f16	
32	fc::task_base::run_impl	task.cpp	43	0x10a9f03	
33	fc::task_base::run	task.cpp	32	0x10aa5b5	
34	run_next_task	thread_d.hpp	498	0x10a869e	
35	fc::thread_d::process_tasks	thread_d.hpp	547	0x10a869e	
36	fc::thread_d::start_process_tasks	thread_d.hpp	475	0x10a8911	
37	make_fcontext			0x15e3f1e	
38	??			0x7fff840008c0	
39	??			0x7fff3a95d3c0	
40	??				



0	pthread_cond_wait**GLIBC_2.3.2	/lib/x86_64-linux-gnu/libpthread.so.0		0x7ffff2eec414	
1	boost::condition_variable::wait	condition_variable.hpp	73	0x10a6adb	
2	fc::thread_d::process_tasks	thread_d.hpp	574	0x10a88cc	
3	fc::thread::exec	thread.cpp	242	0x10a1cc4	
4	fc::thread::thread(std::string const&)::{lambda()#1}::operator()() const	thread.cpp	81	0x10a305c	
5	thread_proxy			0x15b1bca	
6	start_thread	/lib/x86_64-linux-gnu/libpthread.so.0		0x7ffff2ee8182	
7	clone	/lib/x86_64-linux-gnu/libc.so.6		0x7ffff21ed47d	



0	pthread_cond_timedwait**GLIBC_2.3.2	/lib/x86_64-linux-gnu/libpthread.so.0		0x7ffff2eec7ce	
1	do_wait_until	condition_variable.hpp	108	0x10a6c08	
2	wait_until	condition_variable_fwd.hpp	253	0x10a6c08	
3	boost::condition_variable::wait_until<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l>>>	condition_variable_fwd.hpp	181	0x10a6c08	
4	fc::thread_d::process_tasks	thread_d.hpp	598	0x10a88b9	
5	fc::thread_d::start_process_tasks	thread_d.hpp	475	0x10a8911	
6	make_fcontext			0x15e3f1e	
7	??			0x7fff640008c0	
8	??			0x7fff64000b90	
9	??				




0	malloc	/lib/x86_64-linux-gnu/libc.so.6		0x7ffff2175755	
1	operator new(unsigned long)	/usr/lib/x86_64-linux-gnu/libstdc++.so.6		0x7ffff2a32f2d	
2	std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)	/usr/lib/x86_64-linux-gnu/libstdc++.so.6		0x7ffff2a8e3b9	
3	char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag)	/usr/lib/x86_64-linux-gnu/libstdc++.so.6		0x7ffff2a8fae1	
4	std::string::basic_string(char const*, std::allocator<char> const&)	/usr/lib/x86_64-linux-gnu/libstdc++.so.6		0x7ffff2a8fef8	
5	boost::system::(anonymous namespace)::generic_error_category::message(int) const			0x15b6b38	
6	boost::system::(anonymous namespace)::system_error_category::message(int) const			0x15b6bf8	
7	message	error_code.hpp	358	0x8caa2d	
8	boost::system::system_error::what	system_error.hpp	70	0x8caa2d	
9	fc::asio::detail::error_handler	asio.cpp	59	0x1162808	
10	operator()<void (*)(const fc::shared_ptr<fc::promise<void>>&, const boost::system::error_code&), boost::_bi::list1<const boost::system::error_code&>>	bind.hpp	313	0x1145f42	
11	operator()<boost::system::error_code>	bind_template.hpp	47	0x1145f42	
12	operator()	bind_handler.hpp	47	0x1145f42	
13	asio_handler_invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>>	handler_invoke_hook.hpp	64	0x1145f42	
14	invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>, boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>>	handler_invoke_helpers.hpp	37	0x1145f42	
15	asio_handler_invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>, boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>	bind_handler.hpp	88	0x1145f42	
16	invoke<boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>, boost::asio::detail::binder1<boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>, boost::system::error_code>>	handler_invoke_helpers.hpp	37	0x1145f42	
17	boost::asio::detail::reactive_socket_connect_op<boost::asio::ip::tcp, boost::_bi::bind_t<void, void (*)(fc::shared_ptr<fc::promise<void>> const&, boost::system::error_code const&), boost::_bi::list2<boost::_bi::value<fc::shared_ptr<fc::promise<void>>>, boost::arg<1>>>>::do_complete	reactive_socket_connect_op.hpp	100	0x1145f42	
18	complete	task_io_service_operation.hpp	37	0x11655b7	
19	boost::asio::detail::task_io_service::do_run_one	task_io_service.ipp	384	0x11655b7	
20	boost::asio::detail::task_io_service::run	task_io_service.ipp	153	0x11666b1	
21	run	io_service.ipp	59	0x116684b	
22	operator()	asio.cpp	105	0x116684b	
23	boost::detail::thread_data<fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}>::run()	thread.hpp	117	0x116684b	
24	thread_proxy			0x15b1bca	
25	start_thread	/lib/x86_64-linux-gnu/libpthread.so.0		0x7ffff2ee8182	
26	clone	/lib/x86_64-linux-gnu/libc.so.6		0x7ffff21ed47d	



0	fc::shared_ptr<fc::promise<unsigned long>>::~shared_ptr	shared_ptr.hpp	47	0x1141b43	
1	~future	future.hpp	185	0x15a8135	
2	fc::detail::rate_limiting_group_impl::readsome_impl<std::shared_ptr<char>>	rate_limiting.cpp	310	0x15a8135	
3	bts::net::stcp_socket::readsome	stcp_socket.cpp	86	0xff8e4f	
4	fc::istream::read	iostream.cpp	360	0x10b6b36	
5	bts::net::detail::message_oriented_connection_impl::read_loop	message_oriented_connection.cpp	136	0x154c2d7	
6	operator()	message_oriented_connection.cpp	108	0x154e6ac	
7	fc::detail::void_functor_run<bts::net::detail::message_oriented_connection_impl::connect_to(const fc::ip::endpoint&)::__lambda1>::run(void *, void *)	task.hpp	83	0x154e6ac	
8	fc::task_base::run_impl	task.cpp	43	0x10a9f03	
9	fc::task_base::run	task.cpp	32	0x10aa5b5	
10	run_next_task	thread_d.hpp	498	0x10a869e	
11	fc::thread_d::process_tasks	thread_d.hpp	547	0x10a869e	
12	fc::thread_d::start_process_tasks	thread_d.hpp	475	0x10a8911	
13	make_fcontext			0x15e3f1e	
14	??			0x7fff0c0008c0	
15	??			0x7fff0c16f560	
16	??

**Comment by Troglodactyl** [comment]
My original theory was that it was an issue with the tray icon bubble messages not being thread safe.  Here I've added queuing to the notification system as an attempted fix:

https://github.com/Troglodactyl/qt_wallet/commit/d6a60a17861b012e87d5db0d11ad60f0479b3277
https://github.com/Troglodactyl/qt_wallet/commit/2ad9c672b5b682ed5889d057d14e8da7f380e9e0

Unfortunately testing this I still had the issue at least once, so I supposed that I was on the wrong track.  The stack looks to me like this could actually be it though, so perhaps my fix was just incomplete or I missed something else.

**Comment by Troglodactyl** [comment]
I backed up a copy of my wallet folder which includes unscanned market transactions, so I can now reproduce this issue at will by restoring it.  I'll do some more testing.

**Comment by vikramrajkumar** [comment]
Assuming fixed by https://github.com/BitShares/qt_wallet/commit/d0fc812a6690f3451d902039960092ffa36cbed6 until we hear otherwise.
