### ISSUE TITLE
Short orders lower than the highest margin call price can't be filled

### ISSUE THREAD

**Issue by btswildpig** [BitShares/bitshares#1495]
Short orders higher than the highest margin call price can be filled , while those short orders who are lower than the highest margin call price can't .

**Comment by pmconrad** [comment]
This is a known issue : https://github.com/BitShares/bitshares/issues/1315#issuecomment-75244261

**Comment by abitmore** [comment]
Yes the short order is dropped when limit price is lower than margin call price:
https://github.com/BitShares/bitshares/blob/64cb2f6aae18e306dea995dca400eb3c754c9fa3/libraries/blockchain/market_engine_v7.cpp#L179-187
Already fixed in v0.9.

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php/topic,15668.msg201173.html#msg201173

**Comment by theoreticalbts** [comment]
Yeah, this should be fixed in latest version of market engine.  Feel free to re-open if it pops up again
