### ISSUE TITLE
【emergency】short&buy can't math right now in bitUSD:bts market

### ISSUE THREAD

**Issue by todasun** [BitShares/bitshares#1497]
![qq 20150411160238](https://cloud.githubusercontent.com/assets/10720816/7100731/71c3e49c-e064-11e4-82be-0e5b7690fdfc.png)

i have reloaded many times

**Comment by abitmore** [comment]
Another screenshot here: #1498 .
The top 'sell order' is a short order.
The reason is same to #1495 . 
A workaround could be short with a higher limit_price or without limit_price.

**Comment by vikramrajkumar** [comment]
Duplicate: #1495
