### ISSUE TITLE
how can we do

### ISSUE THREAD

**Issue by vsrole** [BitShares/bitshares#1498]
![qq 20150411161251](https://cloud.githubusercontent.com/assets/9563334/7100750/ac7ad0ae-e065-11e4-919a-caa7fb951bf2.jpg)

**Comment by pmconrad** [comment]
This is the third issue opened on the same subject. Duplicates: #1497 and #1495 .
Also see this thread for explanations: https://bitsharestalk.org/index.php/topic,15668.0.html

**Comment by vikramrajkumar** [comment]
Duplicate: #1495
