### ISSUE TITLE
The 5% margin call fee is gone in dvs/0.9.0 ?

### ISSUE THREAD

**Issue by abitmore** [BitShares/bitshares#1499]
* BM said the 5% fee will be eliminated in this post https://bitsharestalk.org/index.php/topic,13782.0/all.html, because an operation will be implemented to cover the short with collateral and bypass the fee.
* The operation is implemented in this commit 211c5e17f4b2d53ebfd5504c6ff1c7cdf731d509, and named `update_call_price`. At the same commit the 5% fee is gone.
* The `update_call_price` operation is renamed to `update_cover` in this commit c48646f840d68b9fe90387d56b1b57fb91230712. 
* The `update_cover` operation is removed in this commit: 445e22dfc73a8851eba2b9c78c3b262f3555f6c6

So the only result is, the 5% fee gone. Is it expected?

**Comment by vikramrajkumar** [comment]
@abitmore Good catch and good working tracing the commit history.

Given BM's explanation in the linked thread and in particular this segment:
> In reality the 5% fee merely served to create a variable amount of additional collateral depending upon the risk tolerance of each individual shorter.  Considering we are raising the min collateral requirement from 1.5 to 2x the added benefit of the 5% fee is insignificant.  The fear of a short squeeze and being forced to buy at up to 10% above the feed if there are not enough orders at the feed means there is still plenty of incentive to avoid forced buying.

And in the interest of simplicity and avoiding the additional development and testing that would be required for further changes, we will leave things as they are with the 5% fee now removed.

**Comment by xeroc** [comment]
Has this made it's way into bts/0.9.0 tag?

**Comment by abitmore** [comment]
Sure.

**Comment by xeroc** [comment]
If so it was not properly communicated in the forums IMHO
