### ISSUE TITLE
0.8 Can't open

### ISSUE THREAD

**Issue by rgcrypto** [BitShares/bitshares#1507]
My computer shut down by accident while the software was still open.
Now when I enter my password and press unlock, the screen remain and I can't get to my account.

**Comment by vikramrajkumar** [comment]
@rgcrypto Please see https://github.com/BitShares/web_wallet/issues/641#issuecomment-87799560 and see if you can login that way.

**Comment by vikramrajkumar** [comment]
Please refer to the above link and make a support thread on the forum if you are still having problems.
