### ISSUE TITLE
Unable to import wallet in .8

### ISSUE THREAD

**Issue by AdamBLevine** [BitShares/bitshares#1509]
The last time I used Bitshares was on a different computer in the version .4-ish days, I downloaded the most recent version for 64bit windows from bitshares.org but on attempting to load my wallet backups I recieved error 20001 "invalid password!" which is unfortunate and was a bit terrifying because it's inaccurate. 

 I double checked on my other computer that still has the early version of Bitshares on it and the password works fine there although it will not connect to the network.  I then backed up my wallet from the computer where the password worked and tried to recover it on the computer with the updated bitshares client with the same result, invalid password recovering the file.

![image](https://cloud.githubusercontent.com/assets/6858319/7243472/62b246e0-e782-11e4-9572-b560e8932ef2.png)

What gives?

**Comment by vikramrajkumar** [comment]
@AdamBLevine This is a still-unsolved bug on some Windows platforms.

For now the workaround is to install version 0.5.3 (https://github.com/BitShares/bitshares/releases/tag/bts%2F0.5.3) first, import the backup, then upgrade in-place to the latest version.

Another option is that you should also be able to directly copy the `wallets` folder from your old client application data directory for the to the same spot on the other computer with the new version.

**Comment by roadscape** [comment]
I got this 'Invalid Password' message on OSX with 0.8.  Yesterday I was switching between 2 wallets.. wallet #1 worked and #2 kept giving me this error. I was getting worried and about to post an issue, but the problem resolved itself.

The problem may have been due to the fact that wallet #1 was not finished scanning. Today, I let it finish, then swapped for #2, and my password was accepted.

Sorry I can't contribute more.. just know there's hope :)

It's a shot in the dark but you could try:
 - move `wallets` to `wallets.bak`
 - launch bitshares and create a new "temp" wallet (to ensure a fresh/consistent state)
 - close bitshares, delete the newly created `wallets` dir
 - move `wallets.bak` to `wallets`
 - cross your fingers and re-launch the client

**Comment by AdamBLevine** [comment]
@vikramrajkumar is this a legacy issue?  do you believe it will be fixed in the next few months?   I was just trying to check in on the technology, seems like it needs a bit more time.

**Comment by vikramrajkumar** [comment]
@AdamBLevine This is an issue affecting wallet backups created before version 0.6.0, and is unlikely to be fixed.

**Comment by AdamBLevine** [comment]
@vikramrajkumar 

That seems hard to believe.    I wonder how many people have this problem assume the "invalid password" error actually means their password is invalid and assumes it's their fault, moving on.

You guys can't be onboarding many new users compared to the early adopters who are potentially affected by this bug, so this seems like a choice to save a little time by throwing away the people who supported the project financially to the point it is now.

Is this just an impossible bug to solve or is it just not worth the time because it "only effects people who backed up their wallets after 0.6.0" lol

I can't imagine this is the upgrade experience you want people who put money into the system earlier to experiance lacking any context besides an error message that incorrectly says your password is wrong.  And the workaround you've provided given the bug won't be fixed is insane.  I might do that but who else would?  Where do I even get a version of Bitshares so out of date?  

Is this showstopping bug talked about anywhere on any non-forum or are all users who run into it expected to just know to post an issue on github?

Am I crazy?

**Comment by vikramrajkumar** [comment]
@AdamBLevine I've spent a long time looking at this bug and unfortunately have not been able to figure it out. There have been many GitHub issues and forum posts on BitSharesTalk about it. The software is still unstable/experimental and early adopters are expected to post on the forum when they run into walls like this.

**Comment by AdamBLevine** [comment]
Given that the bug isn't going to be fixed, is this something that will get
easier or more difficult to recover my accounts as you roll out new
versions?

I'm not really anxious to spend more time trying to figure this out but I
need to recover these at some point, should I do it ASAP?

If this is a known bug that will not be fixed you should put a more
descriptive error so that it's less traumatic and more descriptive of
what's actually happening.  I've wasted like three hours on all this and
much of it would have been avoided if the error was "upgrade compatability
issue, see <link> for support" rather than 'invalid password"

**Comment by vikramrajkumar** [comment]
It won't become much more difficult in the future, but you may as well recover it now so you don't have to deal with this later.

An easier way to do so might be to create a brand new wallet, add a new temporary local account, and use the "Import Keys from Wallet" feature under that account and feed it the backup file. See the attached screenshot for where I mean:
![screen shot 2015-04-21 at 11 54 39 am](https://cloud.githubusercontent.com/assets/793567/7256508/92218d3c-e81d-11e4-973c-befb878e0eb8.png)

If that works okay and your old balances/accounts show up, then create a new backup file and use that one in the future (and I would make sure to keep the old one too just to be extra careful).


> If this is a known bug that will not be fixed you should put a more descriptive error so that it's less traumatic and more descriptive of what's actually happening. I've wasted like three hours on all this and much of it would have been avoided if the error was "upgrade compatability issue, see <link> for support" rather than 'invalid password"

Yes we will do something like this: #1491

**Comment by vikramrajkumar** [comment]
Support link added to error message in RC2: https://bitsharestalk.org/index.php/topic,15900.msg203941.html#msg203941

Please post in the forum for help with this if you are still having problems.
