### ISSUE TITLE
Since when do I need to USD transfer fees in USD?

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1514]
I wrote a script that regularily exchanges income from the charity delegates
into USD and EUR and transfer them to a separated "payouts.charity" account.

I used to pay the tx fee in BTS, but this does not work in the 0.9.0-rc1
release, anylonger:

    delegate (unlocked) >>> balance
    ACCOUNT                         BALANCE                     
    ============================================================
    exchange.charity                1,785.77741 BTS             
                                    1.4211 USD                  
    delegate (unlocked) >>> transfer 1.4211 USD exchange.charity payouts.charity
    20010 insufficient_funds: insufficient funds

Is this a desired behavior? If so, we should have a document that states how to
derive the USD fee for transfers, even better, have a RPC call or attribute in
the asset that shows the tx fee in USD.

**Comment by vsrole** [comment]
"insufficient funds"   me too

**Comment by vikramrajkumar** [comment]
Should be fixed in RC2: https://bitsharestalk.org/index.php/topic,15900.msg203941.html#msg203941

**Comment by abitmore** [comment]
Now the default fee for transferring bitUSD is in bitUSD? How much is it?
Is it possible if I want to pay the fee with BTS?

**Comment by xeroc** [comment]
could we still have `blockchain_get_asset USD` show the transaction fee if payed in bitUSD?
