### ISSUE TITLE
An error occurred while trying to start - 0.9.0 RC1 with no BitShares folder [OSX]

### ISSUE THREAD

**Issue by jazy510** [BitShares/bitshares#1515]
On OSX - Running 0.9.0-RC1 without an Application Support/BitShares folder already existing, causes the program to just put an error dialog up w/a Red ! Stop Sign icon, which says "An Error occurred while trying to start"

The only way i could get the 0.9.0 RC1 client to launch, was to manually create the Library/Application Support/BitShares folder - if it doesn't already exist, it would halt w/the above error dialog.

**Comment by vikramrajkumar** [comment]
Cannot reproduce. What version of OSX? Does it still happen to you in RC2: https://bitsharestalk.org/index.php/topic,15900.msg203941.html#msg203941

**Comment by jazy510** [comment]
I believe this was due to a broken / missing symlink (the symlink destination was removed) - thus it may not be a legit issue.
