### ISSUE TITLE
Funds Disappeared V 0.9

### ISSUE THREAD

**Issue by rgcrypto** [BitShares/bitshares#1517]
Hi, 

Big problem here. I had 67k BTS. I tried buying MoonFund but cancelled my order because the buy order wasn't working (V0.8). Then problem started to happen. (Cryptoctopus -> Unknown)

I moved on to V0.9RC1 yesterday and today, I bought more BTS through metaexchange and what I bought completely replace my previous balance and lost all of my previous balance. WTF is going on?

![screenshot 2015-04-23 07 33 09](https://cloud.githubusercontent.com/assets/10917252/7301139/96ae4042-e995-11e4-95ca-07cf5841b258.png)
![screenshot 2015-04-23 07 37 23](https://cloud.githubusercontent.com/assets/10917252/7301141/96d437ca-e995-11e4-9d09-bb98fa3b5b71.png)
![screenshot 2015-04-23 08 48 47](https://cloud.githubusercontent.com/assets/10917252/7301140/96b665a6-e995-11e4-9672-a536e61c89e1.png)

**Comment by dnotestein** [comment]
I'm a bit confused, because in your first picture, it shows 67 BTS, not 67K BTS... Is that just a coincidence and you are talking about some other 67K BTS?

**Comment by rgcrypto** [comment]
Sorry, I am a bit confused too. Here is a more complete story:
I had 57k of BTS. I tried buying MoonFund but cancelled my order because the buy order wasn't working (V0.80). Then problem started to happen. (Cryptoctopus -> Unknown). I had 67BTS in my wallet but my 57k wouldn't reappear after I cancelled my buy order for MoonFunds.

**Comment by dnotestein** [comment]
From the console, can you type "history cryptoctopus" and paste the results here? 
(you can get to console by clicking on "cryptoctopus" drop down on right hand top of screen, then selecting "Advanced", then select "Console" tab)

**Comment by rgcrypto** [comment]
TIMESTAMP           BLOCK     FROM                TO                  AMOUNT                  MEMO                                        BALANCE                 FEE                 ID      
==============================================================================================================================================================================================
2015-04-18T15:00:20 2314093   metaexchangebtc     cryptoctopus        54,645.97147 BTS        mX: buy BTS                                 54,645.97147 BTS        0.00000 BTS         2ecdb302
2015-04-19T01:42:10 2317864   cryptoctopus        UNKNOWN             54,578.34883 BTS                                                    67.12264 BTS            0.50000 BTS         4ec26f43
2015-04-23T15:45:50 2357341   metaexchangebtc     cryptoctopus        31,635.64413 BTS        mX: buy BTS                                 31,702.76677 BTS        0.00000 BTS         7ec8413a

Seems the funds went to the market and didn't came back when I cancelled

**Comment by rgcrypto** [comment]
riverhead saved the day with: wallet_regenerate_keys cryptoctopus 12000 

Issue closed

**Comment by dnotestein** [comment]
I don't see your market order at all (there should be a BID or ASK as the destination for a market order). Maybe try a "rescan" from the console...

**Comment by educatedwarrior** [comment]
This is the exact same thing that happened to me.   Need help.
