### ISSUE TITLE
bts/0.9.0 blockchain_list_key_balances

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1523]
Comparing 0.8.0 to 0.9.0, this call took about 1 seconds, it now takes about 4 seconds.  The hosted wallet will be affected.

`blockchain_list_key_balances "BTS6iTNEs8RvZYdNsoZW2XojhR1fyMDywgB2tWSy2WXmgUqsUnqPR"`

**Comment by jcalfee** [comment]
Much better .. thank you!

**Comment by abitmore** [comment]
The API is implemented as iterating a hash table to find matching records, it's time inefficient anyway, since complexity is O(n) or say linear. We're using a cache for address->whatever pairs in wallet db, is it possible to cache like that in chain db?

**Comment by abitmore** [comment]
I am talking about complexity of `scan_balances` call.

**Comment by abitmore** [comment]
Update: I am talking about inefficiency of calling `scan_balances`.
