### ISSUE TITLE
how to start the testnet? thanks

### ISSUE THREAD

**Issue by CompileMaster** [BitShares/bitshares#1530]
i want to start the testnet, but i don't know how to import the 101 delegates to my wallet,please help me ,thanks.

**Comment by CompileMaster** [comment]
but the help answer me this :

>> help wallet_import_private_key

Usage:
wallet_import_private_key <wif_key> [account_name] [create_new_account] [rescan]                      Loads the private key into the specified account. Returns which account it was actually imported to.
Loads the private key into the specified account. Returns which account it was actually imported to.

Parameters:
  wif_key (wif_private_key, required): A private key in bitcoin Wallet Import Format (WIF)
  account_name (account_name, optional, defaults to null): the name of the account the key should be imported into, if null then the key must belong to an active account
  create_new_account (bool, optional, defaults to false): If true, the wallet will attempt to create a new account for the name provided rather than import the key into an existing account
  rescan (bool, optional, defaults to false): If true, the wallet will rescan the blockchain looking for transactions that involve this private key

Returns:
  account_name

aliases: import_key, importprivkey

**Comment by CompileMaster** [comment]
account_name is optional, why the comand report a error?

**Comment by xeroc** [comment]
Try
    
    wallet_account_create foobar
    wallet_import_private_key 5Jh2tEhMchUkBZqX6SXNn6pjAZDT2vPHU2YLYW1jAvaBC4zdD8A foobar

instead
