### ISSUE TITLE
wallet_account_update_active_key fails with "unable to parse new active key" if key is given as argument

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1539]
default (unlocked) >>> wallet_account_update_active_key xxxxxxxxxxxx xxxxxxxxxxxx BTS5DCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    10 assert_exception: Assert Exception
    new_private_key.valid(): Unable to parse new active key.

**Comment by abitmore** [comment]
Looks like the parameter should be a private key, but `BTS5DCxxxxxxxxxx` is a public key?

**Comment by xeroc** [comment]
dang ..
you are write .. though it could be an address but the help indeed states it requires a wif..

sorry for the interrupt
closing
