### ISSUE TITLE
Lost BTS to fees from cover bug.

### ISSUE THREAD

**Issue by nmushegian** [BitShares/bitshares#1545]
Transaction  #414cd742

-109,646.72321 BTS     fee

**Comment by vikramrajkumar** [comment]
Regression after most recent hardfork. Will put out a delegate-only release soon to fix this.

**Comment by vikramrajkumar** [comment]
Actually looking closer at the transaction it looks like the BTS was paid back correctly:
```
[ ... ]

          "type": "deposit_op_type",
          "data": {
            "amount": 10964672321,
            "condition": {
              "asset_id": 0,
              "slate_id": 0,
              "type": "withdraw_signature_type",
              "data": {
                "owner": "BTS8vWTzv7bn27FxDzjY1UtbzdTrK3zW8nCA"
              }
            }
          }

[ ... ]

    "fees_paid": [[
        0,
        50000
      ],[
        22,
        0
      ]
    ],
    "total_base_equivalent_fees_paid": 50000,

[ ... ]
```

In any case I have put out a release that performs an extra check to ensure the bug cannot recur: https://github.com/BitShares/bitshares/commit/9145b63d9879446c6e95058b98d9a2f33c4d6b48
