### ISSUE TITLE
wallet file crack after update from 0.9.1 to 0.9.2

### ISSUE THREAD

**Issue by pureland** [BitShares/bitshares#1546]
Wallet file crack after update from 0.9.1 to 0.9.2
also many user have this problem too

**Comment by xeroc** [comment]
you can import from automated backups ...

1) locate you wallet folders according to http://wiki.bitshares.org/index.php/BitShares/Config
2) rename `wallets/default` into something else (as a backup)
3) launch the client and click "import wallet" from the main menu
4) go to the wallet folder from 1)
5) select the most recent backup in `wallets/.backups/default/` for import
6) provide your passphrase ..
7) done

**Comment by vikramrajkumar** [comment]
It's not clear to me what this means; if you are still having a problem, please post a more detailed report in the technical support forum here: https://bitsharestalk.org/index.php/board,45.0.html
