### ISSUE TITLE
After voting - receiving notification "invalid asset amount"

### ISSUE THREAD

**Issue by zhenkas** [BitShares/bitshares#1551]
After voting via Bitshare Windows Client 0.9.1 - receiving "invalid asset amount" notification.

![bts_issue_invalid_asset_amount](https://cloud.githubusercontent.com/assets/858377/7897373/585153f6-06e2-11e5-85f1-a2abc7dbcf94.png)

Voting via another account works clean.

**Comment by vikramrajkumar** [comment]
Duplicate: #681
