### ISSUE TITLE
What am i doing wrong? Register error...

### ISSUE THREAD

**Issue by lemial** [bitshares/bitshares#1552]
Trying to register a new wallet for this guide: http://wiki.bitshares.org/index.php/Delegate/How-То, get this error:

wallet (unlocked) >>> wallet_add_contact_account myname PTS5dBUB5KB6ZYUHzNASQYajNyudyq1tkBsQZ7PgKzVDe2Qv9k6Ka
Error: invalid command "wallet_add_contact_account"

wallet (unlocked) >>> wallet_list_my_accounts
Error: invalid command "wallet_list_my_accounts"

The client latest version!

**Comment by xeroc** [comment]
Seems the Howto is deprecated ...
The correct command to create a new account is 

 wallet_account_create

and you can see your account with

 wallet_list_accounts

to get all commands you can simply use 

 help
