### ISSUE TITLE
Missing NOTEs private key when exporting

### ISSUE THREAD

**Issue by jcalfee** [bitshares/bitshares#1555]
How could a BTS 1.0 wallet return the same private key for both of these commands?
```
wallet_dump_private_key BTSLH4gqUTeHzrc1venu5kbm9xwFiLjsbChs
wallet_dump_private_key BTSGqhRJW2BcJUs6N55e4pQfAknmTSafYzQ
```
The BTS 1.0 blockchain has a NOTEs balance under the second address.  The issue is the WIF I get converts to the first address (no balance)!  Also vikram's newly formatted export keys file (https://github.com/bitshares/bitshares/commit/8e91dac18add0f86fd8a6a59091d80b6ebdc2d6c) contains only the 1st address.

So it appears that the export key file may be missing this private key.

I suspect there is a issue here beyond this wallet file, @svk31 is having an issue where he does not see his original share drop NOTEs in BTS 2.0 but can see other NOTEs obtained through a transfer.

Their are addresses with NOTE credits in the testnet genesis `jul-31-test-genesis.json`.

I do recall transferring a few NOTEs to test them out at one point.

**Comment by jcalfee** [comment]
@svk31 is using the new wallet export format and is going to let us know if his matching genesis NOTEs address is being exported...

**Comment by vikramrajkumar** [comment]
I am almost certain this is due to not checking all 5 address formats (PTS/BTC/BTS) for each private key. Re-open if that does not solve it.
