### ISSUE TITLE
Compute total_collateral, long_equity and short_equity for BitAsset

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#726]
We should have a command to get the total BTSX removed from circulation to collateralize BitUSD.  I propose adding a new field `total_collateral` to the output of the `blockchain_get_asset USD` command.

It would be nice to also provide `long_equity` and `short_equity`.  Each is the fraction of `total_collateral` that long and short holders would (hypothetically) get if every long BitUSD holder sold at `avg_price_1h` and every short BitUSD holder bought and covered at `avg_price_1h`.

Here's how I would compute them (you should probably double check these formulas give the right answers before implementing them):

    long_equity = (current_share_supply[USD] / (precision[USD] * avg_price_1h)) / total_collateral[USD]
    short_equity = 1.0 - long_equity

I think `short_equity` is a great macro-economic indicator of the state of a BitAsset:

- Exactly 1.0:  BitUSD is trading at zero (this can't actually happen, but we could get arbitrarily close).

- Above 0.5:  Short positions, on average, have unrealized profits on their books (or have chosen to use less than maximum leverage)

- Exactly 0.5:  Short positions are breaking even.

- Below 0.5:  Shorts have taken losses.

- Less than 0.25:  The market is in a margin crisis.  The only way this situation can happen is if the Ask book doesn't have enough depth to satisfy demand from automatic margin call orders (or margin calls aren't executing because prices are so high that the entire collateral can't cover the margin, i.e. `short_equity` is really less than 0.0, but the moving average means the computed `short_equity` value hasn't quite caught up to reality just yet).

- Less than 0.0:  The BitUSD backing is inadequate; margin calls will be unable to execute without a price drop or an FDIC bailout.

**Comment by vikramrajkumar** [comment]
For viewing collateralization: https://github.com/BitShares/bitshares/commit/bf5ab92da7e039de50a05bdaf3266dc4a13ce790

The other two values can be calculated by external services.
