### ISSUE TITLE
Wallet not rescanning in delegate after block production disabled

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#733]
Performed a delegate_withdraw_pay in an inactive delegate that had block production enabled. Then disabled block production and issued a rescan command, but it didn't find the transfer (just returned "OK" immediately). Had to lock and unlock the wallet for it to properly rescan and find the transfer.

**Comment by vikramrajkumar** [comment]
Too old; and I doubt this is still a problem after recent scanning changes: 1d67a9bca519b8e417f3d2507324a98a7e2e3a1d
