### ISSUE TITLE
Use broadcast to discover LAN peers

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#871]
When running multiple clients on the same LAN, it is highly desirable for those nodes to discover each other (for obvious reasons, LAN bandwidth is generally very fast and cheap compared to an internet connection).  We can implement this with broadcast packets:  See http://en.wikipedia.org/wiki/Broadcast_address

**Comment by vikramrajkumar** [comment]
Would be nice but out of scope for the foreseeable future.
