### ISSUE TITLE
Unit testing of serialization code

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#882]
All serializable types should have a unit test where the serialization produced by the code is compared against a hard-coded reference serialization.

The purpose of these tests is to catch cross-platform errors on 32-bit vs. 64-bit or little-endian vs. big-endian.

See discussion on #495 for more.

**Comment by vikramrajkumar** [comment]
@theoreticalbts Should this still be kept open?

**Comment by vikramrajkumar** [comment]
Too old; closing.
