### ISSUE TITLE
Mandatory automatic wallet backups

### ISSUE THREAD

**Issue by NginUS** [BitShares/bitshares#903]
As is being discussed on BitSharesTalk, here:
https://bitsharestalk.org/index.php?topic=9435.0

I'd like to propose the creation of a mandatory option to automatically backup 'wallet.dat' to a specified location.

-Automatic backup frequency would be specified by a radio box defaulting to a 'monthly' interval.
-Automatic backup frequency radio box would allow options for changing the frequency from the default 'monthly' to 'weekly', daily', & 'after each transaction'.
-Automatic backup root path to be user-definable, but defaulting to a sensible location.
-Automatic backup path to present an radio box option to allow for a new directory to be created in the 'Automatic Backup Root Directory' path, such that a new directory named [Current Date/Time] is created to backup the wallet.dat to, so as to provide the option to not overwrite the most recent backup, should the user wish.

[/mywishlist]

Some users want:
-To be able to rename the resulting 'wallet.dat' file, and as such it would be desirable to implement logic in the Wallet restore function(s) such that its name is automatically changed back to 'wallet.dat' from its renamed state to ensure proper operation of the client.

**Comment by vikramrajkumar** [comment]
Would be nice but not happening for the foreseeable future. These days we are preferring the model in the light wallet where we have a single deterministic seed that can recover everything.
