### ISSUE TITLE
Insufficient funds with dust

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/bitshares#916]
https://bitsharestalk.org/index.php?topic=10911.msg143768#msg143768

**Comment by vikramrajkumar** [comment]
There are very many 1 satoshi balances in the blockchain, which may be due to this.

**Comment by vikramrajkumar** [comment]
Unable to reproduce; closing for now.

**Comment by vikramrajkumar** [comment]
Changed my mind; too many coincidences.

**Comment by VoR0220** [comment]
Has there been any other reports of similar things happening? Have you been able to reproduce?

**Comment by vikramrajkumar** [comment]
There are lots of 1 satoshi balances in the network. I have not been able to reproduce or find a possible cause.

**Comment by pmconrad** [comment]
See also https://bitsharestalk.org/index.php?topic=14545.msg189741#msg189741

Maybe a rounding issue in the GUI?

**Comment by vikramrajkumar** [comment]
Possibly related: #923

**Comment by vikramrajkumar** [comment]
GUI rounding behavior changed by: https://github.com/BitShares/web_wallet/commit/a4798209779ab9923608209fd69fac088bbd0b53

**Comment by vikramrajkumar** [comment]
Closing again; let's chalk it up to market rounding errors and GUI rounding behavior for now.
